refersto::[Hiram Merrill](./../../people/Merrill-line/Hiram_Merrill.html)
refersto::[Lucy Witherell](./../../people/Merrill-line/Lucy_Witherell.html)


## Transcription
Name of Groom Hiram Merrill
Name of Bride Lucy R. Witherell
Residence of Groom Addision, Vt.
Date of marriage February 21, 1862
Age in years 42
No. of Marriage 2nd
Occupation Farmer
Father's Name Aaron Merrill
Mother's Name Nancy Merrill
Name of Party Officiating F.W. Olmstead, Minister of the Gospel
Town Bridport
Certified Copy W.S. Bennett Town Clerk



## Citation

New England Historic Genealogical Society; Boston, Massachusetts; State of Vermont. Vermont Vital Records through 1870

###### Description

Surname Range: _Merchant-Metcalf, M_

###### Source Information

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ . Lehi, UT, USA: Ancestry.com Operations, Inc., 2013. 
Original data:State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts.