refersto::[Horatio Nelson White](./../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Susan Spaulding](./../../people/Merrill-line/White-line/Susan_Spaulding.html)


## Transcription

Name of Groom White, Horatio N.

Name of Bride Spaulding, Susan B.

Residence of Groom Panton

Date of Marriage Apr. 13, 1880

Age in Years 77

Occupation Farmer

Place of Birth Essex

Father's Name Ebenezer White

Mother's Name Candace

Name Party Officiating Jas. Gibson Johnson - Pastor

Town Panton

?? H. TenBroeke Town Clerk

## Citation

#### Source Citation

New England Historic Genealogical Society; Boston, Massachusetts; _State of Vermont. Vermont Vital Records, 1871–1908_

#### Source Information

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2013.

Original data: State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.

State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts
