
## Transcription

Name of Bride: Grandey, Ellen M.

Name of Groom: White, Wm. E.

Residence of Bride: Bridport

Date of Marriage:Nov. 19, 1859

Age in Years: 18

No. of Marriage: 1st

Place of Birth: Panton

Father's Name: Grandey, Truman

Mother's Name: Grandey, Polly

Name Party Officiating: Rev. W.J. Stevens

Town: Bridport

## Source

#### Source Citation

New England Historic Genealogical Society; Boston, Massachusetts; _State of Vermont. Vermont Vital Records through 1870_

#### Source Information

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2013.

Original data: State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.

State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts.



## Notes

refersto::[William E. White](./../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Ellen Grandey](./../../people/Merrill-line/Grandey-line/Ellen_Grandey.html)
refersto::[Truman Grandey](./../../people/Merrill-line/Grandey-line/Truman_Grandey.html)
refersto::[Polly Myrick](./../../people/Merrill-line/White-line/Grandey/Polly_Myrick.html)

