
 

refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)

## Notes



Postmarked Dec. 20, Buffalo. The year "1848" pencilled by a later hand on the envelope is confirmed by the subject, since Henry George also responds directly to an inquiry from Horatio Nelson about the same Dr. Allin in [1848-07-02-HGW-to-HNW](./1848-07-02-HGW-to-HNW.html).

Who is Jewett?


## Synopsis

Henry George White in Buffalo writes to Friend Adams White in Panton. 

Only one sheet of a longer letter is preserved. The surviving two pages (front and back of the sheet) are entirely devoted to a tirade about the same Dr. Allin Horatio Nelson had asked about in July ([1848-07-02-HGW-to-HNW](./1848-07-02-HGW-to-HNW.html)). Henry George considers Allin a fraud, and compares him to Joseph Smith


## Transcription

Tell H N White that I believe the said Doctor allin to be a great Humbug & Liar & that instead of having the Doctors under his controll they discountenanced him altogether & that his associates were of not the most respectable character & that instead of his being Rich as he represented himself to be his was verry poor & that I think he will not molest Jewett for the more Some things are stired the worse it is When he came back here he had Several hundred dollars with him no doubt obtained from Some of his dupes poor Simple fools way down in Vermont You know that Jo Smith had his believers & that people that are honest are prone to believe all bold pretenders honest likewise especialy if they do not look cooly at the things as they pass, he had (I mean Allein) but one or two who believed anything he said in this city & now has gone off from here & left his babe with strangers promising to return soon & whether he will do so or not remains to be seen Yet at any rate many do not believe he will call for the child he boarded while here with one Lindsay a Swinestealer & the man Barker So far as I know is an Honest respectable man & has been helped by him as he believes but whether or no such is the case I am led to doubt for perhaps nature done the most for him after all the others that he helped as he aren any men that have been ailing for some time & no doubt some what whimsical & their mind only to be doctored by one who could boldly affirm he could do some great thing & they would fancy themselves well again 

I do not wish to get into any fuss with the aforesaid doctor nor do I like to see honest people duped by a designing knave & therefor I write as You see I have & hope You will use Your own discretion about the matter but I am confident that all can be proved if it was necessary but the law of Libel in this state is "the greater the truth the greater the Libel" You when asked about persons often replied that You knew nothing of them & thereby avoided the name of newsteller 

Jewett is a man of first rate character & was from Midlebury Vermont & is proprietor of the largest & most repectable paper in this city even if it is a Whig paper he is a very good sort of a man withal & likes to see all things done decently & in order

Many men here believe he tells stories of his exploits that been falsity on their face & think all he tells of himself is equaly false as for his time here being worth 50 dollrs per day I do not believe that while here he averaged 50 cts per day & I heer he did not pay all the bills he ought to have done. I am sorry to hear that he could so easily dupe the citisens of my own native state but for all they are sometimes as green as the hills of their own state