





refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Candace Smith](./../../../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)

Refers to without naming George's wife [Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html), Hiram's wife [Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)





## Notes
No envelope.

Torn sheet.

## Synopsis

 

Ebenezer in Burlington writes to Horatio Nelson in Panton.

Ebenezer updates Horatio Nelson on family news. The family has been isolated because of colera outbreaks.
## Transcription




Burlington Aug 9th 1849

Nelson

I thought perhapse you would like to hear from this region So I will write a few words to you and let you know how we are in the first place I am about the Same as when you ware at Burlington you Mother is pretty well much better than I would expect her to be considering the number of times She has had to go up & down Stares to attend to Adaline who has ben Sick ever Since you ware here about nine weeks in all She is confined to her Chamber & to her bed the most of the time Some days a little better and then back again no great alteration but if any She contineus to loos Strength but we are in hopes She will recover before long I have ben to Keeseville they ware all well and look prety slick about the premises Artemas has ben over twice Since you ware here he has ben in your neighbourhood twice looking for hay he told me he bough 60 Tons of Capt. Sherman for $7.00 per Ton perhapes he is now that way now giting it presed. I have had two Letters from George he writes that the Colera rages thare to an allarming degree but he don't apear to be alllarmed he goes right amonst it if it becomes necessary I learned the same by a Man who came direct from Buffalo who took Tea with Geo. his Family ware well Geo writes to have me say to you that you had better take the Enquirer out of the office untill the time was out for which he subscribbed he thought the ware woth the postage and I think so to we call it now a good paper we all read it. he has since wrote me that he had Settle the subject with you and the publishers also think the must feel rather mean why don't you write to him think hard that you don't. Hiram & Family are prety well although his wife has had another time of bleeding but they are not allarmed we expected some of your young Folks up here before now but I suppose you ware affraid of Colra there has ben a few cases I believe of the real Colra but the cases have all ben traced to Intemperance or imprudance thares ben but two American who have died with it viz Mr. Stutson and Mr Lun a young man of 19 it is said by some that thares was not the real Colra the Widow Day Died a few days since with the Colra Morbus age 75 we are all dried up we shall have no potatoes I dont think I shall have half as many as I planted So you may prepare to find us in potatoes if we should live for you have had all the rain down your way we a good rain on Monday the Folks at the Grocery said it was on an account of Hiram's going to Meeting the day before but I don't believe it the Ground is moist down about Seven inches and I presum it is as dry as ashis four feet below if you are afraid to come up to see us yo could write can't you?

our best Love to all *tierd* Father 

H.N White Esq