
 

refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)


Candace is not named, referred to as "your Mother."

"A" must be [Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html). "G" will be [Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html) "Wm" is [William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)

## Notes and questions


Hiram is distant enough that Ebenezer writes a letter to him, but close enough that Cynthia has "ben down" to visit.

Is he in CA gold digging? Is she living with her family?

In 1850 census, Hiram, Cynthia and their then two children live with Ebenezer and Adaline, evidently after Candace's death that year. 

## Synopsis

Ebenezer in Burlington writes to Horatio Nelson in Panton.

He hopes to buy some fabric from his son to make a pair of "pantiloons."

## Transcription

Sunday 2 oclock PM. Sep 9 1849

Nelson

I and your Mother went to church in the four noon, but not being much entertained we stay at home this afternoon, and I have undertaken to write three letters one to Hiram and one to A. & one to G — your Mother & myself are as well as usual Adaline has ben Sick 13 weeks She is better to day, but has ben worse Since you left us, Cynthia has ben down but *(tear in paper)* She Set up yesterday I have not heard from her to day, but shall see her by & by you Mother wants the Children to save a good bunch of Cale seed, for she has got some Birds to feed. I want you to save me Cloth enough for a pare of pantiloons for you know if I had 1400 sheep I would give you some & I should like enough for a Coat if you have it to spare. that I will pay you for, in somthing perhapes I will let you have a *Mare* or Somthing of that sort, we expect Friend, Wm & George to see us before Potato Diging I think *Taters* wont be so very scarce after all as they are selling for 25 ct per Bushel we have had no letter from George for a long time I wish I could learn the reason

Love to all 

Father