
 

refersto::[[Ebenezer White]]
refersto::[[Horatio Nelson White]]
refersto::[[Frances E. White]]
refersto::[[Adaline White]]
refersto::[[Henry George White]]
refersto::[[Charles H. White]]
refersto::[[Friend Adams White]]
refersto::[[Hiram Smith White]]
refersto::[Cynthia Sawyer](../../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)


## Synopsis

Ebenezer in Burlington writes to Horatio Nelson in Panton.

Ebenezer provides a full acount of everyone's health, as well as treating his own own ailments with homeopathic pills that George sent to him.

## Transcription

Burlington March 2nd 1851

My Son

I did not expect to write you until I had seen you I expected you were here before this. Francis writes that you are nomore likely to be ready than you ware months ago. I am prety smart for me Adaline sliped down on the platform East door last monday week and sprained her wrist very bad we thought it was broke at first but the Doctor sais it is not but it will take longer to heal than if the bone had ben broken I reced a letter from Geo. yesterday 8 oclock A.M. with two little Bottls of Homapathy pills about the Size of Mustard seid directions to take 5 of one kind at night 5 of the other in the morning with a printed Directions what I might eat & Drink and what is prohibited, amongst the greatest comforts of life was that of Tobaco, so I laid my pipe on the stove and went to preparing and last night I took 5 and 5 this morning. I feel no better my head flies round like a top oh! my Tobacco I miss it more than all the rest but I will try to get along but have not Faith the bigness of one of the pils. George's Charles has ben verry Sick, but had got about well (?) sais he has writen to you twice but has had no answer I think that , Friend wont be likely to fall in Love with work immedately on his return from School I think he has improved his ways are easey and quite agreeable I think he would like to go through Colledge Give my love to all hope you are all well I shant watch at the South window any more for you for when you come we shall know it I had most forgotten Hiram we hear from him evry Mail by some one who writes, and Cynthia has one letter from him Since Friend was here and expect one next tuesday or wedensday he said he should write Father a *Thundering* letter, I expect it will come on the Telegraph. So if you are up here you will have a chance to read it if you please I have a miserable pen and I believe if I had a larger Chaw of Tobacco my hand would be more stidy you Father E. White
