
 


refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Syrena Adams](./../../../people/Merrill-line/White-line/Syrena_Adams.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)

## Notes

Syrena is not named but referred to as Horatio Nelson's wife

## Synopsis

Ebenezer in Burlington writes to Horatio Nelson in Panton.

An exchange of family news. Ebenezer has recovered from the illness referred to in [1851-09-03-HGW-to-HNW](./1851-09-03-HGW-to-HNW.html), despite having taken "the Homipathice humbug." Ebenezer is trying to stop delivery of a paper to Horatio Nelson and recounts the difficulties he has had getting the account settled up.

## Transcription


Burlington July 27 1851

My Son

I rec'ed yours of the 24 yesterday the day it was mailed I was very glad it had raind at your place for that I am indebted to you for a letter I hope it may rain often. I could not think of writing to you evry time it rains here for it rans almost evry day a more growing Season in the vilage was never known it Thunders now you say it is a long time since you rec'ed a letter from me I could say the same of you. I was glad to learn that your Wife & self have ben to Poultny and a happy visit that looks right. you and your Wif shold go among your friend & enjoy yourselves and not alwais be delving at home you have property enough, yes and to much if you had less you would have less on your minds I hope you visit George this fall I have a letter from him evry few days now the Potag is so cheap he says som-times he thinks he will never write to any of you again that you don't care anything about him, if you did you would write to him I am glad you have had a letter from Hiram am glad to hear he is well we have not had a letter from him since the 20th of March which is over four months we think strange that he has not writen you know the Mailes goes safe now or ought to for there is an Agent goes with them the same as the British Mailes go though here I wish you would send -the- the letter to Boy Friend when he comes up if thare is nothing Confidential in it I hope you will not forgit it you may concider your paper Stopes on Tuesday the 8 of this month I hapened to take him ?? on the eving at the express office he said it should be stoped from that time perhapes he never will think of it again I advise you not to take them out of the Post Office if he should continue to Send them I told him we had caled a number of times to sittle, but no one knew how it stood he said he knows it, but he coud to make it out, I told to do so & it should be paid I requested Frances to tell you write about how long a time was Due and what the price was when you commenced taking it. for I saw Man settle with his foreman for one Dollar per year if I am not Much mistaken he acknoleged that Hiram had paid him money for you I hope Friend will be up and Candace for she has not been here for a long time we expect a great display of Firework better than that of the 4th I have ben quite unwell this sumr and was when the Children ware here. I was on the Bed when they went away and did not know where they went or I shoud have said. good by to them, but neither of them saw fit to say good by to their old sick Grandfather I felt Grieved at the time but I lay up no hard feelings towards them they are young. neither did you My Son think to enquire after your old Farthe in your letter but Thanks to God my health is much improved and am quite smart for so old a person I am almost as well as I was before I took the Homipathice humbug I don't know of anything more to write but love to you all and may the blessing of God ever attend you is the prayer of your Fathe Ebenr White

PS. I had forgotten to tell that Adaline is well as usual but Cynthia has had ?? of Bleeding at the lungs as she thinks but is prety smart now

EW




H.N. White Esqr of Panton VT

I gues you cant read this what blunders
