 




refersto::[[Ebenezer White]]


## Notes

The death of Artemas' "little Hiram" refers to [[Hiram White]]

Who is Cad Wainwright? And the Willards house?


refersto::[[Ebenezer White]]
refersto::[[Horatio Nelson White]]
refersto::[[Adaline White]]
refersto::[[Henry George White]]
refersto::[[Artemas White]]
refersto::[[Hiram White]]
refersto::[[Hiram Smith White]]
refersto::[[Syrena Adams]]
refersto::[Candace White](../../../../people/Merrill-line/White-line/Candace_White.html)



## Synopsis

Ebenezer White in Burlington writes to Horatio Nelson White in Panton.

News includes the death of Artemas' son, arrangements for Horatio Nelson to help with winter food supplies since Ebenezer and Adaline have no cow or hog, and details on a fine house for sale "Dog Cheap" in Burlington.

## Transcription


Burlington Dec. 25 1851

 

My Son and all

 

I wish you mery Christmas we all ar well as usual except Adaline she has sliped down again and sprained her wrist so she cano't use it I had a letter from George not long since he tells of coming out hear this winter hope he will had a letter from Artemas informing us of the Death of his little Hiram caused by canker Rash this is the fifth child he has ben called to part with by death the Lard has laid his hand heavy upon Him and often afflicted him in this way I hope he may have Grace to sustain him in those often afflictions. we have no word or letter from Hiram. you wrote of coming to see us I hope you will and bring your Wife & Candace with you and the Butter you told of and som Lard if you have it to spare for we have bouht no Hog nor do I expect to for thare is none to be sold. Oh! I want you to bring sausage enough for *Me* one meal -- Cad Wainwright offers his place for sail which he gave $2200 and laid out $300 for improvements and will sell it for $1600 you know the peace it is short of a mile from the Court House not far from Willards thare is a Good Brick House and out Buildings. all in fine repair and two acres of land it is the place Syrereane thougt she would like to live on it is Dog Cheap the Buildings cost about twice the amount he asks for the whole it giting dark and I shall look for nex Tuesday noon my love to all

you Father

it said to be the coldest day we have had this winter best sleighin you never see we keep no Cow and have no Hog
