

 


refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[Sister of Ann Quayle](./../../../people/Merrill-line/White-line/Sister_of_Ann_Quayle.html)
refersto::[Brother of Ann Quayle](./../../../people/Merrill-line/White-line/Brother_of_Ann_Quayle.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)
refersto::[Henry S. White](./../../../people/Merrill-line/White-line/Henry_S._White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)


## Notes

[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html) not referred to by name, only as Hiram's wife


## Synopsis


Henry George White in Buffalo writes to Horatio Nelson White in Panton. 

Henry George invites Horatio Nelson and his family to come to Buffalo for a visit. Henry George is late replying to Horatio Nelson because of a trip with his wife, Anna, to Ohio to see a sister Anna has not seen for fifteen years, and the the unexpected death of Anna's brother.

## Transcription

Buffalo 3d Sept 1851

My Dear Brother & family,

You undoubtedly think it quite strange that I do not write to You in answer to Yours of the 5th Aug but when You know the reasons You will be satisfied


We went up into Ohio to see a Sister of My Wife whom she had not seen for about fifteen years I went with her as no one did know about the point to leave the Railroad as she lived in a small country village some 8 miles from the line of travel I went with her & after staying I came back on my return intending to stay one day with her brother but found him sick & stayed 10 days & left My wife there & today I reced a telegraph stating he had died at noon Ann is still there & will no doubt providence permitting be with me on Saturday So you see our visit of pleasure ended in sorrow not that we went for we were glad to minister to his wants but we did not expect to see him quite so low, as he had left our house quite comfortable about 3 weeks before, his disease was quick consumption he was the best of *Brothers* 

We were glad to recieve so long a letter from you & that you were all so well for it is a source of real pleasure receve a letter from those we care for & that care for us in return

I would not wish to spin out this letter to an unusual length nor would I wish to hide from you our pleasure that you were coming to see us & hope your haying has gone off to suit you & that you will come do not let us be disapointed this time for it is too bad to be so, I have always said if you only had your minds made up you were half here & it is so. for the facilities are such you can come here in one & half days if you choose to do so, I will not enumerate to you all the inducements for you to come but one of them is that I hope you will meet with a welcome from each of us & you will be repaying some of your many debts due us which will be a source of pleasure no doubt

I was glad to hear from Hiram although he does never find time to write to me even one little scrap notwithstanding I have written as many as four to him & paid the postage on some of them too but no doubt he depends much upon my forbearance & good nature to overlook his deficiencies -- his wife wrote to me a letter that I answered on Sunday I am sorry that she is not as well as last Year but hope she may get better soon I have invited her often to come & see us & bring Henry with her

You say that you have all visited Burlington since I was at your house I regret that I have not but I somehow thought I would like to see you or some of you out here & so defered my visit waiting for you

I say I regret that I had never been there since the melancholy time I was there to bury my own dear Mother the best of earthly friends I know it would not be now as formerly & should not expect it, but I do not forget it would afford a pleasure to my father to have me come & see him again & I have promised him to come again soon I would like to come & go & see you all if I had time & means to do so for I have the desire

I shall write to Father & Artemas soon I am glad that Friend gets along so well with his studies & hope he will aim high in all his aspirations after knowledge ever bearing in mind to do all things well I would be glad to have him & Frances or any of you come over & see us

Our children are all quite well & write in sending love to all their Cousins Uncles & Aunts in your vicinity 

Excuse this as it is the 3rd this evening 

Your Brother

H.G. White
