
 

## Notes

The new nephew who has arrived in Keeseville is [Frederick D. White](./../../../people/Merrill-line/White-line/Frederick_D._White.html), born 26 September (i.e., exactly a month earlier). Frederick was Artemas and Lydia's ninth child.

Who is Samuel Dresen, whom George saw?

refersto::[[Henry George White]]
refersto::[[Horatio Nelson White]]
refersto::[[Ann Eliza White]]
refersto::[[Ebenezer White]]



refersto::[Frederick D. White](./../../../people/Merrill-line/White-line/Frederick_D._White.html)


## Synopsis

Henry George White in Buffalo writes to Horatio Nelson White in Panton.

Henry George adduces numerous arguments to persuade Horatio Nelson to come to Buffalo for a visit. These include details of local travel that is now so much easier in "the Cars" than with the earlier stage or canal journey (a mere 36 hours from Panton to Buffalo!), the many sights such as the wire suspension bridge at Niagara Falls, and along with the other conveniences in Buffalo "all Sorts of Meeting Houses."

## Transcription

Buffalo 26th Oct. 1851

 

Dear Brother & Sister

 

I recd a letter from Father last night & by it I learned that you had about made up your minds not to "come and see" us, I need not to tell you how much we were disapointed, for you will probably have expected that after so many years of promise & waiting to thus be deprived of an expected pleasure ---

I do not know what is the cause of your altering your minds, nor do I mean to question you concerning it, for you are both of you competent to manage your own affairs to suit yourselves

*We* would be glad if still you would come this fall for although it now snows a trifle it will in all human probability clear off & and then quite a "spell of good & pleasant weather will follow" during which you would have a good time to come & *pay* us a visit -- it is not now so great an undertaking as it was formerly for you know now a ride in the Cars is quite a comfortable thing to what it was upon the canal or stage & time is anhialated for if you leave *Your own House* in the afternoon of Wednesday Thursday night will undoubtedly find you at *our House*

So you see it is only 36 hours ride at the most, quite a short affair & we hope you will try it -- now I do not thus write to tell you what you do not know already only to stir you up to action by holding up to your view the feasebility of the thing & probably you will never have a better time to come than now, for you now have a *man* to leave with the affairs of the farm outdoors & a *woman* to look well after the things in the House & they are both well known to you & if you choose to take one of the small ones it will not cost you anything for I never paid anything for Anna Elisa when we went to Ohio & I saw Samuel Dresen on his way home from Burlington to the West & he had a wife & two children of the ages of 4 & 11 Years & he said he did not pay anything for them all the way out & back & took a first passage at that, so You see if You do not like to leave all take one or more along as it will not cost you anything & we would like to have the small ones pleased

Brother & Sister I would urge You by every consideration to Come & I promise to make all except the weather pleasant & will hope & pray for that even, so that there will be nothing in the way.

Our 3 children write with us in urging you to come out here for you know all children like to see their uncles & Aunts & Cousins So come along 

The weather this fall has been quite changeable & today we have had our first snow storm but I hope it will not be a beginning of winter for we usualy do not have it so soon here so dont be frightened from coming by fears of winter

We are all quite well at present & trust a continuation of the Same Sort as we are *cold water users* & *Homeopathists* & with them both trust to preserve a tolerable share of health &c so dont expect to find us sick for we seldom are & if you are when you get here, there is all *Sorts* of good doctors & you will be taken care of I assure you

I have plenty of every thing except *Cash* & can get enough for all practical purposes of that & I have no doubt you will be made comfortable while you are here

There are all Sorts of Meeting Houses here & you can be suplied with any Sort of worship & there is a Methodist place of worship within Seventy rods of our House & a smart(?) man to preach to all who choose to come & hear, but the place we attend is somewhat futher off So you see you can be suited in all things

*Niagara Falls* is within one hours ride of our house & there is a wire suspension bridge there which is well worth a ride from your home to here to see, independent of the falls which are some so they say, but I need not enumerate the many things to be seen on your way & while here & about here & on you way out here nor the good you will both recieve *Moraly Physicaly* & *Intelectualy* I mean the benefit to Body & Soul & every thing else to be benefited by a trip of a *day* & *a half* across one of *the states* "as is *a state*"

I wrote to Father last Sunday & recd one from him Yesterday informing me of another nephew at Keeseville if I were they I would quit & "cry enough"

