
 


refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[Ann Eliza White](./../../../people/Merrill-line/White-line/Candace-Smith-line/Ann_Eliza_White.html)
refersto::[George A. White](./../../../people/Merrill-line/White-line/George_A._White.html)
refersto::[Charles H. White](./../../../people/Merrill-line/White-line/Charles_H._White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[George A. White](./../../../people/Merrill-line/White-line/George_A._White.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)



## Notes

"our little girl" is Ann Eliza, now about 5

"our boys" are George W. (about 11) and Charles H. (about 7)

"our Brother" is the other yet unnamed one: Hiram

Artemas is back east, staying in Buffalo; Hiram is evidently still in CA starting on a new venture

Who is Hiram's partner W. Thomas?


## Synopsis

Henry George White in Buffalo writes to Horatio Nelson White in Panton.


Their brother, Artemas, has been staying in Buffalo with Henry George since March (!). Hiram apparently remains in California where he has started up a partnership in a new mining business that is "sure to make the partners rich."


## Transcription

Buffalo 1st Aug 1852

Brother

I find one of your letters dated 6th April & and I do not know whether it has been answered or not at any rate it has not been filed away & thinking perhaps you would like to hear from us here once more I thought to write to you a few lines

Of course in the first place we would write concerning our health which is at this time quite good at any rate is is passable -- our wife has gone for a few days into the country on a visit to some friends & has taken our little girl with her she has been gone since tuesday morning & as I requested her to stay until she made a good visit I hope she will & probably will be home this week Our Boys are quite well & as it is now vacation they will be out of school for a few weeks & I wish they were with you that they might *work* & *grow fat* but you are too far off to think of such a thing at present 


Our business has been quite good for this past spring since April but is now quite slack on & I am not sorry they hot weather makes me little inclined to work & as I have only a trifle to do it all comes round right

it is quite cool today however & has been since we had as fine a storm of *Thunder* & Lightning as one could wish to witness last Thursday night


Our brother Artemas is here & has been since last march to & perhaps may make up his mind to remove to this place to live at any a few days will determine he is quite well at present & has been since he came here he recieves letters quite often from Keeseville

Our Father wrote to me on the 23d & and I was glad to hear again from our Brother through him & also was glad that his garden was in so fine a condition & his health was so good he writes me that he has had a railing placed around the graves of these dear ones that are buried there where he no doubt soon epets to be laid by those that may survive him it is a melancholy yet a pleasant thing to thus make the place of burial of our friends our care & it gives us an assurance that when we too follow we may be held in kind remembrance by those left behind for we too must go

I know not how they manage there & who pays the expenses of the house but I do know that either of us would feel willing to contribute to the wants of our remaning parent & I hope you will find out & let me know how things are there that we may not wait until it is too late & when you do so write to me all the particulars

Our brother Hiram (whose wife was at your place the last I heard about her) it seems has not yet made his pile & has gone with W Thomas into another business a business that I am informed if done in any sort of order for & judgement is sure to make the partners rich that are in it if they are in the way of luck as the term is for an acquaintance of mine who has recently returned was in the same business only he was in the northern mines but was sick a great deal of the time & was robed of his cattle by White me who run them off but he says that it is a money making business I have seen a plenty from these places & some of them have been working near hiram & know him, I hope he may be returned to his family in *health* & *rich*

Buffalo is now close to Panton & only a short ride on the rail & perhaps you had better come & see fellow & his wife & children & city &c &c & the fall is about to come again when we shall expect some or all of you to see us here & if Cynthia is still at Panton I would again urge her if she feels able in body to come & stay a time with us by & bye when it gets a trifle cooler for some say it is sickly here but I think that possibly reports are exagerated there has been a few sudden deaths during the past week & some can be traced to the too free use of sour cherries & the Whig meeting at the falls


Perhaps I may as well fill this side as not so I will keep on until I stop -- -- 

I would like to know from friend if he does realy mean to go to California or what he intends to do for perhaps I might get him a situation somewhere out here if he likes & you desire it & I hope you will write to me friend

Frances I wish you had come back with me when we were at your house last winter for I fear another so good time will not come soon & I know you would have here been pleased & when you wanted to go back I could easily have gone with you if no good chance offered to go with good company

I hope William & also my namesake will not forget that they have an uncle her in Bufa & perhaps the next time they come to troy with those sheep their father may give them leave to come & see us here only 12 hours ride you know & also that youngest one named after my dear departed mother I hope you will be spared to grow up & be like her for then if God spares me I shall love you even more than I now do

Finaly one & all write as often as you choose but & if I forget to answer write again & I will send you one of the longest letters you ever received

Peace be with you all

Your Brother

HG. White
