




 







## Synopsis

Henry George White in Buffalo writes to his nephew Friend Adams White. Since Henry George is uncertain of Friend's "wherabouts," he addresses the envelope to Friend's father, Horatio Nelson White, in Panton.

Friend, now about 19, is "passing the trying time" of his life, trying to decide on his future, which could include anything from farming, to mining for gold in California, to setting out to another location to find a profession or occupatoin. Henry George offers advice. He encourages his nephew to visit Buffalo, with details to consider about the deadly cholera that is seasonal in Buffalo.

## Transcription


Buffalo 19th December 1852

My Dear Nephew

I hardly know how to write to you or what about neither do I know where you are or what doing

I have tried so long & hard to get your Father & Mother out here on a visit that I have nearly given it up for a bad jobb & think I will commence with you in order to see if there is any of you that desire to see us but as I knew that you sometimes taught school & perhaps might be so engaged that you could not come I did not know how to proceed in the premises so I write to you at this time to find out your wherabouts and your plans & if you are not engaged I & are of a mind to come from & make us a visit *we can* fix it if your parents are willing so you can come & perhaps bring along Frances your sister

I do not know but that I shall come along that way if I come to Boston on business if I do I will write to you when

Although it may not be as well to come here in the winter as the summer yet perhaps your Parents might be better willing that you should come here in the cold weather as then there is no cholera or like diseases to fear but I hope that we have the same kind Father God or Providence to take care of us here that looks after your interests in Vermont & if he wishes to remove you he could find means to do so even if you were in Vermont or any where else, but let that pass for the present 

We had some cholera here & many died & so many die when there is none, but there is something in that sound *cholera* that has a tendency to fill us with dread until after we get use to it -- but there is none now & we hope to be excused for the next season

All your Cousins are well & unite in wishing you all a Merry Christmas & a Happy New Year Your Aunt has a very bad eye it has been so inflamed that she could not see her & was obliged to keep dark for several days but through the goodness of God & the use of Homoeopathy & Hydropathy she is better & is now getting along quite well & I hope will soon be well -- I am as well as usual

It is now nearly one Year since I was at your Fathers House & saw you all in good health & spirits I hope you are so now & have been so throughout the season -- but many that were at that time alive have been called home to report & receve their rewards

Say to your Father to & Mother that I have not forgotten them but always have hoped that they would come & see us & now that they can come as well in the winter as the summer in nice warm Cars & comfortable too I will accept of no excuse except a short crop & a lack of desire to do so for when they can come inside of two days they can have no excuse about time &c so start them if you dont come

Say to Frances that I suspect she does not desire to come & perhaps some young man resides there that keeps her from coming if so I ask it of her to make him promise to come to Buffalo & the Falls on their wedding tour at least she could not wish to refuse me that as she is too kindhearted


Say to William & George if they ever run away to come & see us as it is much better to be with friends than strangers in such cases but I hope they will not think of such things but be good boys to & so become good men & not bring sorrow to the hearts of their Parents

Say to Candace I hope as she bears the name of my *Mother* Your Grandmother I hope she will try & be like her so that all may love her & so that she can make all around her happy even as she did & then when she comes to be called home can go rejoicing

I do not know what to fill up this side of the sheet with but it must be filled I suppose so I will try

I know not what your intentions are whether to go to California to get rich, to go to some place seeking a place or occupation or to till the ground & raise sheep cows &c and be happy but what ever you do my young friend strive to do it well & fix your aim high & your efforts to correspond & you need never fear the consequences, only strive to fix upon something & keep it always in view & never forget your obligations to your Father your mother that bore you in her arms & to your god that cares for you & watches over you & to your self Ever keeping these things in view you may become an ornament to society and a source of happiness to your parents -- you may think me preaching but I tell you that you are now passing the trying time of your life & you will look back & tremble when you think of it in after years for it is not a great while since I stood where you now stand & wonder at my escape & can only ascribe it to the good god who is ever neer & to the love I bore my Mother that I am here

Your Uncle H.G. White



## Notes



refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Syrena Adams](./../../../people/Merrill-line/White-line/Syrena_Adams.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Henry George White 2](./../../../people/Merrill-line/White-line/Henry_George_White_2.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)


The envelope is addressed to Horatio Nelson, but written to Friend. In the letter Henry George says he does not know exactly where Friend is; evidnetly he has sent the letter to reach Friend via his father.


Friend's relatives in Buffalo not referred to by name but by relation
