 


## Synopsis

> Ebenezer White in Burlington writes to Horatio Nelson White in Panton. The letter is begun on June 7, and posted after being continued on June 8.
>
> Along with usual complaints about not receiving mail, Ebenezer describes his abundant garden, and tells the dramatic story of an how arsonist was caught.

## Transcription


Burlington june 7 1852 

My Son Nelson

It is with a bosom filled with Grief that I now address you I am grieved that I have a Son who --who-- has a heart to neglect his natural earthly Parent as you done done it is over one third of year since you have written to me, neither have I heard from you either directly or indirectly except --by-- by the way of Buffalo, and what is the cause is more than I can divine. I know of nothing I have said or done to merit such neglect and it grieves me to think of it, I am alone as it ware, and no one to cheer me or comfort me in my Old age, and to be neglected who has formerly held a friendly corispondane if nothing more, is as much or more than I feel able to bare, it wears upon my mind, I should have writen you before had it not ben that I was expecting something from you in sake of a letter but have waited in vain. I hold a friendly and kind corispondance with all your Brothers even the one who is *seven thousands* miles from me has writen to me since you have, living short of 30 what does it mean? thare has ben a corispondance caried on betwixt the two Families the contents of which I know nothing of as I read none of the Letter nor heave any part of them read. I hope it is nothing to make dificulty between you and me, but I have done with this subject I have not a heart or a wish to dwell upon a subject so adverse to my feelings. I supose you have had prety much such kind of weather as we have heare cold and dry I fear you have sufered more by the douth than we have on account of your land being more Claye, but should think that the land around your home premises would be apt to stand the drouth being much of it moist and springey, ledges &c which may in some measure protect you, but having lands scatered about as I suppose yours must be is very likely some of it must suffer I think of you, and am affeard that not only you , but many others must suffer, but the *Lord* knows what is best for us although we short sighted Mortals do not see it in the light our *Heavenly Father does*. My Garden looks as well as any of my neighbours and better than some I worked very hard, and beyond my strength this spring to to keep my Garden clear of Grass and weeds it neve was so clean before, both of weeds and vegetables although the latter look better than I could expect concidering the season I think I shall have new Potatoes in 4 weeks and those precious things *Tomatoes* that I have tried for five or six years to love and can't beare the stinking things. I should think I have from fifty to sixty plants some of them ten inches high all looking very will ever so many Plants I stand ready to give to any one who may want. I wish I wish you had them --if you had them-- if you have not a plenty, as I believe you & your folks love them I have set out my early cabbege and have plenty left which I shall sell or give to particular Friends. Fruit looks very promising Rasberies White, Black and Red never looked as well, my Cucumbers Squashes &c look will and well they may for it is so cold that no Bug or Flicor-lis to disturb them we have scarcely seen a House Fli this spring

I know of nothing more to write that you would like to of and perhapse you will care but little for what I have writen, but it will cost you nothing but the reading and that is no small job as many blunders as I have made you sai I do not write as well as I once did, but you are young and can write if you are a mind to, and I hope you will have a mind to. it is not likely you will have a chance to write me many letters and at the rate you have written in times past but very few I have all your letter you eve wrote me packed up that you may read if you please after I shall be no more ---

I shall not mail this according to the date for I expect to see or hear from Hiram to night if I do I will write you give my love to your family. for I love you all. I pray our Hevenly Farther to put a right spirit within you, and bless you in spiritual and temporal blessings

Adieu

Your Father


PS. I do not ask any of you to visit me for if you want to see me for if you want to see me you will come without askin it is not likely I shall ever be able to visit you again but can't tell what may happen 

E.W

June 8 half past 4 PM.no Hiram nor letter or tidings we had a fine shower yesterday an other to day and is now sprinkling and looks likely for more for which we hope we all thankfull. Last Sabat night the wood pile on the South wharf belonging to the Steam Boat company was discoverd to be on fire which caused a great allarm, but was put out after distroying eigh or nine cords of wood had it hapened two or three ours later it must have distroyed perhapse the whole stores you know the wood lies close to to the west store the fire was discoverd a little before 10 oclock in the evening and last night it was set on Fire again about the same time of the night a Boat coming in gave the allarm and the two Follets being in the store they and perhapse others rushed out one on each side the store, and caut the Fellow, and on examingi him found Pouder and combustubles for setting fire they asked him what he did it for he said for Fun they put in jail he is a a lad abou eighteen or so, look lik a poor mierable chap I suppose they have had a court of inquiry to day but I have ben so unwell that I have not ben out today to learn further about it, I caght a terible cold yesterday Coughed a great deal last night and to day and feel as sore as if had ben to an old fashioned Raising. I am in hopes it will ware off, the lads name is Griffith & he does not belong to this Town

Adieu again Father


## Images

Front cover [IMG_3153](./../../../images/IMG_3153.html) Back cover [IMG_3154](./../../../images/IMG_3154.html)

Page 1 [[IMG_3155]] Page 2 [IMG_3156](./../../../images/IMG_3156.html) Page 3 [IMG_3157](./../../../images/IMG_3157.html) Page 4 [IMG_3158](./../../../images/IMG_3158.html)



## Notes


refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)




The son "7000 miles" away is presumably Hiram, still in CA

Who are "the two Follets"?