
 

refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[Syrena Adams](./../../../people/Merrill-line/White-line/Syrena_Adams.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[George A. White](./../../../people/Merrill-line/White-line/George_A._White.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)


## Notes

Henry George refers to Ann as "our wife."




## Synopsis

Henry George White in Buffalo writes to Horatio Nelson White in Panton.

Henry George writes upon returning to Buffalo from a visit to Panton with details of each leg of the long train journey home. He addresses each nephew or niece in order by age rank, and his advice to the children (now roughly ages 10-19) is a fascinating document of education and choice of profession in the mid-nineteenth century.
## Transcription

 

Buffalo Sunday evening 16 Feby 1852

Brother Nelson

I write to you at this time to let you know he arived safely here on Thursday morning after riding all night in the cars Log left Panton 7-o clock A.M. Wednesday made Vergennes 8 3/4- & left 9 1/2 made Rutland 11 1/2 & lay to 3 hours *impatiently* left at 2 1/2 & made Schenectady at 7 & at 7 1/4 left for Buffalo & arrived here at 9 1/2 having run slow & been detained somewhat during the night -- so you see that after you are once underway you are soon somewhere I write this to encourage you to come some time & see us

I found our children well but our wife is & has been sick her side troubles her & while I was absent it sweled up quite a lump & is now sore to the touch but is some better I do not know what it will amount to & as I am so hopeful perhaps I do not realy know how bad it is

Syrena I think if you & Nelson both realy desired to come out here you could find a good time to do so but Your household cares have so grown upon You that You do not think You can leave home is it right to to be so tied to one continual round of duties & have no time for recreation & relaxation

Friend I was glad to see had grown to be so large & fine a looking young man but I noticed you were uneasy & unsettled as if you did not realy know what you were going to do next now I know how you feel & it is not so long since I was of your age but what I can remember all about it you are now of the right age to be laying plans for the future & it is right you are but it is also right to come to some conclusion & be sure you are right & then go ahead to & if you desire to go to College do so & if you wish a situation in some other business if you try you can get into one & if you desire to learn some mechanical trade or business do so but *never learn the painters* for it is a bad one & at the mercy of any vagabond who chooses to adopt it, be sure you are right 

You talk of California now all the mining has been done heretofore in the river botoms & in such places that a single man could dig & wash his ounce or so as he choose in a day but those kind of times are gone by & hereafter the mining will have to be done by companies with a capital to crush the quartz rock & separate the gold & operations simply will not amount to much but probably as much or more gold will be dug as formerly you can make enquiries & read & you will come to the same conclusion -- come & see me

Frances Ann was quite disapointed in your not coming back with me for I had promised to have you with me if I could before I left but while I was at Burlington I heard such would not be the case & I need not try so I did not we would be glad to have you come out here & stay as long as you like & as long as it will be for your benefit & Ann thinks she & yourself would both be pleased if such should be the case & when you will write us you will come I will find some way to get you here

William I thought you were a little sulky on the morning that we came away but I asked your Father & he says you sildom get so of which I was glad to hear you now have grown to be quite a large fellow & I hope your mind will keep pace with your body but will depend somewhat on your own exertion so I hope you will spend all or a large part of your leisure time in some useful study that will make you think & reflect & thereby give ?? to your mind by exercise for it matters not what business you eventualy follow knowledge will not hinder you So *Read* & *think*

George you were probably named *after* me & if so I hope you will try & sustain the reputation of the name I think much of that name they tell me you do not care for books &c I hope you will try do away with the truth of such an assertion

Candace I was glad to hear & see that you liked school so well & hope you will always be as apt & willing to learn I know you will read the book I gave to you & I hope you will under-stand what you read for there are good stories in that book as well as in the others & when I come again I will talk with you about them but I shall not come again until some of your folks comes out & makes us a visit & then they will probably bring you with them so ask them to come

Finaly you see I have written you all a slice not so much because I wished to instruct any of you as to say something & let you know how I thought

Read all the books & write to us when you have done so & let us know what you think of them all

I hope to recieve a letter from each of you soon. for I like to write & will answer

The bird is safely here & sings merrily & that with my bird & the children fills the house with music

Finaly may peace & plenty ever dwell where you dwell & all the blessings of heaven attend you always amen

H.G. White
