
refersto::[[Ebenezer White]]
refersto::[[Horatio Nelson White]]



 


refersto::[[Ebenezer White]]
refersto::[[Horatio Nelson White]]
refersto::[[Cynthia Sawyer]]
refersto::[[Hiram Smith White]]
refersto::[[Henry George White]]
refersto::[[Adaline White]]


## Notes


Others mentioned:


Wm. Hickock may be 
refersto::[[William H. Hickock]]

"Weston" is probably
refersto::[William Weston](./../../../people/not-related/William_Weston.html)


"young Smalley?"
## Synopsis

Ebenezer White in Burlington writes to Horatio Nelson White in Panton.

Much of the letter concerns Ebenezer's complicated attempts to pay insurance fees on "the Building &c" Hiram's wife Cynthia is statying at Ebenezer's house and contemplating going to California to join Hiram. Ebenezer wants Horatio Nelson to dissuade her but without revealing that Ebenezer has mentioned the subject to him.

## Transcription


Burlington Nov 11 1852

 

My Son Nelson

 

I rec'd yours sometime ago informing me of your welfare, Business & also requesting me to pay our Town Representative the Insurance Money on the Building &c I started the next morning to see Wm. Hickock, but he had started for Montpeliar I tried to catch him but could not the Cars went faster than I could at this time of *life* knowing he would be home on Saturday night I went early on Monday Morning to his House, but he had left, but I overhalled him at the Depo he said he had rec'd no line from you neither ware the Books in hands but ware with Weston I went twice to Weston's office but could not see him I chanced to meet him He said young Smalley had the Books and not to trouble myself for he would call on me I knew Smalley called last year for the pay on Hiram's Insurance People hear don't send their money to Montpeelir when they want their Money thare is a Person appointed to collect it and when he calls I shall pay it I could not see you gave yourself and me so much trouble for nothing. I suppose in a Scaterd Population they do not do as in a place like this. I have no news only we had a New Moon a little past eleven this morning I suppose it will do you as much good as anybody I suppose your *Tribe ??* has let you know prety much how the Election has gone I have no comments to make. Our Family are all as well as usual except Cynthia she is quite unwell more so than she has ben since Hiram has ben gone she has a continual cough She calls it a bad cold I hope it is nothin worse, she still thinks of going to California I do wish you would come up and talk with her and discourage her it won't do to write because she would know I had writen you and She would be displeased I wish that you let any of your Family know that I have writen you on this subject for she would soon here of it I don't say with an intention to do harme, you can tell the ?? what is propper in this case and let that Sufise She had a letter from Hiram las Mail he was well and doing as usual I do think it would better for Hiram to come back and take care of his affares don't you but it wont do for me to say anythin in favor it what I have writen you is confidential on the Square if you please Hiram sais you have never writen to Him I read a letter from George a few days ago they ware well he says he has sent me two Blls Flour it has not arrived yet hope it will soon I am almost out I have a large hog and is fat it measuer five feet & 7 Inches round the boddy I inted to kill as soon as the weather is col. nothing more at present give love to all and come and see us Fens made or not made

Father


P.S. Adaline wishes me to ask you to let her have 20, 30, 40, or 50lb Butter. Butter is *low* here and hard to be had she will give you the highest Market price

