



 
 


refersto::[[Ebenezer White]]
refersto::[[Horatio Nelson White]]
refersto::[[Cynthia Sawyer]]
refersto::[[Hiram Smith White]]
refersto::[[Syrena Adams]]



## Notes

The last letter in the collection from Ebenezer. Its date is notably later than the death date Adaline had put on Ebenezer's tombstone!

The "Kid" is probably Horatio Nelson's youngest, [Candace White|Candace](../../../../people/Merrill-line/White-line/Candace_White.html)


Who is "Col. Smith"?


## Synopsis

Ebenezer White in Burlington writes to Horatio Nelson White in Panton.

Ebenezer informs Horatio Nelson about markets for hay and "stock," and how the prices have been skewed by farmers foolishly trying to take profits by selling too much of their stock. He also writes about the difficulty in getting butter, as he does in four earlier letters from 1849-1852 (all dated between October 31 and late December of the year).

This is the latest letter in the collection written by Ebenezer.

## Transcription
 

Burlington Dec 13 1853

My Son


As it has jut began to snow I have began to write. I have nothing particular to write but I write to plague you knowing if you were not pleased to have me write you would write back I wrote you a short time since but have recd no answer neither do I expect any to this, and should not wish any if you & your *Kid* would come and make us a visit which I should --- think you can as you can't make Fence now I should be happy to see you or any of the Family we are all pretty well Cynthia has got about as well as usual we expect a letter from Hiram every night but you will git none from him untill you have answered some of his letters he thinks hard of you for not writing poor Fellow he don't consider how much *Fence* you have had to make I wrote to you about Butter (it makes my han shake to to write the word) if you have any to Spare and don't like to let it.have it let me have it and the Dimes are ready (as Hiram sais) I have not tasted of any Butter for five or six weeks excep last Thanksgiven there was a smal piece put on my Pudding and it got melted before I could git it off but we always have it upon the Table and shall if you come whether you bring any or not, but it will not be as good and nice as Syreana makes

turn over

the Farmers abot here have got themselves in a fix they have sold off all their stock they could that they might git four times as much for their Hay as it is worth the cold weather has held off so long that every body has hay to sell for they can't buy stock to eat it up ho-ha-ha good I am glad Col. Smith and other good judges think Hay won't be over $5 or $6 at the out side next march I mean per ton but I don't care for I can't eat Hay any more than I do Butter perhapes it may help you if you have not ben foolish enough to sell off your stock I believe you usually have more stock than hay I think we shall have a milde Winter although it is now snowing those Rains we have along back ware in the place of snows don't you think so? if all the Rains we have had had ben Snow it wold be three feet deep if it had not melted 

it is gitting dark so I cant plague you any more now but I will son if I am well good by

Love as usual your Father

E White

P S the California papers say thare are 16,000 people in that place