

 





refersto::[[Henry George White]] 
refersto::[[Horatio Nelson White]]
refersto::[[Hiram Smith White]]
refersto::[[Ann Quayle]]
refersto::[[Ann Eliza White]]
refersto::[[Adaline White]]
refersto::[[Artemas White]]
refersto::[[Frances E. White]]
refersto::[[George W. White]]
refersto::[[Ebenezer White]]




## Notes

Who is Lenny? Could that possibly be [[Mary Ella White]]?

Horatio Nelson and Syrena have finally visited Buffalo!!

"Out little girl" is Ann Eliza, now about 7 years old

Hiram has moved out from his "old home" shared with Adaline! Does this imply that Ebenezer has died?

Henry George urges Horatio Nelson to have his boys write to HG's son George A., now about 13


## Synopsis

Henry George White in Buffalo writes to Horatio Nelson White and Syrena Adams White in Panton.

Horatio Nelson and Syrena have returned from visiting Buffalo. Henry George shares his worries about their brother Artemas, and discusses the arrangements ensuing on the recent death of their father, Ebenezer. (Note that Ebenezer was still alive and writing to Horatio Nelson in December of 1853, [1853-12-13-EW-to-HNW](../1853-12-13-EW-to-HNW.html)) Henry George also refers to his booming business, now up to 25 employees.
## Transcription

Buffalo 12th March 54

Brother Nelson & Wife

I have waited for some time to hear how you arrived home after your visit I recd a letter from Hiram who stated to me that you all got along well & arrived in Poultney the first day or night & staid 2 nights &c &c

We were both pleased that you all came out to see us but regret that it was so cold that we could not get around any better than we did as then we could have seen things better but as it is you will have to come again when it is not so cold, now you have learned the way it will not be as hard to do so

My wife was half sick while you were here with a severe pain in the side had too much grit to let me know of it lest is should distract from the pleasures of the visit, if it was not for that she would have gone round with you more, it was in fact caused by having to be with our girl so much but we do not always have such a girl mostly better yet often worse but the bad are off in quick time

I am sorry that Hiram found it necessay to leave the old home & his sister but so it is & I will note interfere I pity her, poor thing for after all she is our only sister I pity her 

I rec'ed a letter from Brother Artemas he is in New York & was quite sick or rather he had been so, I hope he is better now, he poor fellow seems to have a long streak of bad luck or rather he seems to be going down stream. Jast I know how how it will be but I hope he will have a turn of luck soon if he does not he will become discouraged & perhaps drink for we know not how things will go with any of us so let us be kind to one another so that we shall not accuse ourselves of being accessing to to anything that may occur

My Business begins to start I now have about 25 men at work & if the weather holds warm shall soon be as busy as I desire to be 

The weather has been quite warm all this month & the ice has left the creek but there is plenty in the lake yet to last for sometime to come I fear we shall catch it towards the close of the month for the old Sayings are sometimes true come in like a lamb go out like a lion, but in these days of spiritual manifestations one cannot tell what to think of

We shall always be pleased to have you come again both of you & will try to amuse you and also if Frances or any of the other children choose to come we shall be be happy to have them We would urge them if it was right to do so but as they have parents it is not

Yet if some one of your family does not come out here & see us I shall be sorry, I cannot tell whether the cholera will be here this season or not yet hope it will not if it comes will do our best to keep right & put our trust in providence & keep our barrels open as that is the best plan to keep it off

If some of the boys would write to George it might be the means of learning both to write & perhaps do them good if they write tell them to direct to my care as then he will get it

Hiram says Lenny wrote to him we hav not yet recieved it, I invite any or all of your boys & girls to write to us & promise to answer

We are all quite well at this present time but & hope you & yours are

I say to you again we were pleased that you came & hope you will come again we hav been to your house often & as the distance is short now let our visits be often 

All unite with me in sending to you all the love & kind regards

Has there anything been done about a stone to put to the grave of "our Father" let us act in concert & then all will have a chance it ought to be done 

The day has been beautiful & so is the night

Your Brother

H.G. White
