

 


refersto::[[Henry George White]]
refersto::[[Horatio Nelson White]]
refersto::[[Hiram Smith White]]
refersto::[[Artemas White]]
refersto::[[Adaline White]]
refersto::[James Herbert White](./../../../people/Merrill-line/White-line/James_Herbert_White.html)
refersto::[[Friend Adams White]]
refersto::[[William E. White]]
refersto::[[Frances E. White]]

## Notes

The "fine baby boy" is [James Herbert White](./../../../people/Merrill-line/White-line/James_Herbert_White.html)

## Notes

April 1, 1855 was Sunday. If HG literally means "three weeks old today" then James Herbert was born on March 11, 1855.

## Synopsis

Henry George White in Buffalo writes to Horatio Nelson White in Panton.

Henry George shares the news of a new son (James Herbert White). Most of the letter is concerned with questions about settling the family estate, over a year after the death of their father, Ebenezer.

## Transcription


Buffalo 1 April 55

My Brother

I have just wrote to Hiram & now write to you yet you both are my detters

Sometimes there is not so good a feeling existing as there should be between you all there & if it is so know perhaps you may not have heard the news about us here

We have another member of our family a fine Baby Boy three weeks old to day & that & its mother are doing quite well, better than I at one time expected for I thought that neither would survive but I feel thankful it is no worse

We here had a cold severe & bad winter & it is cold now & nothing for a great many to do & so misery is plenty among us everything is high & no work

I wrote to Hiram that I thought the best way to dispose of the BIble was to cast lots for it as that would be fairer than to put it up & let the one that had the most money to spen take it but cast lots for it & see who gets it. -- or ask the spirit of its late owner who shall have it & she will make her own choice suppose you try that way -- any way is fairer than the money way for it may be her wish for me to have it if so I would take it but if I was to bid against any of you her children my Brothers & Sister I would not give 10 cents I would rather imitate her example than have her Bible & if I had the Book without her spirit I would be constantly reproached. I have reproaches enough already

You ought to have taken these cattle of ?? & then allowed for them what they were worth to you & I would have stood by you in the matter & something would have been got out of the note

Settle up the concerns for the sake of peace & divide the old Jugs, Bottles, Corkscrews & other traps among you & save one old chair for me & I will be satisfied & for the sake of the money of our parents do let us try & live like Brothers "Love one another" if you love the money of her who raised us when young & helpless & if you desire to be a follower of Jesus do try & promote peace

I thank god that I live far away from all of you because I escape a part of the trouble & you do not hear what I am doing as much as you would if I were near you all, when I say you I mean all of you *Nelson*, *Artemas*, *Adaline* & *Hiram*

Live in peace & try not & love each other & remember that the spirit of our departed friends are constantly with you

Business I cannot tell how it will be this year but as usual I live in hopes

Money is hard to be got at & probably will be for some time I would like to hear from any of your children & wish they would write to me -- I suppose it would do no good to ask one or any of them to come & see us here this season but if they write I could tell Friend, William Frances or all of you write to me

Give my love to all or any of my friends 

Peace be with you & your family is my wish

Your Brother

H.G. White

