
 





refersto::[[Henry George White]]
refersto::[[Horatio Nelson White]]

refersto::[[Hiram Smith White]]
refersto::[[Friend Adams White]]
refersto::[[Ann Quayle]]
refersto::[[Artemas White]]
refersto::[[Adaline White]]
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)





## Notes

Friend is in Fondulac "engaged in the Post Office"!

HG has made Artemas his "agent" -- we're still trying to sort out the estate.


Who is "Mrs. Cock" ?



## Synopsis

Hiram George White in Buffalo writes to Horatio Nelson White in Panton.

It seems to be a time of transition for all of the White family. Of Horatio Nelson's children, his son, Friend, has gone west and writes fro Fondulac (Wisconsin), while William is sickly, which Henry George attributes to his school. The White siblings are still working through the settlement of their parents' estate. Henry George's business is prospering to the point that he has forty men working for him, but he would like to find some other, less demanding occupation. Hiram, previously engaged in the family grocery business in Burlington, is now a farmer, and wishes to travel west to see the country.

## Transcription

Buffalo 19th Aug 1855
 
My Dear Brother

Your letter of the 31 July came duly to hand I was glad that you were all so well I rec'd one from Hiram about the same time which I answered & if you have seen him you possibly may have seen the letter I rec'ed a letter from Friend dated Fondulac at which place he still is as you no doubt know engaged in the Post Office

I hardly know what to write to you about but no doubt before I get through shall fill the paper

Ann had a letter from Mrs. Cock affair from her home which she styles clovernook she apears to be quite pleased & let us hope that they all will be ever

I have not recd any letter from Artemas since but no doubt shall soon My reasons for making him my agent was that as I could not conveniently be there myself & he could be it would save delay & bring about a more speedy settlement & regret that anything unpleasant should have occured or that any expence should have been made but however I hope all will be finaly setted to the satisfaction of all by the bye who has got the old family Bible as I do not onw whoever gets I hope will be able to realize that our Mothers spirit will still be about them while reading it & that if they are not made better by its perusal, they read in vain Verify may thoughts would be gendered by having & reading it

I have not had any letter from Adaline for sometime but no doubt shall by & bye when she gets ready 

The weather usualy furnishes a topic for conversation & for Writing but no doubt you have the same kind there that we have which has been for the 5 days quite cold for August

My business has as usual kept me confined so I seldom get time be absent I have kept about 40 men at work which is more than usual for the time of the year & as a friend stoped with some days if he wrote to you of my perplexities & trails & of the effect upon me Moraly & physic-aly he will no doubt have given you to know my moral & spiritual state is quite low at times & so I desire to find some other business in which I should escape so many & constant perplexities which has a badd effect upon me -- I do not expect to find any business without trials but I know that there are some which have not so many. but I find myself like a boy upon a sled going down hill who cannot stop until he gets to the bottom & so possibly I my continue in this until I get to the end of this state of existance -- excuse me for the episod

We are all quite well & have been so our children all form finely & although they are not so large as yours it may be because they are not raised upon a farm & perhaps it is because that are not of so large stock at any rate they are not large nor as large as I could wish they were

I wrote to you to let William come out & see us during his vacation but as he did not come I presume he did not desire to do so -- I fear his school may have a tendency to injure his health & so I wished to have him come & see us & possibly it might have been beneficial to him I hope he will not pursue his studies if they still continue to affect his health for recolect that you never plant & reap or gather at the same time & he may now be planting the seeds of some disease which may prove a trouble to him in future -- but you as his parents ought to & probably do know if such is the case -- but friend said he was sickly

I wrote to Hiram to know how it came about that he took a turn in his life moraly & what sort of a sect he has he said he had not as yet united with any but loved all & desired to follow Jesus to which I say god speed you & I would that all of followed him closely & tried to become like him -- I hope he will even try & be like him as then he will become godlike & his state bothe here & after he leaves the body will be better for having tried to be like Jesus our example who came to lead us back to god from whom we had strayed

I do not know whether you ever believed that the spirits of our friends (angels) are constantly about us striving to influence us for our good but I do & the bible I think teaches the same & although I have not lately had any communications from my spirit friends owing to the presure of business yet I sill believe that they can & will communicate with us & that they still live & are sat far from us if we could realize it it would make us more circumspect in our acts & thoughts which are known to them as well

I need not tell you all or any any of you that we would be quite happy to have a visit from some of you this fall & as we have a *baby* which will keep us confined at *Home* you ought not to expect us there so send a delegation & let us known when you are coming

Hiram says he will go to the west this fall & see the country but as he is a farmer I do not see how he can until his crops are all in & then something else will be for him to do as farmers have but if I was in his place I would go & see the country & then I should know 

I sent you a semon preached here at the opening of our unitarian convention I hope you read it in order to know how some of us feel you my think if I am a spiritualist I cannot be a unitarian I see nothing conflicting in them only find spiritualism to be unitarianist theories carried out & proved that is as man lives & leaves the body his state will be in future & that he can still if he desires *progress* toward god & a high state of spiritual existance

My sheet is full -- Good bye H.G. White