
 

refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refertso::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)



## Notes

"your firstborn" is Friend Adams White, presumably still in Wisconsin where HG identified him as working in the Postal Service in [1855-08-19-HGW-to-HNW](./1855-08-19-HGW-to-HNW.html) 




## Synopsis



## Transcription

Buffalo 2d January 1856

Dear Brother

I was glad to receive a letter from you once more & thank you for it

I am glad to hear so good a report of the health & prospects of your family & I was glad to hear that William has well enough to keep a school notwithstanding I do not like the calling much less to keep one in my native town yet it is better than nothing but if he is truly fitted for the place it is well, for in order to form others well one should first learn to form themselves a thing that I have not yet fully learned, but my reasons for not keeping school in my native village is because a Prophet is without honor in his native place I trust these remarks will give no offence to William

You talk of selling out & retiring from business What will you go at as you cannot be idle if you try as "Idleness begets Vice" and an "Idlemans brains is the Devls workshop" so you see you ought not to retire in order to take your ease & be idle for we read of one that said soul thou hast much goods laid up for many days therefore eat Drink &c Yet it proved a bad investment to him poor fellow if we believe the record and it is as true now as it ever was no doubt, but I was only joking You probably have some project in view and & know how to mange your own affairs no doubt

Hiram says I always preached to him in my letters while he was in California & probably you may think I am doing so now but it is natural for me & I cannot help myself but I will try

I know not whether you have any desire to see the west if you have not I advise you to create a dsire, for I assure you that eastern men have no ideas of its extent & growth until they see for themselves & until you see & know you cannot tell how much easier they can raise wool & everything else that sells, then you can, also if you have a desire to make money you will see it is the place to do it also if one desires to spread themselves there they will find plenty of room & if one desires large views of life &c there is the place to generate them, but you will probably get plenty of such from your firstborn who is there but joking aside you ought to go & see the west

I received a letter from sister Adaline a few days previous to the receipt of yours. by it I learn that she has been quick sick this fall poor thing she must have felt lonely enough in the old home almost entirely forgotten or neglected by those of her own kindred, but she says she was not neglected by the neighbours who were extremely kind to her 

I see that you desire to dispose of the old place & say you will sell it to the first that offers be he Negro, Irish or French does it not seem to you to be a sort of desecration

I am right glad to learn that the affair at Burlington is so nearly setted I hope it is all satisfactory if not I cannot tell whose is the fault 

I recd from Artemas a sort of schedule of what fell to my share & by it I see that you got the Bible I know not how the division was made & whether all was satisfatory & would like to know for it was written to me that some said that I should not have the Bible if others had to pay 100 dollars (more than I would give for all the Bibles (to use) in the States) I never desired it & thought that Adaline ought to have it but presum all is right & have never received a word from any one since the division on the subject only barely the schedule from Artemas, I wrote to him to keep all of my portion that would bring the cash & only send me the *old chair spoon* & *Towels* & keep the rest for himself until I sent for them, he is quite poor & I feel sorry for him & would like to do him good if I can but he seems to be bound for bad luck or to be kept poor & possibly there can be no help for him all I fear is that he may become discouraged & take to drink for relief & if I can prevent it I will try & do so, for you know that it is written that "he that seeth his brother needy & does not relieve him &c it is a hard thing to see a poor fellow working hard daily striving to stem the river & finding himself continualy going down for & at the end of the year farther down than at the beginning

I took the liberty to send you the "Age of Progress" a paper printed here & devoted to spiritualism as you will see if you read it, these lectures are all recieved through the raps by an uneducated girl one that has had no educational advantages but you will know all about that if you read & if you are pleased with the papers you can write me if your desire 