project:
  type: website
bibliography: "biblio.bib"

date: last-modified 
website:
  site-url: "https://neelsmith.quarto.pub/personal/"
  title: "neelsmith"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home  
      - text: "Posts"
        file: posts.qmd        
      - text: "Family history"
        file: familyhistory/index.qmd    
      - text: "Sources"
        file: familyhistory/sources/index.qmd 
     
    
    right:
      - icon: person-circle
        menu:
          - text: "My professional work"
            href: https://neelsmith.quarto.pub
        aria-label: Home


format:
  html:
    theme: minty
    css: styles.css
    toc: true



