---
engine: julia
---

# Neel Smith: personal site


## What's here

I'm using this site to share some tidbits I've uncovered while researching the history of my children's family. Currently, the site includes a little [background context](./familyhistory/), and [a blog](./posts.qmd) section where I'm sporadically posting notes. 

I'm interested more generally in how to do historical research and use historical sources in writing for digital platforms. Future posts may also include some "DIY" notes on how I'm carrying out different parts of my research.



## Following updates

Notes in [the "Posts" section](/./posts.qmd) are sorted by date, so if you peek there, you'll see newest additions on top.

There's also an [<i class="bi bi-rss"></i> RSS feed](https://neelsmith.quarto.pub/personal/posts.xml) if you prefer to automate notification of updates.




:::{.callout-tip title="My professional work on line"}
I have a separate web site where I'm gradually migrating all of my on-line professional work. You can see it at [https://neelsmith.quarto.pub/](https://neelsmith.quarto.pub/) -- yes, that's just the root directory of the web service where this personal web site is located.
:::