## Source


## Transcription

*Page 2 of probate box*

Ebenezer White

Estate

Report of Division

---

Filed 26 July 1855

Recorded


*Page 3 of probate box*

To the Hon the Probate Court of the District of Chittenden.

Provenient to a warrant to us e???ed by the Hon. the Probate Court for the District of Chittenden as the subscribers having been first sworn agreeably to the direction of said warrant and the heirs having been notified and all being present by themselves or their Agents and Attorneys and having settled and divided among themselves all the Bank stock and notes and settled and arranged the nine dollars eighty two cents due the said Administratriors as in the warrant to so directed and having appraised the residue of the personal estate of the said deceased and ascertained the sum to be one hundred sixty dollars sixty two cents $160.02

one fifth part of which sum being $32.12

Whereupon we have set out and divided the said personal estate so estimated to and among Horatio N. White, Adaline White, Artemas White, H.G. White and Hiram S. White the heirs to the said deceased designated in said warrant, as near as could be done, and exhibited in the schedule affixed to this report, and follow that is to say

To the said Horatio N. White the

*page 4 of probate box*

| (*item*) | (*amount*) |
| ----------------------------------------------------------------------------------------- | ---------- |
| the articles imbraced in the following schedule attached to his name his full share being | 32.20 |
| To the said Adaline White articles as in schedule attached her full share being | 32.20 |
| To the said Artemas White Do. Do. | 32.20 |
| To the said H. George White Do. Do. | 32.10 |
| To the said H.S. White Do. Do. | 31.92 |

To the said Horatio N., Adaline, Artemas, H.G., and H.S. th?? susp?? heirs and assigns each the susp?? par?? so divided and sot?? to him or her as aforesaid in severally to his and her sole use benefit and behoof for ever.

Given under our hands at Burlington this 26th day of July 1855.

N. Lawly?
M.A. Ebents?
H.H. Mitchell 

Committee


*page 5 of probate box*


## Notes

refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)

