## Source

#### Source Citation

New England Historic Genealogical Society; Boston, Massachusetts; _State of Vermont. Vermont Vital Records through 1870_

#### Source Information

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2013.

Original data: State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.

State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts.

## Transcription

Full Name of Deceased Ebenezer White

Age 74 Yrs - Mos - Days

Date of Birth ?

Name of Parents ?

Name of Husband or Wife, if married Candace Smith White

Date of Death Oct. 31, 1852

Name of Cemetery Elmwood

A True Copy. Nov 4 1921. Attest: Edward B. Copley

Town Clerk of Burlington



## Notes

refersto::[Ebenezer White](./../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Candace Smith](./../../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html)