## Source
## Transcription

County Decatur Indiana State Board of Health Registered Number 35435

Bureau of Vital Statistics

Town Greensburg

No. I.O.O.F. Home St.

Full Name Fredrick D. White

**Personal and Statistical Particulars**

| Sex | Color or Race | Single, Married, Widowed or Divorced |
| --- | --- | --- |
| Male | White | Married |
 
HUSBAND of (or) WIFE of Sarah Jane Couch

DATE OF BIRTH (month, day and year) SEPT 26, 1851

AGE 87 Years 2 Months 27 Days

Trade, profession or particular kind of work RETIRED

Birth place NEW YORK

**FATHER**

Name Artemas White

Birthplace Vermont

**MOTHER**

Maiden name Lyda Brumley

Birthplace New York

Informant Wilbert Grayson

Greensburg, Ind.

Place of burial or removal South Park - Greensburg Date ?? 19 1938

Undertaker Chrs. R. Howe, Greensburg, Ind.

Was the body embalmed? Yes Embalmers License No. 3622

Filed 12.17.1938 G.M. Sanders

**Medical Certificate of Death**

Date of Death Dec. 19 1938

I hereby certify that I attended deceased from Apr 15 1938 to Dec 17 1938 and that death occurred on the above date at 4 A.M.

The principal cause of death and related causes of importance were as follows:

Prostatic Hypertrophy

Other contributory causes of importance:

Chronic? Nephritis

Signed by N.C. Allington?, M.D.

? 17 1938 Greensburg Ind

## Notes

refersto::[Frederick D. White](./../../people/Merrill-line/White-line/Frederick_D._White.html)
refersto::[Sarah Jane Couch](./../../overviews-people/White/Sarah_Jane_Couch.html)


"IOOF Home" is probably "Independent Order of Odd Fellows Home" in Greensburg, Indiana


