
refersto::[Hiram Merrill](../../../people/Merrill-line/Hiram_Merrill.html)


## Citation

#### Source Citation

Vermont State Archives and Records Administration; Montpelier, Vermont, USA; User Box Number: _PR-01922_; Roll Number: _S-30815_; Archive Number: _M-2050475_

#### Source Information

Ancestry.com. _Vermont, U.S., Death Records, 1909-2008_ . Provo, UT, USA: Ancestry.com Operations, Inc., 2010.

Original data:

- Vermont. Vermont Death Records, 1909-2003. Vermont State Archives and Records Administration, Montpelier, Vermont. 
- Vermont. Vermont Death Records, 2004-2008. Vital Records Office, Vermont Department of Health, Burlington, Vermont.
 
 
 
## Transcription

Full Name of Deceased Hiram Merrill
Usual Residence Addision, Vt.
Color white Age 93 yrs 1 mos. 11 days
Occupation Farmer
Birthplace Addison, Vt
Father's name Aaron Merrill
Father's Birthplace N.S.
Mother's Maiden Name Nancy Farron
Mother's Birthplace N.S.
Date of Death Oct. Month 13 Day 1910
Disease Causing Death Cronic Bronchitis.90
Contributing Disease Old age.
Medical Attendant Frank C. Phelps, M.D.
Town Addison Dec. 12th 1910 L.C. Seeger Town Clerk
