---
engine: julia
---

# Index

- [Adaline_White_death](./Adaline_White_death.html)
- [Anna_Serena_White_death](./Anna_Serena_White_death.html)
- [Bee_Neel_in_CA_birth_index](./Bee_Neel_in_CA_birth_index.html)
- [Bee_Neel_in_Social_Security_death_index](./Bee_Neel_in_Social_Security_death_index.html)
- [Candace_Smith_in_federal_mortality_schedule](./Candace_Smith_in_federal_mortality_schedule.html)
- [Candace_White_Palmer_death_certificate](./Candace_White_Palmer_death_certificate.html)
- [Cassie_Green_death_certificate](./Cassie_Green_death_certificate.html)
- [Daniel_Clyde_Henderson_birth](./Daniel_Clyde_Henderson_birth.html)
- [Ebenezer_White_birth](./Ebenezer_White_birth.html)
- [Ebenezer_White_death](./Ebenezer_White_death.html)
- [Eliza_Ann_White_death](./Eliza_Ann_White_death.html)
- [Elizabeth_Stagg_death](./Elizabeth_Stagg_death.html)
- [Elvira_Ann_Williams_death_certificate](./Elvira_Ann_Williams_death_certificate.html)
- [Frances_Hix_death_certificate](./Frances_Hix_death_certificate.html)
- [Frederick_White_death](./Frederick_White_death.html)
- [Hiram_Merrill_death_certificate](./Hiram_Merrill_death_certificate.html)
- [Hiram_Smith_White_death_record](./Hiram_Smith_White_death_record.html)
- [Horatio_Nelson_White_death](./Horatio_Nelson_White_death.html)
- [I.N._Gattis_death_certificate_summary](./I.N._Gattis_death_certificate_summary.html)
- [Jacob_Dubois__birth](./Jacob_Dubois__birth.html)
- [James_A._Merrill_MN_death_index](./James_A._Merrill_MN_death_index.html)
- [James_Marion_Neel_death_certificate](./James_Marion_Neel_death_certificate.html)
- [Joseph_Saudek_-_Nancy_Northern_marriage](./Joseph_Saudek_-_Nancy_Northern_marriage.html)
- [Juanita_Rush_death](./Juanita_Rush_death.html)
- [Julia_Euless_Chattanooga_death_certificate](./Julia_Euless_Chattanooga_death_certificate.html)
- [Marguerite_Merrill_birth](./Marguerite_Merrill_birth.html)
- [Marguerite_Merrill_death_certificate](./Marguerite_Merrill_death_certificate.html)
- [Mona_Rush_death_certificate](./Mona_Rush_death_certificate.html)
- [Moses_Smith_birth](./Moses_Smith_birth.html)
- [Moses_Smith_death](./Moses_Smith_death.html)
- [Owen_Burrow_death_certificate](./Owen_Burrow_death_certificate.html)
- [Robert_Neel_death_certificate](./Robert_Neel_death_certificate.html)
- [Stephen_Ayers_birth](./Stephen_Ayers_birth.html)
- [Syrena_Adams_birth_certificate](./Syrena_Adams_birth_certificate.html)
- [William_E._White_death](./William_E._White_death.html)
- [Willie_Blanton_death_certificate](./Willie_Blanton_death_certificate.html)
- [Zachariah_Smith_birth_record](./Zachariah_Smith_birth_record.html)