refersto::[Marguerite Merrill](./../../people/Merrill-line/Marguerite_Merrill.html)
refersto::[Anna Serena White](./../../people/Merrill-line/White-line/Anna_Serena_White.html)
refersto::[James Albee Merrill](./../../people/Merrill-line/James_Albee_Merrill.html)

## Source

#### Source Citation

New England Historic Genealogical Society; Boston, Massachusetts; _State of Vermont. Vermont Vital Records, 1871–1908_

#### Source Information

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2013.

Original data: State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.

State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts.

## Transcription

Name of Chilld Merrill, Margaret

Date of Birth 1895 Month March Day 3

Maiden Name of Mother Anna White

Mother's Birthplace Panton

Parent's Residence Addison

Full Name of Father Albert Merrill

Father's Birthplace Addison

Fahter's Occupation Farmer

