refersto:: [Moses Smith](./../../people/Merrill-line/White-line/Candace-Smith-line/Moses_Smith.html)

## Notes

Moses Smith, Jan 25, 1738, Shrewsbury.

Father: Ephraim. Mother: Hannah

From Vital Records of Shrewsbury



## Citation


New England Historic Genealogical Society. _Massachusetts, U.S., Town Birth Records, 1620-1850_ . Provo, UT, USA: Ancestry.com Operations Inc, 1999.

Original data:

- _Vital Records of Bellingham Massachusetts to the Year 1850._ Boston: New England Historic Genealogical Society, 1904.

- _Vital Records of Granville Massachusetts to the Year 1850._ Boston: New England Historic Genealogical Society, 1914.

- _Vital Records of Lawrence Massachusetts to the Year 1850._ Salem, MA: Essex Institute, 1926.

- _Vital Records of Lincoln Massachusetts to the Year 1850._ Boston: New England Historic Genealogical Society, 1908.

- _Vital Records of Richmond Massachusetts to the Year1850._ Boston: New England Historic Genealogical Society, 1913.

- _Vital Records of Shirley Massachusetts to the Year 1850._ Boston: New England Historic Genealogical Society, 1918.

- New England Historic Genealogical Society. _Vital Records of Chelmsford Massachusetts to the Year 1849._ Boston: New England Historic Genealogical Society, 1914.