---
engine: julia
---

# Images in directory `images/White letters-images`

- [IMG 3028](./IMG_3028.html): Letter of Ebenezer White to Friend Adams White, September 9, 1849: front cover with address.
- [IMG 3029](./IMG_3029.html): Letter of Ebenezer White to Friend Adams White, September 9, 1849: rear cover.
- [IMG 3030](./IMG_3030.html): Letter of Ebenezer White to Friend Adams White, September 9, 1849: interior with text of letter.
- [IMG 3031](./IMG_3031.html): Letter of Ebenezer White to Friend Adams White, September 9, 1849: unfolded exterior.
- [IMG 3032](./IMG_3032.html): Letter of Ebenezer White to Friend Adams White, August 9, 1849: first page.
- [IMG 3033](./IMG_3033.html): Letter of Ebenezer White to Friend Adams White, August 9, 1849: second page.
- [IMG 3034](./IMG_3034.html): Letter of Ebenezer White to Friend Adams White, August 9, 1849: final page.
- [IMG 3045](./IMG_3045.html): Letter of Henry George White to Friend Adams White, December 20, 1848: front cover with address.
- [IMG 3046](./IMG_3046.html): Letter of Henry George White to Friend Adams White, December 20, 1848: rear cover.
- [IMG 3047](./IMG_3047.html): Letter of Henry George White to Friend Adams White, December 20, 1848: first preserved page.
- [IMG 3048](./IMG_3048.html): Letter of Henry George White to Friend Adams White, December 20, 1848: second preserved page.
- [IMG 3049](./IMG_3049.html): Letter of Henry George White to Horatio Nelson White, July 2, 1848, page 1.
- [IMG 3050](./IMG_3050.html): Letter of Henry George White to Horatio Nelson White, July 2, 1848, page 2
- [IMG 3051](./IMG_3051.html): Letter of Henry George White to Horatio Nelson White, July 2, 1848, page 3.
- [IMG 3052](./IMG_3052.html): Letter of Henry George White to Horatio Nelson White, July 2, 1848, page 4.
- [IMG 3053](./IMG_3053.html): Letter of Artemas White to Horatio Nelson White, October 31, 1842: cover with address.
- [IMG 3054](./IMG_3054.html): Letter of Artemas White to Horatio Nelson White, October 31, 1842: back cover with seal, resued for calculations.
- [IMG 3055](./IMG_3055.html): Letter of Artemas White to Horatio Nelson White, October 31, 1842: unfolded exterior.
- [IMG 3056](./IMG_3056.html): image
- [IMG 3057](./IMG_3057.html): Letter of Ebenezer White to Horatio Nelson, July 17, 1842: cover with address.
- [IMG 3058](./IMG_3058.html): Letter of Ebenezer White to Horatio Nelson, July 17, 1842: rear of cover.
- [IMG 3059](./IMG_3059.html): Letter of Ebenezer White to Horatio Nelson, July 17, 1842, page 1.
- [IMG 3153](./IMG_3153.html): Letter of Ebenezer White to Horatio Nelson, June 7, 1852: cover with address.
- [IMG 3154](./IMG_3154.html): Letter of Ebenezer White to Horatio Nelson, June 7, 1852: back cover.
- [IMG 3156](./IMG_3156.html): Letter of Ebenezer White to Horatio Nelson, June 7, 1852: page 2.
- [IMG 3157](./IMG_3157.html): Letter of Ebenezer White to Horatio Nelson, June 7, 1852: page 3.
- [IMG 3158](./IMG_3158.html): Letter of Ebenezer White to Horatio Nelson, June 7, 1852: page 4.
- [IMG 3295](./IMG_3295.html): Letter of Henry George White to Horatio Nelson White, March 1, 1857:  cover with address.