

## Transcription

Bristol, Russel T., Panton, Vergennes p.o., was born in 1822. He was married in 1847 to Martha Jane Thompson, a daughter of James Thompson. She was born in 1828. They had a family of seven children born to them -- Willard R. (married in 1876 to Mary A. Richards, or Cornwall, Vt.), Edwin S., Ernest J. (married in 1878 to S. Imogene Harris), Carlton D. (married in 18767 to Anna M. Elitharp, of Bridport, Vt.)), Alice J. (married in 1881 to Sidney M. Harris), Arthur H., and Wallis H. (married in 1886 to Cornelia L. Sibley). Russel T. Bristol was a son of Noah anna (Stafford) Bristol. Anna was born in Essex, Essex county, N.Y. in 1794, and died in Panton, Vt., in 1865. Noah was born in Panton, Vt., in 1789, and died in 1838. They had a family of nine children born to them. Three sons and one daughter are now living -- Philemon L., Russel T., Abel,, and Mrs. Abigail Eno (now the wife of Rufus Eno). Those deceased are Philo (who died in 1885, aged seventy years), Stafford (who died in 1848, aged twenty-two years), Sybil (who married Watson Morgan and died in 1868, leaving a family of four children), Lydia (who married Charles Hayward and died in 1876, leaving a family of three sons). Noah Bristol was a son of Aaron and Sybil Bristol, who were natives of Harwinton, Litchfield county, Conn., and settled in Panton, Vt. 1785. Aaron Bristol was born in 1742, and died in 1823. They had a family of eight children -- Sybil, Chauncey, Levi, Rhoda, Lemon, Olive, Moses and Noah. Moses and Noah inherited the homestead by will from Aaron, and remained as partners until the death of Moses in 1826. He was born in 1786, and served in the War of 1812.


## Source


Smith p. viii
## Notes

refersto::[Russel T. Bristol](./../../../people/Vermont/Panton/Bristol/Russel_T._Bristol.html)

refersto::[Philo Bristol](./../../../people/Vermont/Panton/Bristol/Philo_Bristol.html)
