 

refersto::[William Goheen Hammond](./../../../people/Hammond-line/William_Goheen_Hammond.html)
refersto::[Wesley Hammond](./../../../people/Hammond-line/Wesley_Hammond.html)
refersto::[Mayberry Hammond](./../../../people/Hammond-line/Mayberry_Hammond.html)

## Notes


**Hammond Letter 1**

 

**Date**: December 2, 1856

**From**: W. G. Hammond [41]

**To**: Wesley Hammond [213]

 

 

_(_**_Original_** _of this letter is in possession of dhs, a gift from Aunt Emma [26], daddy's [8] sister, many years ago.  I have transcribed it here, trying to be careful to assure an accurate transcription. The original shows beautiful penmanship and other signs of a well-trained, studious writer._ 

      _DHS.  7 September 2001.)_ 

 

(**Note**:  Square brackets following a name indicate the person's identification number in The Master Genealogist, the computer software program in which I keep family data. Example: Wesley Hammon [213], W.G.Hammon [41]        DHS 06 September 2001)

 

Emory & Henry College

Dec 2, 1856

 

 

Dear Wes [213],

After waiting long and anxiously to receive a letter from some of those to whom I have long since written your letter came to hand and was read with more than ordinary satisfaction.  I was happy to learn something it contained and others I was sorry to learn. Among the latter class was the information that Harvey Moore was teaching school in a place where it conflicts so much with Mr. Campbell's interests.  I would not have thought Harvey, being under so many obligations to him, would act in such away toward his old friend and teacher, one whom he ought to revere as the guardian and tutor of his youth.  Such a course is a very ungrateful one. And one that I hope with not be pursued by many students who have been favored by such instructions as Mr. Campbell has so patiently given them in their younger days.  I now look back upon the hours spent in his care and wish that I had improved them better. If I had, now I'd be much farther advanced and the cost of an education would not have been so great.  Wes, do not put off till a later period in your course of Study things that you should now learned, such as the thorough knowledge of grammar and arithmetic, the reading of such books as will yield your mind a beneficial store of knowledge and fit it for the course of study you should pursue until you are past my present age.  As books worthy of attention I would recommend a careful and diligent perusal of all of Thomas Dick's works. "The Wonders of the World". - "Guide to Knowledge". - "The History of the Commonwealth of Rome". And a book title, "Harper's Family Library or History of the World from the Creation to the Deluge."

All of these books you will find at home.  The last one I read several years ago and am now studying Natural History which is nearly the same in substance as the contents of that book. So the study is greatly facilitated by having a previous knowledge of it.

So with most of the above numerated works.  You will find in them a great deal of what you would have to learn at College. Don't neglect now to obtain a complete knowledge of English Grammar for upon it is based almost the entire fabric of a good education. Understand this art well and you will have at command a style of writing, without which the best literary men cannot hold a fair reputation: for it matters not how much "sense" a writer may display if he is guilty of grammatical errors he is not looked upon as an elegant or refined scholar.  Many students here pouring over Latin & Greek have but an imperfect acquaintance with this exceedingly useful branch. (that is, grammar)

Now, if I have not already wearied you with advice let me insist on you writing compositions too with all your reading, for the two together are calculated to improve faster than most any other course.  

I am still well pleased at Emory and continue to study as my only source of enjoyment, for there is nothing here like "woman's smiles" to cause the thoughts to steal away from books.  It is now near the end of the present session and I must soon know whether I can stay here another term of 5 months. Since I am now situated I think it would be much better to remain till June as I now have my room furnished and am well started in learning and shall endeavor to improve the moment as they pass.  Tell mother [16] that I am faring well here and have excellent health.  I have not been sick since I came here.      I would delight much in seeing my old friends at this time, especially some of the girls; give my love to them all -- to Mr. Campbell and family present my sincere regards. Tell them that I often think of them now. May prosperity attend them and all the associates of my early years.

Until I see you I hope you and Mayberry [42] will assiduously apply yourselves to study and improve much while it will cost you but little.  

I herewith send you one of my compositions. It is the first one I wrote after I came.  I will try to send you more occasionally as I get time to copy them.

Write frequently.  I am always glad to hear from any one -- It was really funny about Harvey Moore loving Sue Medly so hard - I suppose she has cast so strong a spell upon his heart that he can't resist the "magic power" and in the desperation of his condition will ______ her to ease his throbbing heart, now burdened so with "love."

 

Remind Sam [37] that I wrote to him sometime ago and have not yet recd anything in return, and to Buck [40] I addressed a letter some weeks ago.  Tell Eliza [39] that I have been looking for a letter from her for some considerable length of time -- I hope to hear from her soon.   As you are going to school now and can have plenty time write, let me hear from you often --Let me congratulate you since you hold the honorable position of Lieutenancy -- My lessons now demand my attention.

 

Yours affectionately,

 

W. G. Hammon  (sic) [41]

 

_(_**_Note_** _that the personal signature does not put the letter_ **d** _on the surname.  Numerous early spellings of the name followed that pattern, and earlier still some spellings included two -_**a-** _letters:_  **Hamman.**  Dhs 7 September 2001)