
refersto::[Noah Rush Sr.](./../../people/Rush-line/Noah_Rush_Sr..html)

## Citation

#### Source Citation

_Wills, 1663-1978; Estate Papers, 1781-1928 (Randolph County)_; Author: _North Carolina. Division of Archives and History (Raleigh, North Carolina)_; Probate Place: _Randolph, North Carolina_

#### Source Information

Ancestry.com. _North Carolina, U.S., Wills and Probate Records, 1665-1998_ database on-line. Provo, UT, USA: Ancestry.com Operations, Inc., 2015.

Original data: North Carolina County, District and Probate Courts.
## Notes

Contents as listed on ancestry.com's digital version: 66 images, numbered 60900-60965 in ancestory's online viewer.

- Cover page: 1
- Sales paper: 2-6
- Petition papers: 7-10
- Sales paper: 11-25
- Order papers: 26-31
- Inventory papers: 32-34
- Account papers: 35-43
- Petition papers: 44
- Cover page: 45
- Petition papers: 46-47
- Order papers: 48-49
- Guardianship papers: 50-51
- Order papers: 52-53
- Petition papers: 54-58
- Account papers: 59-64
- Sales paper: 65-66

But relevant material seems to continue beyond this last image

I have saved locally image 60996 which I transcribe and annotate here:

### Transcription

Noah Rush's heirs:
x 1 Zebedee Rush
x 2 Nancy Wade
x 3 J. CLark Rush
x 4 Geo. Rush ~~Noah Rush~~
x 5 Milton Blair & wife Mary
x 6 Branson Briles & wife Dorcas
x 7 F. L. Johson & wife, M.M. Johnson
x 8 Alex Briles & wife Sally (last dead)
 x Children: 1 Noah Briles
 2 

### Identification

>x 1 Zebedee Rush

refersto::[Zebedee Rush 1821-1907](./../../people/Rush-line/Zebedee_Rush_1821-1907.html)

> x 2 Nancy Wade

refersto::[Nancy Rush 1812-1912](./../../people/Rush-line/Nancy_Rush_1812-1912.html)

> x 3 J. CLark Rush

refersto::[John Clark Rush](./../../people/Rush-line/John_Clark_Rush.html)

> x 4 Geo. Rush

refersto::[George Gregory Rush](./../../people/Rush-line/George_Gregory_Rush.html)

> x 5 Milton Blair & wife Mary

refersto::[Jesse MIlton Blair](./../../people/Randolph_county_lines/Jesse_MIlton_Blair.html)
refersto::[Mary Rush](./../../people/Rush-line/Mary_Rush.html)

> x 6 Branson Briles & wife Dorcas

refersto::[Branson Briles](./../../people/Randolph_county_lines/Briles/Branson_Briles.html)
refersto::[Dorcas Rush](./../../people/Rush-line/Dorcas_Rush.html)




