refersto::[[people/Gattis-line/Green-line/Harris-line/James Harris]]

## Notes

James Harris, 3rd Tennessee Militia, War of 1812. Applicant claims private to captain.

Born 2-10-1777, died 11-3-1863.
Enlistment 1-28-1814. Discharge 5-13-1814.
Grade Private
3rd regiment (Copeland's).

Address to send to:

Mrs. J.A. Proctor
PO Box 316
Scottsboro, AL
Name and location of cemetery: Williams Cemetery, Bedford County, Shelbyville, TN.
Submitted 4-25-1959.

Stamp says verified Nov. 13, 1959.



## Citation
National Archives at Washington DC; Washington DC, USA; Applications for Headstones for U.S. Military Veterans, 1925-1941; NAID: A1, 2110-C; Record Group Number: 92; Record Group Title: Records of the Office of the Quartermaster General

###### Description

Surname Range: _Harrington, Arthur W-Herndon, Morris J_

###### Source Information

Ancestry.com. _U.S., Headstone Applications for Military Veterans, 1925-1970_ . Lehi, UT, USA: Ancestry.com Operations, Inc., 2012. 
Original data:Applications for Headstones for U.S. Military Veterans, 1925-1941. Microfilm publication M1916, 134 rolls. Records of the Office of the Quartermaster General, Record Group 92. National Archives at Washington, D.C. Applications for Headstones, compiled 01/01/1925 - 06/30/1970, documenting the period ca. 1776 - 1970 NAID: 596118. Records of the Office of the Quartermaster General, 1774–1985, Record Group 92. National Archives and Records Administration, Washington, D.C.
