refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[Clarence Harris Rush](./../../people/Rush-line/Clarence_Harris_Rush.html)
refersto::[Elinor Agnes Rush](./../../people/Rush-line/Elinor_Agnes_Rush.html)
refersto::[Mona Rush](./../../people/Rush-line/Mona_Rush.html)
refersto::[Mary Lucille Rush](./../../people/Rush-line/Mary_Lucille_Rush.html)
refersto::[Mary Jane Rush](./../../people/Rush-line/Mary_Jane_Rush.html)

refersto MRs. T.E. Lassiter

## Source

*News and Record*, Greensboro, North Carolina · Thursday, December 17, 1936, page 5
## Transcription

**C. H. Rush**
(Special to Daily News)

Asheboro, Dec. 16. -- C.H. Ruish, 83, formerly superintendent of the water and lights department of Asheboro, died at his home on Academy street tonight at 7:30 o'clock after a prolonged illness. H was for many years railway express agent on the Asheboro and Aberdeen railroad.

Surviving are five children, C. Rush, chief of the Asheboro fire department; Mrs. Agnes Barker and Mrs. T.E. Lassiter, both of Asheboro; Mrs. Mona Rush Smith, Cambria, Va., and Mrs. J.P. Meador, of Aberdeen. Also surviving ar a sister, Mrs. Mary Jane Lowe, Asheboro, seven grandchildren and one great-grandchild.

Funeral service will be conducted at the First Methodist church at 11 o'clock Friday morning by the pastro, Rev. H. P. Powell. Interment will follow in the Asheboro cemetery. Mr. Rush was a lifelong member of the Methodist church.