## Source

*The Buffalo Enquirer*, December 30, 1902, Page 6. via Newspapers.com (https://www.newspapers.com/article/the-buffalo-enquirer-obituary-for-henry/167255876/ : accessed March 5, 2025), clip page for Obituary for Henry George White by user neel_smith_home


## Transcription

**H. G. WHITE DIES VERY SUDDENLY.** 

---

**WAS ONE OF BUFFALO'S OLDEST CITIZENS - BORN AT BURLINGTON, VT., IN 1814** 

**HERE FOR YEARS.**

---

Henry George White, one of Buffalo's oldest residents.and one of the city's most esteemed citizens, died at his home, No, 32 Irving Place, at 6 o'clock this morning. Death, although resulting from old age, was unexpected. Last night Mr. White retired as well as he has ever been during the past two years, and this morning he was discovered dying by one of the members of the family. A physician was summoned but dying expired as the physician crossed the threshold.

Mr. White was borning in Burlington, Vt.. June 8, 1814..

## Notes

refersto::[Henry George White](./../../people/Merrill-line/White-line/Henry_George_White.html)
