
## Source

*The Buffalo News*, December 30, 1902, Page 1. via Newspapers.com (https://www.newspapers.com/article/the-buffalo-news-obituary-for-henry-geor/167255857/ : accessed March 5, 2025), clip page for Obituary for Henry George White by user neel_smith_home
## Transcription

**H. G. WHITE DEAD.** 

---

**Buffalo's Oldest Citizen Died Suddenly at His Home on Irving Place.**


---

In the death of Henry George White, Buffalo loses its oldest resident as well as an estimable citizen. He was born in Burlington, Vt., June 8, 1814, and died at his home, 32 Irving Place, at 6 o'clock this morning. Death, although resulting from old age, was unexpected. Last night Mr. White retired as well as he has ever been during the past two years, and this morning he was discovered dying by of the members of the family. A physician was summoned, but the dying man n expired as the physician crossed the threshold.
## Notes

refersto::[Henry George White](./../../people/Merrill-line/White-line/Henry_George_White.html)
