
# Index

- [Anna_White_Merrill_death_notice](./Anna_White_Merrill_death_notice.html)
- [Bee_Neel_obituary_LA_Times](./Bee_Neel_obituary_LA_Times.html)
- [Calvin_Harris_Rush_obituary_in_Greensboro_News_and_Record](./Calvin_Harris_Rush_obituary_in_Greensboro_News_and_Record.html)
- [Charles_R._Smith_obituary_Roanoke_Times](./Charles_R._Smith_obituary_Roanoke_Times.html)
- [Claud_Gattis_obituary_in_News-Journal](./Claud_Gattis_obituary_in_News-Journal.html)
- [Ebenezer_White_incarcerated_Vermont_Sentinel_and_Democrat](./Ebenezer_White_incarcerated_Vermont_Sentinel_and_Democrat.html)
- [H.G._White_obituary_in_Buffalo_Enquirer](./H.G._White_obituary_in_Buffalo_Enquirer.html)
- [H.G._White_obituary_in_Buffalo_News_p._5](./H.G._White_obituary_in_Buffalo_News_p._5.html)
- [H.G._White_obituary_in_Buffalo_News](./H.G._White_obituary_in_Buffalo_News.html)
- [Hiram_Smith_White_obituary_in_Burlington_Free_Press](./Hiram_Smith_White_obituary_in_Burlington_Free_Press.html)
- [Isaac_N._Gattis_obituary_Murfreesboro_News_Journal](./Isaac_N._Gattis_obituary_Murfreesboro_News_Journal.html)
- [Isaac_Newton_Gattis_obituary](./Isaac_Newton_Gattis_obituary.html)
- [James_Green_obituary](./James_Green_obituary.html)
- [Judy_Gattis_wedding_plans_Rutherford_Courier](./Judy_Gattis_wedding_plans_Rutherford_Courier.html)
- [Judy_Smith_birth_announcement_in_Murfreesboro_News_Journal](./Judy_Smith_birth_announcement_in_Murfreesboro_News_Journal.html)
- [Louise_Neel_Gattis_obituary](./Louise_Neel_Gattis_obituary.html)
- [Moses_Smith_death_in_abstract_of_Columbian_Centinel](./Moses_Smith_death_in_abstract_of_Columbian_Centinel.html)
- [Sallie_Rush_obituary_in_Asheboro_Courier](./Sallie_Rush_obituary_in_Asheboro_Courier.html)
- [Shelley_Lindner_-_John_Henderson_wedding_plans](./Shelley_Lindner_-_John_Henderson_wedding_plans.html)
- [Susan_Winslow_-_Charles_Church_marriage](./Susan_Winslow_-_Charles_Church_marriage.html)
