refersto::[Isaac Newton Gattis](./../../people/Gattis-line/Isaac_Newton_Gattis.html)
refersto::[Cassie Green](./../../people/Gattis-line/Green-line/Cassie_Green.html)
refersto::[Edith Gattis](./../../people/Gattis-line/Edith_Gattis.html)
refersto::[Aliene Gattis](./../../people/Gattis-line/Aliene_Gattis.html)


## Source

Murfreesboro, *The Daily News-Journal*, Tuesday, Dec. 26, 1939, page 1.

## Transcription

**Funeral Services Conducted for I.N. Gattis, 73**

Funeral services were held from the residence on Church St. today at 10:30 o'clock for I.N. Gattis, 73, who died at Sarasota, Fla., at 6 p.m. Saturday following a heart attack.

He was a native of Bedford county but had made his home here for the past 25 years. Until his health failed, he was prominently identified with music houses throughout the south. He was a member of the First Methodist church.

He is survived by his wife, Mrs. Cassie Green Gattis; two daughters, Mrs. Will Gilmore of Murfreesboro and Mrs. E. W. Hill of Chattanooga, a son, Claude Gattis of Murfreesboro, and five grandchildren.

The funeral services were conducted by the Rev. Neal Frazier and the Rev. B.B. Pennington. Burial was at Evergreen cemetery under the direction of Woodfin-Moore.

Pallbearers were A.H. Smith, Tom McCord, T.S. McFerrin, William Earthman Will Co[illegible], E.C. Holloway, Sr. and Fr[illegieble]ry.
