refersto::[Judy Gattis](./../../people/Gattis-line/Judy_Gattis.html)

## Source

*The Rutherford Courier*, Smyrna, Tennessee · Tuesday, March 01, 1955, page 4.

## Transcription

### Miss Judy Gattis Completes Wedding Plans; Pre-Nuptial Parties to be Given

Miss Judy Gattis has chosen April 9 as the date for her marriage to David Hammond Smith of Cambria, Virginia.

Stanford Memorial Chapel, Oak Hill First Presbyterian church, Nashville, will be the scene of the morning ceremony with Dr. Walter R. Courtenay officiating at eleven o'clock.

Preceding the reading of the vows a program of nuptial music will be presented by Roberta Womac, vocalist, and Cyrus Daniel, organist.

Mr. Gattis will give his daughter in marriage and Miss Gloria Gattis of Milligan college, Tennessee, sister of the bride, will be the only attendant.

Ensign Charles Richard Smith will serve as his brother's best man and ushers will be George M. Bell and R. Kolmar Altizer of Cambria, Virginia.

Following the wedding, Mr. and Mrs. Gattis will entertain at a breakfast at Oak Hill. Assisting with the affair will be Miss Jan Dourhit, Miss Betty Ray Clark, Miss Frances Smith, Miss Glover Dale Tarver and Misses Sara Jo and Nancy Wallen.

The bridegroom-elect is student minister at Oak Hill and Miss Gattis is organist and Youth choir director at the chuirch.

**Luncheon is given**

.... [Continues]....
