
## Source

Murfreesboro, Tennessee, *The Daily News-Journal* - 24 Nov 1995 - 2

www.newspapers.com

## Transcription

**Louise N. Gattis**

Services for Mrs. Louise Neel Gattis, 83, Murfreesboro, who died at home Thursday, are set for 3 p.m. Sunday at First United Methodist Church.

Her parents were the late Robert and Willie Blanton Neel and her husband was the late Claud Gattis.

She is survied by two daughters, Judy Gattis Smith of Richmond, Va., Gloria Gattis ANdrews of Murfreesboro; five grandchildren; and seven great-grandchildren.

She was a member of the Murfreesboro Women's Club, United Daughters of the Conferederacy, Delta Kappa Gamma honorary educational society, Retired Teachers Association and the First United Methodist Church. She taught at McFadden School for 32 years.

Memorial contributions may be made to her church, Linebaugh Library, or to Hospice of Murfreesboro.

Visitation will be held from 2-4 p.m. Saturday at Jennings & Ayers Funeral Home.

Daily News Journal, Nov. 24, 1995.


## Notes

refersto::[Mary Louise Neel](./../../people/Neel-line/Mary_Louise_Neel.html)
refersto::[Robert Wilburn Neel](./../../people/Neel-line/Robert_Wilburn_Neel.html)
refersto::[Willie Saudek Blanton](./../../people/Neel-line/Blanton-line/Willie_Saudek_Blanton.html)
refersto::[Claud Gattis](./../../people/Gattis-line/Claud_Gattis.html)
