
refersto:: [[Moses Smith]]
refersto:: [Lydia Jepson Smith](./../../people/Merrill-line/White-line/Candace-Smith-line/Lydia_Jepson_Smith.html)

## Notes

Moses Smith married Lydia Smith on 30 Apr 1760 in Shrewsbury.


## Citation

Family History Library; Salt Lake City, UT; _Film # 0759526_

#### Source Information

Ancestry.com. _Massachusetts, U.S., Compiled Marriages, 1633-1850_. Lehi, UT, USA: Ancestry.com Operations Inc, 2005.

Original data: Dodd, Jordan, Liahona Research, comp. _Massachusetts, Marriages, 1633-1850_. With some noted exceptions all marriage records in this collection can be found at the Family History Library in Salt Lake City, Utah, and may be available through Family History Centers throughout the United States. See table below for information listed.

#### Description

This database is an index to approximately 838,000 individuals who were married in select areas of the State of Massachusetts, USA, between 1633 and 1850. Information that may be found in this database for each individual includes their name, gender, spouse's name, marriage date, marriage location, and source information