



## Citation

The National Archives in Washington, DC; Washington, DC; _Registers of Signatures of Depositors in Branches of the Freedman's Savings and Trust Company, 1865-1874_; ARC Identifier: _566522_; Record Group Number: _101_; Record Group: _Records of the Office of the Comptroller of the Currency, 1863-2006_


## Transcription

No. 2894

Record for Artemas White

Date, June 30, 1871

Where born, Burlington Vt.

Where brought up, Burlington

Residence, Keeseville, N.Y.

Age, 63

Complexion, White

Occupation, Traveling Agent

Works for, Anderson P -- Res 174 Miller St. N.Y.

Wife or husband, Lydia.

Children, Candace Myra Mary Ella, Fred D.

Father, Ebenezer (dead)

Mother, Candace (dead)

Brothers and sisters, Horatio Nelson -- & Henry Geo. & Hiram Smith & Adaline.

remarks, Dst. First Natl Troy on First Natl N.Y. $4.058.33 less $3.82. $4.054.51 balance

Signature, (See Special Record)


## Notes


refersto::[Artemas White](./../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Lydia R. Brumley](./../../people/Merrill-line/White-line/Lydia_R._Brumley.html)

refersto::[Candace Myra White](./../../people/Merrill-line/White-line/Candace_Myra_White.html)
refersto::[Mary Ella White](./../../people/Merrill-line/White-line/Mary_Ella_White.html)
refersto::[Frederick D. White](./../../people/Merrill-line/White-line/Frederick_D._White.html)

refersto::[Ebenezer White](./../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Candace Smith](./../../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html)

refersto::[Henry George White](./../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Adaline White](./../../people/Merrill-line/White-line/Adaline_White.html)
