
# Index

- [Aaron_Curler_in_1850_census](./Aaron_Curler_in_1850_census.html)
- [Abel_Bristol_in_1850_census](./Abel_Bristol_in_1850_census.html)
- [Abigail_Gardner_in_1850_census](./Abigail_Gardner_in_1850_census.html)
- [Abner_Grandey_in_1850_census](./Abner_Grandey_in_1850_census.html)
- [Abner_Holcomb_in_1850_census](./Abner_Holcomb_in_1850_census.html)
- [Abram_Burwell_in_1850_census](./Abram_Burwell_in_1850_census.html)
- [Abram_C._Harris_in_1850_census](./Abram_C._Harris_in_1850_census.html)
- [Achsa_Holland_in_1850_census](./Achsa_Holland_in_1850_census.html)
- [Achsah_Burwell_in_1850_census](./Achsah_Burwell_in_1850_census.html)
- [Adalade_Bristol_in_1850_census](./Adalade_Bristol_in_1850_census.html)
- [Adaline_Kingsland_in_1850_census](./Adaline_Kingsland_in_1850_census.html)
- [Aegalus_Gaige_in_1850_census](./Aegalus_Gaige_in_1850_census.html)
- [Agens_Ganis_in_1850_census](./Agens_Ganis_in_1850_census.html)
- [Akins_Collum_in_1850_census](./Akins_Collum_in_1850_census.html)
- [Albert_Baker_in_1850_census](./Albert_Baker_in_1850_census.html)
- [Albert_Bristol_in_1850_census](./Albert_Bristol_in_1850_census.html)
- [Alexander_Branch_in_1850_census](./Alexander_Branch_in_1850_census.html)
- [Alice_Stone_in_1850_census](./Alice_Stone_in_1850_census.html)
- [Almeda_Prince_in_1850_census](./Almeda_Prince_in_1850_census.html)
- [Almira_Hall_in_1850_census](./Almira_Hall_in_1850_census.html)
- [Almira_Vriment_in_1850_census](./Almira_Vriment_in_1850_census.html)
- [Alonzo_W._Grandy_in_1850_census](./Alonzo_W._Grandy_in_1850_census.html)
- [Alvan_Grandy_in_1850_census](./Alvan_Grandy_in_1850_census.html)
- [Amanda_Haywood_in_1850_census](./Amanda_Haywood_in_1850_census.html)
- [Amasa_Benson_in_1850_census](./Amasa_Benson_in_1850_census.html)
- [Amos_Boyers_in_1850_census](./Amos_Boyers_in_1850_census.html)
- [Angeline_Pond_in_1850_census](./Angeline_Pond_in_1850_census.html)
- [Ann_F._Hays_in_1850_census](./Ann_F._Hays_in_1850_census.html)
- [Ann_Newgent_in_1850_census](./Ann_Newgent_in_1850_census.html)
- [Anna_Bristol_in_1850_census](./Anna_Bristol_in_1850_census.html)
- [Anna_Holcomb_in_1850_census](./Anna_Holcomb_in_1850_census.html)
- [Anna_L._Burwell_in_1850_census](./Anna_L._Burwell_in_1850_census.html)
- [Anna_Orkins_in_1850_census](./Anna_Orkins_in_1850_census.html)
- [Anna_Stedman_in_1850_census](./Anna_Stedman_in_1850_census.html)
- [Annett_Curler_in_1850_census](./Annett_Curler_in_1850_census.html)
- [Anthony_Burwell_in_1850_census](./Anthony_Burwell_in_1850_census.html)
- [Anthony_Depuy_in_1850_census](./Anthony_Depuy_in_1850_census.html)
- [Anthony_Trudo_in_1850_census](./Anthony_Trudo_in_1850_census.html)
- [Aramintha_Hobbs_in_1850_census](./Aramintha_Hobbs_in_1850_census.html)
- [Armena_Orkins_in_1850_census](./Armena_Orkins_in_1850_census.html)
- [Arthur_Adams_in_1850_census](./Arthur_Adams_in_1850_census.html)
- [Ashua_E._Haywood_in_1850_census](./Ashua_E._Haywood_in_1850_census.html)
- [Benjamin_Allen_in_1850_census](./Benjamin_Allen_in_1850_census.html)
- [Benjamin_C._Haywood_in_1850_census](./Benjamin_C._Haywood_in_1850_census.html)
- [Benjamin_Sheldwin_in_1850_census](./Benjamin_Sheldwin_in_1850_census.html)
- [Berthena_Forbs_in_1850_census](./Berthena_Forbs_in_1850_census.html)
- [Betsey_Norton_in_1850_census](./Betsey_Norton_in_1850_census.html)
- [Betsy_Allen_in_1850_census](./Betsy_Allen_in_1850_census.html)
- [Betsy_Ann_Mulliss_in_1850_census](./Betsy_Ann_Mulliss_in_1850_census.html)
- [Betsy_Bevan_in_1850_census](./Betsy_Bevan_in_1850_census.html)
- [Betsy_Lansley_in_1850_census](./Betsy_Lansley_in_1850_census.html)
- [Betsy_McOrman_in_1850_census](./Betsy_McOrman_in_1850_census.html)
- [Betsy_Pond_in_1850_census](./Betsy_Pond_in_1850_census.html)
- [Betsy_Roscoe_in_1850_census](./Betsy_Roscoe_in_1850_census.html)
- [Bridget_Cooners_in_1850_census](./Bridget_Cooners_in_1850_census.html)
- [Buren_Keeler_in_1850_census](./Buren_Keeler_in_1850_census.html)
- [Calvin_Frank_in_1850_census](./Calvin_Frank_in_1850_census.html)
- [Canada_White_in_1850_census](./Canada_White_in_1850_census.html)
- [Caroline_Frank_in_1850_census](./Caroline_Frank_in_1850_census.html)
- [Caroline_Grandy_in_1850_census](./Caroline_Grandy_in_1850_census.html)
- [Caroline_Kingsland_in_1850_census](./Caroline_Kingsland_in_1850_census.html)
- [Caroline_M._Richards_in_1850_census](./Caroline_M._Richards_in_1850_census.html)
- [Cashus_Palmer_in_1850_census](./Cashus_Palmer_in_1850_census.html)
- [Catherine_Allen_in_1850_census](./Catherine_Allen_in_1850_census.html)
- [Catherine_M._Richards_in_1850_census](./Catherine_M._Richards_in_1850_census.html)
- [Cathrine_Curler_in_1850_census](./Cathrine_Curler_in_1850_census.html)
- [Chancy_Boyers_in_1850_census](./Chancy_Boyers_in_1850_census.html)
- [Charity_Holcomb_in_1850_census](./Charity_Holcomb_in_1850_census.html)
- [Charles_A._Perkins_in_1850_census](./Charles_A._Perkins_in_1850_census.html)
- [Charles_Adams_in_1850_census](./Charles_Adams_in_1850_census.html)
- [Charles_Curten_in_1850_census](./Charles_Curten_in_1850_census.html)
- [Charles_E._Shepard_in_1850_census](./Charles_E._Shepard_in_1850_census.html)
- [Charles_Ferris_in_1850_census](./Charles_Ferris_in_1850_census.html)
- [Charles_H._Weisley_in_1850_census](./Charles_H._Weisley_in_1850_census.html)
- [Charles_Hatch_in_1850_census](./Charles_Hatch_in_1850_census.html)
- [Charles_L._Burwell_in_1850_census](./Charles_L._Burwell_in_1850_census.html)
- [Charles_Little_in_1850_census](./Charles_Little_in_1850_census.html)
- [Charles_Macarter_in_1850_census](./Charles_Macarter_in_1850_census.html)
- [Charles_Miny_in_1850_census](./Charles_Miny_in_1850_census.html)
- [Charles_Trudo_Jr_in_1850_census](./Charles_Trudo_Jr_in_1850_census.html)
- [Charles_Trudo_in_1850_census](./Charles_Trudo_in_1850_census.html)
- [Charles_Tull_in_1850_census](./Charles_Tull_in_1850_census.html)
- [Charles_Vriment_in_1850_census](./Charles_Vriment_in_1850_census.html)
- [Charles_W._Burwell_in_1850_census](./Charles_W._Burwell_in_1850_census.html)
- [Charles_W._Sperry_in_1850_census](./Charles_W._Sperry_in_1850_census.html)
- [Charles_Weisley_in_1850_census](./Charles_Weisley_in_1850_census.html)
- [Charlott_Baker_in_1850_census](./Charlott_Baker_in_1850_census.html)
- [Charlott_E._Grandy_in_1850_census](./Charlott_E._Grandy_in_1850_census.html)
- [Charlott_Jackson_in_1850_census](./Charlott_Jackson_in_1850_census.html)
- [Charlott_Smith_in_1850_census](./Charlott_Smith_in_1850_census.html)
- [Charlott_Storms_in_1850_census](./Charlott_Storms_in_1850_census.html)
- [Christopher_Holcomb_in_1850_census](./Christopher_Holcomb_in_1850_census.html)
- [Clara_Spencer_in_1850_census](./Clara_Spencer_in_1850_census.html)
- [Clarassa_L._Walker_in_1850_census](./Clarassa_L._Walker_in_1850_census.html)
- [Clark_Conant_in_1850_census](./Clark_Conant_in_1850_census.html)
- [Cloa_Grandy_in_1850_census](./Cloa_Grandy_in_1850_census.html)
- [Daniel_Brown_in_1850_census](./Daniel_Brown_in_1850_census.html)
- [Daniel_Sturtdifant_in_1850_census](./Daniel_Sturtdifant_in_1850_census.html)
- [David_Adams_in_1850_census](./David_Adams_in_1850_census.html)
- [David_Jackson_in_1850_census](./David_Jackson_in_1850_census.html)
- [David_Raynis_in_1850_census](./David_Raynis_in_1850_census.html)
- [David_Wise_in_1850_census](./David_Wise_in_1850_census.html)
- [Davis_L._Spaulding_in_1850_census](./Davis_L._Spaulding_in_1850_census.html)
- [Delia_Chapin_in_1850_census](./Delia_Chapin_in_1850_census.html)
- [Delia_Kent_in_1850_census](./Delia_Kent_in_1850_census.html)
- [Delia_Kingsland_in_1850_census](./Delia_Kingsland_in_1850_census.html)
- [Dianthony_Gardner_in_1850_census](./Dianthony_Gardner_in_1850_census.html)
- [Edrich_Adams_in_1850_census](./Edrich_Adams_in_1850_census.html)
- [Edrick_Adams_Jr_in_1850_census](./Edrick_Adams_Jr_in_1850_census.html)
- [Edrick_Ferris_in_1850_census](./Edrick_Ferris_in_1850_census.html)
- [Edward_A._Fields_in_1850_census](./Edward_A._Fields_in_1850_census.html)
- [Edward_Lewis_in_1850_census](./Edward_Lewis_in_1850_census.html)
- [Edward_Prince_in_1850_census](./Edward_Prince_in_1850_census.html)
- [Edward_Smith_in_1850_census](./Edward_Smith_in_1850_census.html)
- [Edwin_Bristol_in_1850_census](./Edwin_Bristol_in_1850_census.html)
- [Edwin_Hurlbert_in_1850_census](./Edwin_Hurlbert_in_1850_census.html)
- [Edwin_W._Gardner_in_1850_census](./Edwin_W._Gardner_in_1850_census.html)
- [Elicta_Allen_in_1850_census](./Elicta_Allen_in_1850_census.html)
- [Elijah_Grandy_in_1850_census](./Elijah_Grandy_in_1850_census.html)
- [Eliza_Boyers_in_1850_census](./Eliza_Boyers_in_1850_census.html)
- [Eliza_Lion_in_1850_census](./Eliza_Lion_in_1850_census.html)
- [Eliza_Willard_in_1850_census](./Eliza_Willard_in_1850_census.html)
- [Elizabeth_Allen_in_1850_census](./Elizabeth_Allen_in_1850_census.html)
- [Elizabeth_Collum_in_1850_census](./Elizabeth_Collum_in_1850_census.html)
- [Elizabeth_D._Brown_in_1850_census](./Elizabeth_D._Brown_in_1850_census.html)
- [Elizabeth_Depuy_in_1850_census](./Elizabeth_Depuy_in_1850_census.html)
- [Elizabeth_Grandy_in_1850_census](./Elizabeth_Grandy_in_1850_census.html)
- [Elizabeth_Sheldwin_in_1850_census](./Elizabeth_Sheldwin_in_1850_census.html)
- [Elizabeth_Spaulding_in_1850_census](./Elizabeth_Spaulding_in_1850_census.html)
- [Elizabeth_Spencer_in_1850_census](./Elizabeth_Spencer_in_1850_census.html)
- [Elizabeth_Tenbrooks_in_1850_census](./Elizabeth_Tenbrooks_in_1850_census.html)
- [Elizabeth_Walker_in_1850_census](./Elizabeth_Walker_in_1850_census.html)
- [Ella_Adams_in_1850_census](./Ella_Adams_in_1850_census.html)
- [Ellen_Allen_in_1850_census](./Ellen_Allen_in_1850_census.html)
- [Ellen_Dority_in_1850_census](./Ellen_Dority_in_1850_census.html)
- [Ellen_Tenbrooks_in_1850_census](./Ellen_Tenbrooks_in_1850_census.html)
- [Elmira_Jackson_in_1850_census](./Elmira_Jackson_in_1850_census.html)
- [Elsa_L._Sturtdifant_in_1850_census](./Elsa_L._Sturtdifant_in_1850_census.html)
- [Emela_Rock_in_1850_census](./Emela_Rock_in_1850_census.html)
- [Emerson_Holland_in_1850_census](./Emerson_Holland_in_1850_census.html)
- [Emila_Smith_in_1850_census](./Emila_Smith_in_1850_census.html)
- [Emily_Conant_in_1850_census](./Emily_Conant_in_1850_census.html)
- [Emily_P._Howard_in_1850_census](./Emily_P._Howard_in_1850_census.html)
- [Emily_Trudo_in_1850_census](./Emily_Trudo_in_1850_census.html)
- [Emma_Adams_in_1850_census](./Emma_Adams_in_1850_census.html)
- [Emma_Conant_in_1850_census](./Emma_Conant_in_1850_census.html)
- [Emmerson_Stedman_in_1850_census](./Emmerson_Stedman_in_1850_census.html)
- [Enoch_Kent_in_1850_census](./Enoch_Kent_in_1850_census.html)
- [Ester_Grandy_in_1850_census](./Ester_Grandy_in_1850_census.html)
- [Ester_Tull_in_1850_census](./Ester_Tull_in_1850_census.html)
- [Eunice_Benson_in_1850_census](./Eunice_Benson_in_1850_census.html)
- [Everit_N._Spaulding_in_1850_census](./Everit_N._Spaulding_in_1850_census.html)
- [Faces_Curten_in_1850_census](./Faces_Curten_in_1850_census.html)
- [Fordice_H._Shipard_in_1850_census](./Fordice_H._Shipard_in_1850_census.html)
- [Francis_E._White_in_1850_census](./Francis_E._White_in_1850_census.html)
- [Francis_Ferris_in_1850_census](./Francis_Ferris_in_1850_census.html)
- [Francis_P._Burwell_in_1850_census](./Francis_P._Burwell_in_1850_census.html)
- [Francis_Prince_in_1850_census](./Francis_Prince_in_1850_census.html)
- [Francis_Smith_in_1850_census](./Francis_Smith_in_1850_census.html)
- [Franklin_Richards_in_1850_census](./Franklin_Richards_in_1850_census.html)
- [Fransis_Frank_in_1850_census](./Fransis_Frank_in_1850_census.html)
- [Fransis_Perry_in_1850_census](./Fransis_Perry_in_1850_census.html)
- [Fransis_Prince_in_1850_census](./Fransis_Prince_in_1850_census.html)
- [Fransis_Trudo_in_1850_census](./Fransis_Trudo_in_1850_census.html)
- [Frederick_Curten_in_1850_census](./Frederick_Curten_in_1850_census.html)
- [Friend_A._White_in_1850_census](./Friend_A._White_in_1850_census.html)
- [George_A._White_in_1850_census](./George_A._White_in_1850_census.html)
- [George_Boyers_in_1850_census](./George_Boyers_in_1850_census.html)
- [George_Conant_in_1850_census](./George_Conant_in_1850_census.html)
- [George_Ferris_in_1850_census](./George_Ferris_in_1850_census.html)
- [George_S._Walker_in_1850_census](./George_S._Walker_in_1850_census.html)
- [George_Spencer_in_1850_census](./George_Spencer_in_1850_census.html)
- [George_W._Tilley_in_1850_census](./George_W._Tilley_in_1850_census.html)
- [Gideon_Spencer_in_1850_census](./Gideon_Spencer_in_1850_census.html)
- [Hannah_Janning_in_1850_census](./Hannah_Janning_in_1850_census.html)
- [Hannah_Mitchiel_in_1850_census](./Hannah_Mitchiel_in_1850_census.html)
- [Hannah_Perkins_in_1850_census](./Hannah_Perkins_in_1850_census.html)
- [Hannah_R._Harris_in_1850_census](./Hannah_R._Harris_in_1850_census.html)
- [Hareet_Branch_in_1850_census](./Hareet_Branch_in_1850_census.html)
- [Harret_Capren_in_1850_census](./Harret_Capren_in_1850_census.html)
- [Harret_Spencer_in_1850_census](./Harret_Spencer_in_1850_census.html)
- [Harriet_A._Tappen_in_1850_census](./Harriet_A._Tappen_in_1850_census.html)
- [Harriet_Grandy_in_1850_census](./Harriet_Grandy_in_1850_census.html)
- [Harriet_Smith_in_1850_census](./Harriet_Smith_in_1850_census.html)
- [Harriet_Tull_in_1850_census](./Harriet_Tull_in_1850_census.html)
- [Harry_Benson_in_1850_census](./Harry_Benson_in_1850_census.html)
- [Hellen_Gardner_in_1850_census](./Hellen_Gardner_in_1850_census.html)
- [Henry_Allen_in_1850_census](./Henry_Allen_in_1850_census.html)
- [Henry_Boyers_in_1850_census](./Henry_Boyers_in_1850_census.html)
- [Henry_Brown_in_1850_census](./Henry_Brown_in_1850_census.html)
- [Henry_Gardner_in_1850_census](./Henry_Gardner_in_1850_census.html)
- [Henry_H._Wilder_in_1850_census](./Henry_H._Wilder_in_1850_census.html)
- [Henry_Howard_in_1850_census](./Henry_Howard_in_1850_census.html)
- [Henry_L.P._Warner_in_1850_census](./Henry_L.P._Warner_in_1850_census.html)
- [Henry_Prince_in_1850_census](./Henry_Prince_in_1850_census.html)
- [Henry_Sheldwin_in_1850_census](./Henry_Sheldwin_in_1850_census.html)
- [Henry_Storms_in_1850_census](./Henry_Storms_in_1850_census.html)
- [Henry_Wise_in_1850_census](./Henry_Wise_in_1850_census.html)
- [Hezekiah_Jackson_in_1850_census](./Hezekiah_Jackson_in_1850_census.html)
- [Hiram_Allen_in_1850_census](./Hiram_Allen_in_1850_census.html)
- [Hiram_Kent_in_1850_census](./Hiram_Kent_in_1850_census.html)
- [Hiram_Spaulding_in_1850_census](./Hiram_Spaulding_in_1850_census.html)
- [Hiram_W._Pond_in_1850_census](./Hiram_W._Pond_in_1850_census.html)
- [Hopkins_F._Ganis_in_1850_census](./Hopkins_F._Ganis_in_1850_census.html)
- [Horatio_N._White_in_1850_census](./Horatio_N._White_in_1850_census.html)
- [Huldah_Spaulding_in_1850_census](./Huldah_Spaulding_in_1850_census.html)
- [Ida_Hatch_in_1850_census](./Ida_Hatch_in_1850_census.html)
- [Isaac_Hatch_in_1850_census](./Isaac_Hatch_in_1850_census.html)
- [Isaac_L._Harris_in_1850_census](./Isaac_L._Harris_in_1850_census.html)
- [Isaac_S._Spaulding_in_1850_census](./Isaac_S._Spaulding_in_1850_census.html)
- [Isaac_Spaulding_in_1850_census](./Isaac_Spaulding_in_1850_census.html)
- [Isadore_Adams_in_1850_census](./Isadore_Adams_in_1850_census.html)
- [Jacob_Gardner_in_1850_census](./Jacob_Gardner_in_1850_census.html)
- [Jacob_Spaulding_in_1850_census](./Jacob_Spaulding_in_1850_census.html)
- [Jacob_V._Curler_in_1850_census](./Jacob_V._Curler_in_1850_census.html)
- [James_Capren_in_1850_census](./James_Capren_in_1850_census.html)
- [James_E._Gardner_in_1850_census](./James_E._Gardner_in_1850_census.html)
- [James_Hall_in_1850_census](./James_Hall_in_1850_census.html)
- [James_Kitchen_in_1850_census](./James_Kitchen_in_1850_census.html)
- [James_McOrman_Jr_in_1850_census](./James_McOrman_Jr_in_1850_census.html)
- [James_McOrman_in_1850_census](./James_McOrman_in_1850_census.html)
- [James_Newgent_in_1850_census](./James_Newgent_in_1850_census.html)
- [James_Sage_in_1850_census](./James_Sage_in_1850_census.html)
- [James_Shepard_in_1850_census](./James_Shepard_in_1850_census.html)
- [James_Tenbrooks_in_1850_census](./James_Tenbrooks_in_1850_census.html)
- [James_W._Shepard_in_1850_census](./James_W._Shepard_in_1850_census.html)
- [Jamiah_Milina_in_1850_census](./Jamiah_Milina_in_1850_census.html)
- [Jane_Alden_in_1850_census](./Jane_Alden_in_1850_census.html)
- [Jane_Ann_Conant_in_1850_census](./Jane_Ann_Conant_in_1850_census.html)
- [Jane_Ann_Tenbrooks_in_1850_census](./Jane_Ann_Tenbrooks_in_1850_census.html)
- [Jane_Bristol_in_1850_census](./Jane_Bristol_in_1850_census.html)
- [Jane_Eno_in_1850_census](./Jane_Eno_in_1850_census.html)
- [Jane_Richards_in_1850_census](./Jane_Richards_in_1850_census.html)
- [Jane_Tilley_in_1850_census](./Jane_Tilley_in_1850_census.html)
- [Jefferson_Convers_in_1850_census](./Jefferson_Convers_in_1850_census.html)
- [Jesse_G._Convers_in_1850_census](./Jesse_G._Convers_in_1850_census.html)
- [Jesse_L._Grandy_in_1850_census](./Jesse_L._Grandy_in_1850_census.html)
- [Jessie_Maryet_Holland_in_1850_census](./Jessie_Maryet_Holland_in_1850_census.html)
- [Joannah_Spencer_in_1850_census](./Joannah_Spencer_in_1850_census.html)
- [Joel_W._Grandy_in_1850_census](./Joel_W._Grandy_in_1850_census.html)
- [Johannah_Ryne_in_1850_census](./Johannah_Ryne_in_1850_census.html)
- [John_B._Spaulding_in_1850_census](./John_B._Spaulding_in_1850_census.html)
- [John_Barns_in_1850_census](./John_Barns_in_1850_census.html)
- [John_Davis_in_1850_census](./John_Davis_in_1850_census.html)
- [John_Delana_in_1850_census](./John_Delana_in_1850_census.html)
- [John_F._Adams_in_1850_census](./John_F._Adams_in_1850_census.html)
- [John_G._Smith_in_1850_census](./John_G._Smith_in_1850_census.html)
- [John_Ganater_in_1850_census](./John_Ganater_in_1850_census.html)
- [John_Igo_in_1850_census](./John_Igo_in_1850_census.html)
- [John_McClain_in_1850_census](./John_McClain_in_1850_census.html)
- [John_McDaniels_in_1850_census](./John_McDaniels_in_1850_census.html)
- [John_McOrman_in_1850_census](./John_McOrman_in_1850_census.html)
- [John_Perry_in_1850_census](./John_Perry_in_1850_census.html)
- [John_Porter_in_1850_census](./John_Porter_in_1850_census.html)
- [John_Prince_in_1850_census](./John_Prince_in_1850_census.html)
- [John_R._Convers_in_1850_census](./John_R._Convers_in_1850_census.html)
- [John_Sheldwin_in_1850_census](./John_Sheldwin_in_1850_census.html)
- [John_Spaulding_in_1850_census](./John_Spaulding_in_1850_census.html)
- [John_W._Batcheler_in_1850_census](./John_W._Batcheler_in_1850_census.html)
- [John_W._Kent_in_1850_census](./John_W._Kent_in_1850_census.html)
- [John_W._Sheldwin_in_1850_census](./John_W._Sheldwin_in_1850_census.html)
- [Jonathan_Spencer_in_1850_census](./Jonathan_Spencer_in_1850_census.html)
- [Joseph_A._Vriment_in_1850_census](./Joseph_A._Vriment_in_1850_census.html)
- [Joseph_Boyers_in_1850_census](./Joseph_Boyers_in_1850_census.html)
- [Joseph_Carter_in_1850_census](./Joseph_Carter_in_1850_census.html)
- [Joseph_Collum_Jr._in_1850_census](./Joseph_Collum_Jr._in_1850_census.html)
- [Joseph_Collum_in_1850_census](./Joseph_Collum_in_1850_census.html)
- [Joseph_Daniels_in_1850_census](./Joseph_Daniels_in_1850_census.html)
- [Joseph_Depuy_in_1850_census](./Joseph_Depuy_in_1850_census.html)
- [Joseph_Fields_in_1850_census](./Joseph_Fields_in_1850_census.html)
- [Joseph_Gorke_in_1850_census](./Joseph_Gorke_in_1850_census.html)
- [Joseph_Haywood_in_1850_census](./Joseph_Haywood_in_1850_census.html)
- [Joseph_Holcomb_in_1850_census](./Joseph_Holcomb_in_1850_census.html)
- [Joseph_Janning_in_1850_census](./Joseph_Janning_in_1850_census.html)
- [Joseph_Little_Jr_in_1850_census](./Joseph_Little_Jr_in_1850_census.html)
- [Joseph_Little_in_1850_census](./Joseph_Little_in_1850_census.html)
- [Joseph_Perry_Jr_in_1850_census](./Joseph_Perry_Jr_in_1850_census.html)
- [Joseph_Perry_in_1850_census](./Joseph_Perry_in_1850_census.html)
- [Joseph_Rock_in_1850_census](./Joseph_Rock_in_1850_census.html)
- [Joseph_Trudo_in_1850_census](./Joseph_Trudo_in_1850_census.html)
- [Joseph_Vriment_in_1850_census](./Joseph_Vriment_in_1850_census.html)
- [Joseph_Wise_in_1850_census](./Joseph_Wise_in_1850_census.html)
- [Josephine_Haywood_in_1850_census](./Josephine_Haywood_in_1850_census.html)
- [Josephine_Lansley_in_1850_census](./Josephine_Lansley_in_1850_census.html)
- [Joshua_F._Fields_in_1850_census](./Joshua_F._Fields_in_1850_census.html)
- [Josiah_S._Tappen_in_1850_census](./Josiah_S._Tappen_in_1850_census.html)
- [Julia_Ann_Allen_in_1850_census](./Julia_Ann_Allen_in_1850_census.html)
- [Julia_Ann_Collum_in_1850_census](./Julia_Ann_Collum_in_1850_census.html)
- [Julia_Orkins_in_1850_census](./Julia_Orkins_in_1850_census.html)
- [Julia_Prince_in_1850_census](./Julia_Prince_in_1850_census.html)
- [Julia_Raynor_in_1850_census](./Julia_Raynor_in_1850_census.html)
- [Julia_Sturtdifant_in_1850_census](./Julia_Sturtdifant_in_1850_census.html)
- [Julia_Wise_in_1850_census](./Julia_Wise_in_1850_census.html)
- [Julian_P._Spaulding_in_1850_census](./Julian_P._Spaulding_in_1850_census.html)
- [Juniett_Peck_in_1850_census](./Juniett_Peck_in_1850_census.html)
- [Katurah_Grandey_in_1850_census](./Katurah_Grandey_in_1850_census.html)
- [Leorand_W._Brown_in_1850_census](./Leorand_W._Brown_in_1850_census.html)
- [Lewis_Daniels_Jr_in_1850_census](./Lewis_Daniels_Jr_in_1850_census.html)
- [Lewis_Daniels_in_1850_census](./Lewis_Daniels_in_1850_census.html)
- [Lewis_Raymond_in_1850_census](./Lewis_Raymond_in_1850_census.html)
- [Loisa_Chapman_in_1850_census](./Loisa_Chapman_in_1850_census.html)
- [Loisa_Gardner_in_1850_census](./Loisa_Gardner_in_1850_census.html)
- [Loisy_Mulliss_in_1850_census](./Loisy_Mulliss_in_1850_census.html)
- [Loiza_Allen_in_1850_census](./Loiza_Allen_in_1850_census.html)
- [Loiza_Curler_in_1850_census](./Loiza_Curler_in_1850_census.html)
- [Loiza_Dudley_in_1850_census](./Loiza_Dudley_in_1850_census.html)
- [Loiza_Pond_in_1850_census](./Loiza_Pond_in_1850_census.html)
- [Loiza_Trudo_in_1850_census](./Loiza_Trudo_in_1850_census.html)
- [Loiza_Weisley_in_1850_census](./Loiza_Weisley_in_1850_census.html)
- [Loiza_Wise_in_1850_census](./Loiza_Wise_in_1850_census.html)
- [Lorane_Smith_in_1850_census](./Lorane_Smith_in_1850_census.html)
- [Louisa_Jackson_in_1850_census](./Louisa_Jackson_in_1850_census.html)
- [Lovinna_Stowell_in_1850_census](./Lovinna_Stowell_in_1850_census.html)
- [Loyal_Kent_in_1850_census](./Loyal_Kent_in_1850_census.html)
- [Lucinda_A._Grandy_in_1850_census](./Lucinda_A._Grandy_in_1850_census.html)
- [Lucinda_Fields_in_1850_census](./Lucinda_Fields_in_1850_census.html)
- [Lucinda_Stedman_in_1850_census](./Lucinda_Stedman_in_1850_census.html)
- [Lucinda_Warner_in_1850_census](./Lucinda_Warner_in_1850_census.html)
- [Lucy_Critenden_in_1850_census](./Lucy_Critenden_in_1850_census.html)
- [Lucy_Kent_in_1850_census](./Lucy_Kent_in_1850_census.html)
- [Luretia_Conant_in_1850_census](./Luretia_Conant_in_1850_census.html)
- [Lydia_Bristol_in_1850_census](./Lydia_Bristol_in_1850_census.html)
- [Lyman_J._Conant_in_1850_census](./Lyman_J._Conant_in_1850_census.html)
- [Malankton_Ferris_in_1850_census](./Malankton_Ferris_in_1850_census.html)
- [Mariah_Conant_in_1850_census](./Mariah_Conant_in_1850_census.html)
- [Mariah_L._Grandy_in_1850_census](./Mariah_L._Grandy_in_1850_census.html)
- [Mariah_Prince_in_1850_census](./Mariah_Prince_in_1850_census.html)
- [Marial_Kingsland_in_1850_census](./Marial_Kingsland_in_1850_census.html)
- [Mariam_E._Wilder_in_1850_census](./Mariam_E._Wilder_in_1850_census.html)
- [Marion_H._Adams_in_1850_census](./Marion_H._Adams_in_1850_census.html)
- [Martha_E._Burwell_in_1850_census](./Martha_E._Burwell_in_1850_census.html)
- [Martha_Ferris_in_1850_census](./Martha_Ferris_in_1850_census.html)
- [Martha_Wise_in_1850_census](./Martha_Wise_in_1850_census.html)
- [Marthy_Kingsland_in_1850_census](./Marthy_Kingsland_in_1850_census.html)
- [Martin_Hayt_in_1850_census](./Martin_Hayt_in_1850_census.html)
- [Mary_A._Ganis_in_1850_census](./Mary_A._Ganis_in_1850_census.html)
- [Mary_Ann_Fletcher_in_1850_census](./Mary_Ann_Fletcher_in_1850_census.html)
- [Mary_Ann_Heath_in_1850_census](./Mary_Ann_Heath_in_1850_census.html)
- [Mary_Ann_Spaulding_in_1850_census](./Mary_Ann_Spaulding_in_1850_census.html)
- [Mary_Ann_Tenbrooks_in_1850_census](./Mary_Ann_Tenbrooks_in_1850_census.html)
- [Mary_Billon_in_1850_census](./Mary_Billon_in_1850_census.html)
- [Mary_Boyers_in_1850_census](./Mary_Boyers_in_1850_census.html)
- [Mary_Buvan_in_1850_census](./Mary_Buvan_in_1850_census.html)
- [Mary_Daniels_in_1850_census](./Mary_Daniels_in_1850_census.html)
- [Mary_Dreyic_in_1850_census](./Mary_Dreyic_in_1850_census.html)
- [Mary_E._Spaulding_in_1850_census](./Mary_E._Spaulding_in_1850_census.html)
- [Mary_H._Gardner_in_1850_census](./Mary_H._Gardner_in_1850_census.html)
- [Mary_H._McOrman_in_1850_census](./Mary_H._McOrman_in_1850_census.html)
- [Mary_Holland_in_1850_census](./Mary_Holland_in_1850_census.html)
- [Mary_Little_in_1850_census](./Mary_Little_in_1850_census.html)
- [Mary_Maramnack_in_1850_census](./Mary_Maramnack_in_1850_census.html)
- [Mary_Perry_in_1850_census](./Mary_Perry_in_1850_census.html)
- [Mary_Prindle_in_1850_census](./Mary_Prindle_in_1850_census.html)
- [Mary_Raymo_in_1850_census](./Mary_Raymo_in_1850_census.html)
- [Mary_Sheldwin_in_1850_census](./Mary_Sheldwin_in_1850_census.html)
- [Mary_Tenbrooks_in_1850_census](./Mary_Tenbrooks_in_1850_census.html)
- [Mary_Weisley_in_1850_census](./Mary_Weisley_in_1850_census.html)
- [Maryett_Barns_in_1850_census](./Maryett_Barns_in_1850_census.html)
- [Mathuell_F._Ganis_in_1850_census](./Mathuell_F._Ganis_in_1850_census.html)
- [Matilda_Allen_in_1850_census](./Matilda_Allen_in_1850_census.html)
- [Matilda_Spencer_in_1850_census](./Matilda_Spencer_in_1850_census.html)
- [Matilda_Welles_in_1850_census](./Matilda_Welles_in_1850_census.html)
- [Mercia_Tupper_in_1850_census](./Mercia_Tupper_in_1850_census.html)
- [Mikiel_Billon_in_1850_census](./Mikiel_Billon_in_1850_census.html)
- [Mikiel_Dwyer_in_1850_census](./Mikiel_Dwyer_in_1850_census.html)
- [Milo_S._Parmee_in_1850_census](./Milo_S._Parmee_in_1850_census.html)
- [Miner_Mitchiel_in_1850_census](./Miner_Mitchiel_in_1850_census.html)
- [Mirnerva_Silver_in_1850_census](./Mirnerva_Silver_in_1850_census.html)
- [Miron_Bristol_in_1850_census](./Miron_Bristol_in_1850_census.html)
- [Mitchel_Daniels_in_1850_census](./Mitchel_Daniels_in_1850_census.html)
- [Morris_Smith_in_1850_census](./Morris_Smith_in_1850_census.html)
- [Moses_Sheldwin_in_1850_census](./Moses_Sheldwin_in_1850_census.html)
- [Munson_P._Curtis_in_1850_census](./Munson_P._Curtis_in_1850_census.html)
- [Murrey_Adams_in_1850_census](./Murrey_Adams_in_1850_census.html)
- [Myron_Batchelder_in_1850_census](./Myron_Batchelder_in_1850_census.html)
- [Nancy_Orkins_in_1850_census](./Nancy_Orkins_in_1850_census.html)
- [Nancy_Sheldwin_in_1850_census](./Nancy_Sheldwin_in_1850_census.html)
- [Naris_Curtis_in_1850_census](./Naris_Curtis_in_1850_census.html)
- [Nathan_Spaulding_in_1850_census](./Nathan_Spaulding_in_1850_census.html)
- [Nelson_Richards_in_1850_census](./Nelson_Richards_in_1850_census.html)
- [Noah_Bristol_in_1850_census](./Noah_Bristol_in_1850_census.html)
- [Norman_Grandy_in_1850_census](./Norman_Grandy_in_1850_census.html)
- [Norman_Lansley_in_1850_census](./Norman_Lansley_in_1850_census.html)
- [Norman_W._Bristol_in_1850_census](./Norman_W._Bristol_in_1850_census.html)
- [Obediah_Allen_in_1850_census](./Obediah_Allen_in_1850_census.html)
- [Octava_Vriment_in_1850_census](./Octava_Vriment_in_1850_census.html)
- [Ogden_Tenbrooks_in_1850_census](./Ogden_Tenbrooks_in_1850_census.html)
- [Olive_M._Spaulding_in_1850_census](./Olive_M._Spaulding_in_1850_census.html)
- [Olive_Spaulding_in_1850_census](./Olive_Spaulding_in_1850_census.html)
- [Olud_Perry_in_1850_census](./Olud_Perry_in_1850_census.html)
- [Orpha_Holcomb_in_1850_census](./Orpha_Holcomb_in_1850_census.html)
- [Patience_Allen_in_1850_census](./Patience_Allen_in_1850_census.html)
- [Patience_Keeler_in_1850_census](./Patience_Keeler_in_1850_census.html)
- [Patrick_Newgent_in_1850_census](./Patrick_Newgent_in_1850_census.html)
- [Patrick_Ryan_in_1850_census](./Patrick_Ryan_in_1850_census.html)
- [Patrick_Ryne_in_1850_census](./Patrick_Ryne_in_1850_census.html)
- [Pered_Holcomb_in_1850_census](./Pered_Holcomb_in_1850_census.html)
- [Perin_Bristol_in_1850_census](./Perin_Bristol_in_1850_census.html)
- [Peter_Alden_Jr_in_1850_census](./Peter_Alden_Jr_in_1850_census.html)
- [Peter_Larabo_in_1850_census](./Peter_Larabo_in_1850_census.html)
- [Peter_Mack_in_1850_census](./Peter_Mack_in_1850_census.html)
- [Peter_Trudo_in_1850_census](./Peter_Trudo_in_1850_census.html)
- [Phebe_Ann_Tilley_in_1850_census](./Phebe_Ann_Tilley_in_1850_census.html)
- [Phebe_Hatch_in_1850_census](./Phebe_Hatch_in_1850_census.html)
- [Phebe_J._Stedman_in_1850_census](./Phebe_J._Stedman_in_1850_census.html)
- [Phebe_Spaulding_in_1850_census](./Phebe_Spaulding_in_1850_census.html)
- [Phebe_W._Spaulding_in_1850_census](./Phebe_W._Spaulding_in_1850_census.html)
- [Phila_Shepard_in_1850_census](./Phila_Shepard_in_1850_census.html)
- [Philana_Vriment_in_1850_census](./Philana_Vriment_in_1850_census.html)
- [Philena_Sheldwin_in_1850_census](./Philena_Sheldwin_in_1850_census.html)
- [Philina_Kent_in_1850_census](./Philina_Kent_in_1850_census.html)
- [Philinda_Wise_in_1850_census](./Philinda_Wise_in_1850_census.html)
- [Phillipp_Lansing_in_1850_census](./Phillipp_Lansing_in_1850_census.html)
- [Philo_Bristol_in_1850_census](./Philo_Bristol_in_1850_census.html)
- [Phineas_Holcomb_in_1850_census](./Phineas_Holcomb_in_1850_census.html)
- [Pilana_Pond_in_1850_census](./Pilana_Pond_in_1850_census.html)
- [Polly_Ann_Spaulding_in_1850_census](./Polly_Ann_Spaulding_in_1850_census.html)
- [Polly_Benson_in_1850_census](./Polly_Benson_in_1850_census.html)
- [Polly_Brown_in_1850_census](./Polly_Brown_in_1850_census.html)
- [Polly_Grandy_in_1850_census](./Polly_Grandy_in_1850_census.html)
- [Polly_R._Grandy_in_1850_census](./Polly_R._Grandy_in_1850_census.html)
- [Prince_Perry_in_1850_census](./Prince_Perry_in_1850_census.html)
- [Prosper_Eno_in_1850_census](./Prosper_Eno_in_1850_census.html)
- [Prudance_Bristol_in_1850_census](./Prudance_Bristol_in_1850_census.html)
- [Rachael_Davis_in_1850_census](./Rachael_Davis_in_1850_census.html)
- [Rachael_Igo_in_1850_census](./Rachael_Igo_in_1850_census.html)
- [Rachael_Kent_in_1850_census](./Rachael_Kent_in_1850_census.html)
- [Rebecca_Spaulding_in_1850_census](./Rebecca_Spaulding_in_1850_census.html)
- [Rebecca_Sperry_in_1850_census](./Rebecca_Sperry_in_1850_census.html)
- [Rhoda_Stagg_in_1850_census](./Rhoda_Stagg_in_1850_census.html)
- [Robert_Paelmer_in_1850_census](./Robert_Paelmer_in_1850_census.html)
- [Rollen_P._Tappen_in_1850_census](./Rollen_P._Tappen_in_1850_census.html)
- [Rosatha_Fields_in_1850_census](./Rosatha_Fields_in_1850_census.html)
- [Rose_Daniels_in_1850_census](./Rose_Daniels_in_1850_census.html)
- [Roselia_Prince_in_1850_census](./Roselia_Prince_in_1850_census.html)
- [Rosina_Burwell_in_1850_census](./Rosina_Burwell_in_1850_census.html)
- [Roswell_D._Hopkins_in_1850_census](./Roswell_D._Hopkins_in_1850_census.html)
- [Roswell_J._Hopkins_in_1850_census](./Roswell_J._Hopkins_in_1850_census.html)
- [Rowland_Curten_in_1850_census](./Rowland_Curten_in_1850_census.html)
- [Roxana_Batcheler_in_1850_census](./Roxana_Batcheler_in_1850_census.html)
- [Royal_Kent_in_1850_census](./Royal_Kent_in_1850_census.html)
- [Ruba_Spaulding_in_1850_census](./Ruba_Spaulding_in_1850_census.html)
- [Rufus_E._Orkins_in_1850_census](./Rufus_E._Orkins_in_1850_census.html)
- [Rupee_Norton_in_1850_census](./Rupee_Norton_in_1850_census.html)
- [Russell_T._Bristol_in_1850_census](./Russell_T._Bristol_in_1850_census.html)
- [Ruth_Carter_in_1850_census](./Ruth_Carter_in_1850_census.html)
- [Ruth_Ferris_in_1850_census](./Ruth_Ferris_in_1850_census.html)
- [Sally_Beevan_in_1850_census](./Sally_Beevan_in_1850_census.html)
- [Sally_Chapin_in_1850_census](./Sally_Chapin_in_1850_census.html)
- [Sally_Hobbs_in_1850_census](./Sally_Hobbs_in_1850_census.html)
- [Sally_Jackson_in_1850_census](./Sally_Jackson_in_1850_census.html)
- [Sally_M._Curler_in_1850_census](./Sally_M._Curler_in_1850_census.html)
- [Sally_Monson_in_1850_census](./Sally_Monson_in_1850_census.html)
- [Salmon_W._Holland_in_1850_census](./Salmon_W._Holland_in_1850_census.html)
- [Samantha_Conant_in_1850_census](./Samantha_Conant_in_1850_census.html)
- [Samuel_Boyers_in_1850_census](./Samuel_Boyers_in_1850_census.html)
- [Samuel_F._Ganis_in_1850_census](./Samuel_F._Ganis_in_1850_census.html)
- [Samuel_Gardner_in_1850_census](./Samuel_Gardner_in_1850_census.html)
- [Samuel_Mitchiel_in_1850_census](./Samuel_Mitchiel_in_1850_census.html)
- [Samuel_Richards_in_1850_census](./Samuel_Richards_in_1850_census.html)
- [Samuel_Shepard_in_1850_census](./Samuel_Shepard_in_1850_census.html)
- [Sarah_Allen_in_1850_census](./Sarah_Allen_in_1850_census.html)
- [Sarah_Ann_Milina_in_1850_census](./Sarah_Ann_Milina_in_1850_census.html)
- [Sarah_Convers_in_1850_census](./Sarah_Convers_in_1850_census.html)
- [Sarah_F._Hopkins_in_1850_census](./Sarah_F._Hopkins_in_1850_census.html)
- [Sarah_Foster_in_1850_census](./Sarah_Foster_in_1850_census.html)
- [Sarah_Hatch_in_1850_census](./Sarah_Hatch_in_1850_census.html)
- [Sarah_Jane_Shepard_in_1850_census](./Sarah_Jane_Shepard_in_1850_census.html)
- [Sarah_P._Tull_in_1850_census](./Sarah_P._Tull_in_1850_census.html)
- [Sarah_Smith_in_1850_census](./Sarah_Smith_in_1850_census.html)
- [Sarah_Spencer_in_1850_census](./Sarah_Spencer_in_1850_census.html)
- [Sarah_Storms_in_1850_census](./Sarah_Storms_in_1850_census.html)
- [Seloma_Valerin_in_1850_census](./Seloma_Valerin_in_1850_census.html)
- [Semantha_Ferris_in_1850_census](./Semantha_Ferris_in_1850_census.html)
- [Semantha_Tappen_in_1850_census](./Semantha_Tappen_in_1850_census.html)
- [Seymour_Depuy__Jr._in_1850_census](./Seymour_Depuy__Jr._in_1850_census.html)
- [Seymour_Depuy_in_1850_census](./Seymour_Depuy_in_1850_census.html)
- [Shefail_Tappen_in_1850_census](./Shefail_Tappen_in_1850_census.html)
- [Silad_Tappen_in_1850_census](./Silad_Tappen_in_1850_census.html)
- [Silas_Allen_in_1850_census](./Silas_Allen_in_1850_census.html)
- [Silas_Pond_in_1850_census](./Silas_Pond_in_1850_census.html)
- [Silas_Tupper_in_1850_census](./Silas_Tupper_in_1850_census.html)
- [Silas_Weisley_in_1850_census](./Silas_Weisley_in_1850_census.html)
- [Solomon_Allen_in_1850_census](./Solomon_Allen_in_1850_census.html)
- [Sophia_Boyers_in_1850_census](./Sophia_Boyers_in_1850_census.html)
- [Sophia_Howard_in_1850_census](./Sophia_Howard_in_1850_census.html)
- [Stephen_Holland_in_1850_census](./Stephen_Holland_in_1850_census.html)
- [Stephen_Mulliss_in_1850_census](./Stephen_Mulliss_in_1850_census.html)
- [Stephen_Roscoe_in_1850_census](./Stephen_Roscoe_in_1850_census.html)
- [Sumon_B._Grandy_in_1850_census](./Sumon_B._Grandy_in_1850_census.html)
- [Susan_Mulliss_in_1850_census](./Susan_Mulliss_in_1850_census.html)
- [Suson_B._Spaulding_in_1850_census](./Suson_B._Spaulding_in_1850_census.html)
- [Symon_Shepard_in_1850_census](./Symon_Shepard_in_1850_census.html)
- [Syntha_Adams_in_1850_census](./Syntha_Adams_in_1850_census.html)
- [Syntha_Batcheler_in_1850_census](./Syntha_Batcheler_in_1850_census.html)
- [Syntha_Kent_in_1850_census](./Syntha_Kent_in_1850_census.html)
- [Syrena_White_in_1850_census](./Syrena_White_in_1850_census.html)
- [Taymor_Shepard_in_1850_census](./Taymor_Shepard_in_1850_census.html)
- [Thomas_Buvan_in_1850_census](./Thomas_Buvan_in_1850_census.html)
- [Thomas_Gardner_in_1850_census](./Thomas_Gardner_in_1850_census.html)
- [Thomas_Perkins_Jr_in_1850_census](./Thomas_Perkins_Jr_in_1850_census.html)
- [Thomas_Perkins_in_1850_census](./Thomas_Perkins_in_1850_census.html)
- [Thomas_Ryne_in_1850_census](./Thomas_Ryne_in_1850_census.html)
- [Truman_Gardner_in_1850_census](./Truman_Gardner_in_1850_census.html)
- [Truman_Grandy_in_1850_census](./Truman_Grandy_in_1850_census.html)
- [Ugene_Storms_in_1850_census](./Ugene_Storms_in_1850_census.html)
- [Urnsted_Keeler_in_1850_census](./Urnsted_Keeler_in_1850_census.html)
- [Viola_Chapin_in_1850_census](./Viola_Chapin_in_1850_census.html)
- [Viola_E._Fields_in_1850_census](./Viola_E._Fields_in_1850_census.html)
- [Wallace_Collum_in_1850_census](./Wallace_Collum_in_1850_census.html)
- [Wallace_Norton_in_1850_census](./Wallace_Norton_in_1850_census.html)
- [Walter_Tilley_in_1850_census](./Walter_Tilley_in_1850_census.html)
- [Warren_Hatch_in_1850_census](./Warren_Hatch_in_1850_census.html)
- [Warren_S._Hatch_in_1850_census](./Warren_S._Hatch_in_1850_census.html)
- [Wasburn_Brown_in_1850_census](./Wasburn_Brown_in_1850_census.html)
- [Welthy_Curtis_in_1850_census](./Welthy_Curtis_in_1850_census.html)
- [William_Boyers_in_1850_census](./William_Boyers_in_1850_census.html)
- [William_Bristol_in_1850_census](./William_Bristol_in_1850_census.html)
- [William_Conant_in_1850_census](./William_Conant_in_1850_census.html)
- [William_E._White_in_1850_census](./William_E._White_in_1850_census.html)
- [William_Foster_Jr_in_1850_census](./William_Foster_Jr_in_1850_census.html)
- [William_Foster_in_1850_census](./William_Foster_in_1850_census.html)
- [William_Hobbs_in_1850_census](./William_Hobbs_in_1850_census.html)
- [William_Holland_in_1850_census](./William_Holland_in_1850_census.html)
- [William_Kingsland_in_1850_census](./William_Kingsland_in_1850_census.html)
- [William_M._Grandy_in_1850_census](./William_M._Grandy_in_1850_census.html)
- [William_Newgent_in_1850_census](./William_Newgent_in_1850_census.html)
- [William_Prince_in_1850_census](./William_Prince_in_1850_census.html)
- [William_Richards_in_1850_census](./William_Richards_in_1850_census.html)
- [William_S._Allen_in_1850_census](./William_S._Allen_in_1850_census.html)
- [William_Shepard_in_1850_census](./William_Shepard_in_1850_census.html)
- [William_Smith_in_1850_census](./William_Smith_in_1850_census.html)
- [William_Talbert_in_1850_census](./William_Talbert_in_1850_census.html)
- [William_Tenbrooks_in_1850_census](./William_Tenbrooks_in_1850_census.html)
- [William_Trudo_in_1850_census](./William_Trudo_in_1850_census.html)
- [William_Tull_in_1850_census](./William_Tull_in_1850_census.html)
