
refersto::[Anna Serena White](./../../people/Merrill-line/White-line/Anna_Serena_White.html)
refersto::[William E. White](./../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Ellen Grandey](./../../people/Merrill-line/Grandey-line/Ellen_Grandey.html)

## Source

Vermont State Archives and Records Administration; Montpelier, Vermont, USA; User Box Number: _PR-01922_; Roll Number: _S-30815_; Archive Number: _M-2050475_

#### Source Information

Ancestry.com. _Vermont, U.S., Death Records, 1909-2008_ [database on-line]. Provo, UT, USA: Ancestry.com Operations, Inc., 2010.

Original data:

- Vermont. Vermont Death Records, 1909-2003. Vermont State Archives and Records Administration, Montpelier, Vermont. 
- Vermont. Vermont Death Records, 2004-2008. Vital Records Office, Vermont Department of Health, Burlington, Vermont.


## Transcription

Full Name of Deceased Anna White Merrill

Usual Reisdence 100 S. Union St., Burlington

Color White Age 43 Yrs. 2 Mos. 18 Days Married

Occupation Housewife

Birthplace Vt.

Father's Name W.E. White

Father's Birthplace Vt.

Mother's Maiden Name Ellen Grandy

Mother's Birthplace Vt.

Date of Death 1913 Month May Day 3

Disease Causing Death Angina Pectoris 80

Contributing Disease Arterio-sclerosis

Medical Attendant J.H. Dodds

Town Burlington M.C. Grandy Town Clerk

