
refersto::[Cassie Green](./../../people/Gattis-line/Green-line/Cassie_Green.html)
refersto::[James Green](./../../people/Gattis-line/Green-line/James_Green.html)
refersto::[Elvira Ann Williams](./../../people/Gattis-line/Green-line/Williams-line/Elvira_Ann_Williams.html)
refersto::[Edith Gattis](./../../people/Gattis-line/Edith_Gattis.html)
## Citation

Tennessee State Library and Archives; Nashville, Tennessee; Tennessee Death Records, 1908-1958; Roll Number: 8

###### Description

Year: _1946_

###### Source Information

Ancestry.com. _Tennessee, U.S., Death Records, 1908-1965_ . Provo, UT, USA: Ancestry.com Operations, Inc., 2011. 
Original data:Tennessee Death Records, 1908-1965. Nashville, Tennessee: Tennessee State Library and Archives. Tennessee City Death Records Nashville, Knoxville, Chattanooga, Memphis 1848-1907. Nashville, Tennessee: Tennessee State Library and Archives

## Transcription

**1**. Full Name Mrs. Cassie Green Gattis **2**. Date of Death Feb. 12 1946

**3**. Place of Death: 

A) County Rutherford Civil District 13

B) City or town Murfreesboro

**4** Usual Residence A) State Tenn

B) County Rutherford Civil District 13

C) City or town Murfreesboro

D) Stree no. S. Maple St.

**5** race or color W **6** Six F **7** Widowed

**8** Age 75 years 3 months 11 kdays

**9** Date of Birth: Month Nov Day 1 Year 1873

**10** Place of birth: city or county Bedford State or Country Tenn.

**13** Usual Occupation Housekeeper

**15** Father Full Name James G. Green

Birthplace City or County Bedford State or Country Tenn.

**16** Mother Maiden Name Ann Williams

Birthplace City or County Bedford Sttate or Country Tenn.

**17** Informant Mrs. W.M. Gilmore

**18** Burial, removal or cremation Burial Date Feb. 14 1946

Cemetery Evergreen Place M'boro

**19**. Undertaker Woodfin & Moore

Address Murfreesboro By H.C. Moore, Jr.

**20**. Medical Certifcation. I hereby certify that I attended the deceased from 2-5-1946 to 2-12-1946 and that I last saw her alive on 1-12-1946 and that death occurred on the deate stated

Immediate cause of death: myocarditis

Signature J.R. Gott, M.D.

Address Murfreesboro Date signed 10-8-46

Date filed 10-11 1946 Mrs. ??? Registrar

## Notes

Stamped "DELAYED"

Stamped "Received Oct. 14 1946"