refersto::[Frances Hix](./../../people/Randolph_county_lines/Hicks/Frances_Hix.html)
refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[William J. Hicks](./../../people/Randolph_county_lines/Hicks/William_J._Hicks.html)
refersto::[Jane Lassiter](./../../people/Randolph_county_lines/Lassiter/Jane_Lassiter.html)

## Source

North Carolina State Archives; Raleigh, North Carolina; _North Carolina Death Certificates_

#### Source Information

Ancestry.com. _North Carolina, U.S., Death Certificates, 1909-1976_ database on-line. Lehi, UT, USA: Ancestry.com Operations Inc, 2007.

Original data: North Carolina State Board of Health, Bureau of Vital Statistics. _North Carolina Death Certificates_. Microfilm S.123. Rolls 19-242, 280, 313-682, 1040-1297. North Carolina State Archives, Raleigh, North Carolina.

## Notes

County Randolph
State NC
Register No 31
Township Asheboro
City Asheboro
Full name Fannie Rush

color or race Whte
married

wife of Harris Rush

date of birth 1852
age 73 year 4 months 4 days

occupation house wife

birth place NC

Name of father William Hix
birthplace of father NC

Maiden name of mother Jane Rush

Informant Harris Rush, Asheboro, NC


Death of death 11/13 1925
Cause of death was descried as "nephritis & high blood pression" with a duration of 2 years
