

## Source

## Transcription

**1 Place of death**

County Guilford Registration District No. (41-900 Certificate No. 288

Township High Point

City High Point, N.C. No. Burrus Memorial Hospital

**2 Full Name** Mrs. Juanita Rush Lassiter

Reisidence: No. Academy

**3 Sex** female

**4 Color or race** White

**5 Single, Married, Widowed, or Divorced** Married

**5a HUSBAND of WIFE of** Thomas Lassiter

**6 Date of birth** 1880

**7 Age** Years 57

**Occupation**

**8 Trade, profession or particular kind of work done** Housework

**9 Industry or business in which wor was done** own home


**12 Birthplace** North Carolina

**Father**

**13 Name** Harris Rush

**14 Birthplace** North Carolina

**Mother**

**15 Maiden Name** Fannie Hix

**16 Birthplace** North Carolina

**17 Informant** Thomas Lassiter, Asheboro, N.C.

**18 Burial, Cremation or Removal**

Place Asheboro, N.C. Date Oct. 14 1937

**19 Undertaker** Pugh's Funeral HOme, Asheboro, N.C.


**Medical Certification of Death**

**21 Date of death** Oct. 12, 1937

**22 I HEREBY CERTIFY**, That I attended deceased from 9/28, 1937, to 10/12, 1937 I last saw her alive on 10/12, 1937, death is said to have occurred on the date stated above a 6 p.m.

The principal causes of death and related causes of importance in order of onset were as follows:

| | Date of onset |
| --------------------------------------------- | ------------- |
| Pneumonia | 10/9 |
| Hyperthyroidism from toxic adenoma of thyroid | about 1935 |

Name of operation Thyroidectomy date of 10/8/37

What test confirmed diagnosis? Operation Was there an autopsy? No


**24 Was disease or injury in any way related to occupation of deceased?** No


(Signed) H.L Brockman, M.D.

High Point, N.C.

## Notes
refersto::[Juanita Rush](./../../people/Rush-line/Juanita_Rush.html)
refersto::[Thomas E. Lassiter](./../../people/Randolph_county_lines/Lassiter/Thomas_E._Lassiter.html)
refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[Frances Hix](./../../people/Randolph_county_lines/Hicks/Frances_Hix.html)
