refersto::[Mona Rush](./../../people/Rush-line/Mona_Rush.html)
refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[Frances Hix](./../../people/Randolph_county_lines/Hicks/Frances_Hix.html)
refersto::[Charles R. Smith Sr.](./../../people/Smith-line/Charles_R._Smith_Sr..html)
refersto::[David Hammond Smith](./../../people/Smith-line/David_Hammond_Smith.html)

## Source


#### Source Citation

Virginia Department of Health; Richmond, Virginia; _Virginia Deaths, 1912-2014_

#### Source Information

Ancestry.com. _Virginia, U.S., Death Records, 1912-2014_ . Lehi, UT, USA: Ancestry.com Operations, Inc., 2015.

Original data: Virginia, Deaths, 1912–2014. Virginia Department of Health, Richmond, Virginia.


## Notes

Mona Rush Smith,

F
date of death: 11-27-67 
age 76
place of death: 267 Toy Ave., Va. Beach
residence: 120t Cambria Street, Christiansburg
father: Harris Rush
mother: Frances Hicks
widowed
spouse Charles R. Smith
birthplace Ashboro, NC
date of birth Feb. 19, 1891
last occupation Housewife
informant David H. Smith
immediate casue Undetermined (natural)

signed John Jay Krueger, MD, Va. Beach, 27 Nov 67

place of burial Sunset Cemetery, Christiansburg, Va.
funeral director Allen O. Raines
Richardson Funeral Home, Christiansburg, Va.

signature of registrar Edna R. Lamorelle 
date Nov. 29, 1967

