refersto::[William E. White](./../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Horatio Nelson White](./../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Syrena Adams](./../../people/Merrill-line/White-line/Syrena_Adams.html)


## Source

Ancestry.com. _Vermont, U.S., Vital Records, 1720-1908_ [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2013.

Original data: State of Vermont. Vermont Vital Records through 1870. New England Historic Genealogical Society, Boston, Massachusetts.

State of Vermont. Vermont Vital Records, 1871–1908. New England Historic Genealogical Society, Boston, Massachusetts.


## Transcription

Full Name of Deceased White, William E.

Place of Death Panton, Vermont

Color White Age 65 Yrs 6 Mos. 25 Days Md.

Occupation Farming

Birthplace Panton, Vt.

Father's Name H. Nelson White

Mother's Maiden Name Cyrena

Date of Death 1902 Month March Day 8

Disease Causing Death Angina Pectoris

Medical Attendant Dr. Pilon

Town Panton, Vt. Rollin J. Kent Town Clerk
