---
engine: julia
---

# Neel Smith: personal site


## What's here

On this site I'm sharing some of my research on topics not connected to my professional work. In one way or another, most of it concerns the history of my children's family. Currently, the site includes a little [background context](./familyhistory/), and [a blog](./posts.qmd) section where I'm sporadically posting notes. 

I'm interested more generally in how to do historical research and use historical sources in writing for digital platforms. Future posts may also include some "DIY" notes on how I'm carrying out different parts of my research.


## Following updates

All pages on this web site have a "published" data showing when the published page was last updated. In [the "Posts" section](/./posts.qmd), notes are sorted by date, so if you peek there, you'll see newest additions on top.

There's also an [<i class="bi bi-rss"></i> RSS feed](https://neelsmith.quarto.pub/personal/posts.xml) if you prefer to automate notification of updates.



:::{.callout-tip title="My professional work on line"}
I have a separate web site where I'm posting some of my current on-line professional work, currently focused primarily on using language models to understand the syntax of historical languages like Greek, Latin and Hebrew. You can find it at [https://neelsmith.github.io/](https://neelsmith.github.io/).
:::