---
engine: julia
---

# Index

- [Adam Euless 1840 census](./Adam_Euless_1840_census.html)
- [Almeda Gattis 1870 census](./Almeda_Gattis_1870_census.html)
- [Almeda Gattis 1880 census](./Almeda_Gattis_1880_census.html)
- [Almeda Gattis 1900 census](./Almeda_Gattis_1900_census.html)
- [Almeda Gattis 1910 census](./Almeda_Gattis_1910_census.html)
- [Cassie E. Gattis 1900 census](./Cassie_E._Gattis_1900_census.html)
- [Claud Gattis 1890 census](./Claud_Gattis_1890_census.html)
- [Cordelia Gattis 1870 census](./Cordelia_Gattis_1870_census.html)
- [Cordelia Gattis 1880 census](./Cordelia_Gattis_1880_census.html)
- [Cordelia Gattis 1900 census](./Cordelia_Gattis_1900_census.html)
- [Cordelia Gattis 1910 census](./Cordelia_Gattis_1910_census.html)
- [Dorotha Schofner 1850 census](./Dorotha_Schofner_1850_census.html)
- [Edith Gattis 1900 census](./Edith_Gattis_1900_census.html)
- [Elvira Ann Williams 1850 census](./Elvira_Ann_Williams_1850_census.html)
- [Emma Dora Gattis 1870 census](./Emma_Dora_Gattis_1870_census.html)
- [Evaline Gattis 1870 census](./Evaline_Gattis_1870_census.html)
- [Isaac Newton Gattis 1870 census](./Isaac_Newton_Gattis_1870_census.html)
- [Isaac Newton Gattis 1880 census](./Isaac_Newton_Gattis_1880_census.html)
- [Isaac Newton Gattis 1900 census](./Isaac_Newton_Gattis_1900_census.html)
- [James Gattis 1870 census](./James_Gattis_1870_census.html)
- [James Green 1850 census](./James_Green_1850_census.html)
- [Julia Euless 1850 census](./Julia_Euless_1850_census.html)
- [Julia Euless 1870 census](./Julia_Euless_1870_census.html)
- [Julia Euless 1880 census](./Julia_Euless_1880_census.html)
- [Julia Euless 1900 census](./Julia_Euless_1900_census.html)
- [Julia Euless 1910 census](./Julia_Euless_1910_census.html)
- [Martin A. Gattis 1870 census](./Martin_A._Gattis_1870_census.html)
- [Martin A. Gattis 1880 census](./Martin_A._Gattis_1880_census.html)
- [Martin Shofner 1790 census](./Martin_Shofner_1790_census.html)
- [Martin Shofner 1800 census](./Martin_Shofner_1800_census.html)
- [Martin Shofner 1830 census](./Martin_Shofner_1830_census.html)
- [Mary Gattis 1850 census](./Mary_Gattis_1850_census.html)
- [Michael Shofner 1790 census](./Michael_Shofner_1790_census.html)
- [Michael Shofner 1800 census](./Michael_Shofner_1800_census.html)
- [Thomas A. Gattis 1850 census](./Thomas_A._Gattis_1850_census.html)
- [Thomas A. Gattis 1870 census](./Thomas_A._Gattis_1870_census.html)
- [Thomas A. Gattis 1880 census](./Thomas_A._Gattis_1880_census.html)
- [Thomas G. Gattis 1890 census](./Thomas_G._Gattis_1890_census.html)