---
engine: julia
---

# Index

- [Adaline White 1850 census](./Adaline_White_1850_census.html)
- [Artemas White 1850 census](./Artemas_White_1850_census.html)
- [Candace White 1850 census](./Candace_White_1850_census.html)
- [Candace White 1860 census](./Candace_White_1860_census.html)
- [Cynthia White 1850 census](./Cynthia_White_1850_census.html)
- [Frances E. White 1860 census](./Frances_E._White_1860_census.html)
- [Francis E. White 1850 census](./Francis_E._White_1850_census.html)
- [Francis E. White 1870 census](./Francis_E._White_1870_census.html)
- [Friend White 1850 census](./Friend_White_1850_census.html)
- [George White 1850 census](./George_White_1850_census.html)
- [George White 1860 census](./George_White_1860_census.html)
- [Henry George White 1840 census](./Henry_George_White_1840_census.html)
- [Henry George White 1850 census](./Henry_George_White_1850_census.html)
- [Hiram White 1850 census](./Hiram_White_1850_census.html)
- [Horatio N. White 1840 census](./Horatio_N._White_1840_census.html)
- [Horatio N. White 1850 census](./Horatio_N._White_1850_census.html)
- [Horatio N. White 1860 census](./Horatio_N._White_1860_census.html)
- [Horatio N. White 1870 census](./Horatio_N._White_1870_census.html)
- [Horatio N. White 1880 census](./Horatio_N._White_1880_census.html)
- [Lydia B. White 1850 census](./Lydia_B._White_1850_census.html)
- [Lydia Brumley 1850 census](./Lydia_Brumley_1850_census.html)
- [Moses Smith 1790 census](./Moses_Smith_1790_census.html)
- [Moses Smith 1800 census](./Moses_Smith_1800_census.html)
- [Susan White 1880 census](./Susan_White_1880_census.html)
- [Syrena White 1850 census](./Syrena_White_1850_census.html)
- [Syrena White 1860 census](./Syrena_White_1860_census.html)
- [Syrena White 1870 census](./Syrena_White_1870_census.html)
- [William E. White 1850 census](./William_E._White_1850_census.html)


## Further documents


- [Ebenezer White census](./Ebenezer_White_census/)
- [Mollie G. White census](./Mollie_G._White_census/)