
## Source

Wills, 1792-1917; Will Index, 1792-1970; Author: New York. Surrogate's Court (Herkimer County); Probate Place: Herkimer, New York

###### Description

Notes: _Wills, Vol K-L, 1854-1862_

###### Source Information

Ancestry.com. _New York, U.S., Wills and Probate Records, 1659-1999_ . Lehi, UT, USA: Ancestry.com Operations, Inc., 2015. 
Original data:New York County, District and Probate Courts.



## Transcription

Daniel C. Henderson

County of Herkimer Surrogate Court

In the Matter of proving the last will and testament of Daniel C. Henderson Deceased

Herkimer County fo Elias B. Pullman of the Town of Norway in the County of Herkimer being first Sworn in Open Court on their Oaths do depose and say that the said deceased did in the presence of these deponents subscribe his name at the end of the instrument which is now shown to these deponents and which purportz to be the last will and testament of the said Deceased and which bears date on the 17th day of January A.D. 1860 that the said Deceased did at the time of subscribing his name to said instrument as aforesid declair the same to be his last will and testament that these deponents did thereupon subscribe their names at the end of said instrument as attesting Witness to the execution thereof at the request of the said Deceased and in his presence and in the presence of each Other That the said Deceased at the time of subscribing his name to said instrument as aforesaid has upwards of twenty one years of age that he appears to be of sound mind and memory and was not under restraint to the knowledge or belief of these deponents

Sworn examened and subscribed this 1st day of October 1860 before me Ezra Graves Surrogate

Sarah Pullman

Elias B. Pullman


I Daniel C Henderson of the Town of Norway County of Herkimer State of New York being deeply impressed by the ?im...lantly? of human Life doest Constitute this my last will and testament in the Manner following 1st To my beloved Wife Margaret besides her right of Dower it is my will that she retain in her full possession of the house and lot togethger with the household furniture during her natural lifetime or so long as she remains my Widow

2nd To my son Dryden Henderson I devise and bequeath my House and lot called the Mason House and the store and lot called the Beadley Store to him my son Dryden of his full share of my estate after the deceast of my beloved wife Margaret

Let it be understood that I have lately bought a lot of some twenty Acres 20% called the Pullman lot which is not all paid for now what is not paid at my deceast my three sons Dryden Nathaniel and John D. Henderson must equally pay or caused to be paid after the Bond I gave for the payment for the lot called the Pullman lot my three sons Dryden Nathaniel and John D Henderson must pay each one Hundred Dollars to my youngest Daughter Sarah Bragg to whom I devise and give the lot called the Pullman lot as her full share of my Estate excepting what is hereafter mentioned

To my four Grand Children heirs of my son Hugh deseast I bequeath to Margaret Henderson fifty Dollars to Daniel C James E & John D Henderson my Grand Children one hundred Dollars each to be paid in three and four years after my decest by my executors after the deceast of my beloved wife the house hold furniture is to be Equally divided between my three Daughters Mary Ann Tillinghast Juliette M Johnson and Sarah Bragg after all Claims and bequeaths debts are paid the rest of my property consisting of Mortgatges Bonds or Notes accounts or any note heretofore mentioned of whatever name or nature that except heretofore or hereafter is to be equally divided between my Children mentioned hereafter viz Nathaniel S Henderson John D Henderson Mary Ann Tillinghast Juliette M John son My Libra? such as it is to divided Equally between my three sons heretofore named If theire are Carrages of any kind Waggon be eather at my deceast my son Dryden Henderson must have my Old Natch I give to my Grand son Horace Bragg

Lastly I hereby appoint my son Dryden and Nathaniel S Henderson my executors of this my last will and testament hereby revoking all former will by me made

Daniel C Henderson

In witness whereof I have hereunto set my hand and affixed my seal this seventeenth day of January one Thousand Eight Hundred and Sixty Signed Sealed published and delivered be the above named Daniel C Henderson to be his last will and testament in presence of us who have hereunto subscribed Our Names as Witnesses in presence of the testator and at his request

Elias B Pullman Norway
Sarah Pullman Norway

County of Herkimer

Surrogate Office for

Be it remembered that on the day of the date hereof the last will and testament of Daniel C Henderson late of Norway in the County of Herkimer Deceased bearing date 17th day of January One Thousand Eight Hundred and Sixty 

(certification of copy continues on following page)

## Notes


refersto::[Daniel Clyde Henderson](./../../people/Henderson-line/Daniel_Clyde_Henderson.html)
refersto::[Margaret Carpenter](./../../people/Henderson-line/Carpenter-line/Margaret_Carpenter.html)

He has three living sons:

refersto::[John Dryden Henderson](./../../people/Henderson-line/John_Dryden_Henderson.html)
refersto::[Dryden Henderson](./../../people/Henderson-line/Dryden_Henderson.html)
refersto::[Nathaniel S. Henderson](./../../people/Henderson-line/Nathaniel_S._Henderson.html)

Youngest daughter: 

refersto::[Sarah Henderson](./../../people/Henderson-line/Sarah_Henderson.html)


Deceased son:

refersto::[Hugh Henderson](./../../people/Henderson-line/Hugh_Henderson.html)

Hugh's children:

refersto::[Margaret Henderson](./../../people/Henderson-line/Margaret_Henderson.html)
refersto::[Daniel C. Henderson](./../../people/Henderson-line/Daniel_C._Henderson.html)
refersto::[John D. Henderson](./../../people/Henderson-line/John_D._Henderson.html)
refersto::[James E. Henderson](./../../people/Henderson-line/James_E._Henderson.html)


Daniel C.'s three daugthers:

refersto::[Mary Ann Henderson](./../../people/Henderson-line/Mary_Ann_Henderson.html)
refersto::[Juliette Henderson](./../../people/Henderson-line/Juliette_Henderson.html)

Grandson of Daniel C:

refersto::[Horace Bragg](./../../people/Henderson-line/Horace_Bragg.html)
