
## Citation

_Probate Records (Worcester County, Massachusetts); Index 1731-1881_; Author: _Massachusetts. Probate Court (Worcester County)_

#### Source Information

Ancestry.com. _Massachusetts, U.S., Wills and Probate Records, 1635-1991_[database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2015.

Original data: Massachusetts County, District and Probate Courts.

## Transcription

James Rices Will

In the name of God. Amen.

I James Rice of Barre in the County of Worcester Yeoman, being weak in Body , but of sound and disposing mind and memory, blessed be God for the same, do make this my last Will and Testament this fifteenth day of July, in the year of our Lord, One thousand, eight hundred and thirty two, as follows viz.

I recommend my Soul to God who gave it.

Firstly. I will and direct that my Executor hereafter named, provide and support my beloved Wife during her natural life, comfortably and furnish her with all things necessary for her in sickness and health, and at her decease, a decent burial. my said Wife is to have the use and improvement of my House hold Furniture during her life, and after her decease to be equally divided among my Heirs.

Secondly. I give and bequeath unto my son Samuel Rice, his heirs and assigns forever, all my Homestead Farm situate and lying in Barre & Petersham which is now owned and lies in common between us. Also the Brinknal lot, so called, the Mann lot, so called, and Mill lot, so called. Said last mentioned lot lies in Petersham, and also the Hammond lot, so called. Also I give unto the said Samuel Rice, all my Stock and Farming Tools, to be at his own disposal forever. also my Pew in Barre Meeting House.


Thirdly. I give and bequeath unto my Grandchildren hereafter named, their heirs, etc., to wit, Clarissa Miller wife, Schuyler Miller, the sum of seventy-five Dollars, to be paid by my Executor, in one year after my decease. Also I give unto my other Grandchildren Lucretia Partridge and Lucy Rice to each of them I give the sum of seventy five dollars to be paid them by my Executor hereafter named, in one year after my decease.

Fourthly. To the Heirs of Freeman Rice, I give nothing. I give to Alfred Cladwell, son of Susan Wilder, two hundred dollars, to be paid him by my Executor in one year after my death.

Fifthly and lastly. As to the residue of all my property after paying out my just debts and funeral expenses which property is not before named, I give & bequeath the same to my Sons viz. Sparahawk Rice, Ralph Rice and Nahah Rice, their heirs etc to be equally divided between them.

I direct my Executor to sell all my Real Estate not before disposed of, as soon as convenient after my decease, and apply the proceeds as before divided, as also the remainder of my personal property.

I hereby appoint my Son Samuel, sole Executor of this my last Will and Testament, hereby revoking all other and former Wills, by me made.

In Witness whereof, I hve hereunto set my hand and seal, the day and year above written.

James x Rice
his mark


Signed, sealed, published and declared by the said James Rice to be his last WIll and Testament in presence of us, who are called as Witnesses to the same by said Rice, and have signed our names to the same in his presence.

Nath. Houghton

Anson Bates

Charles Rice

Worcester. To all people to whom these presents shall come, Nath. Paine Esq. Judge of Probate of Wills, etc in the County of Worcester within the Commonwealt of Massachusetts, sendeth Greeting


 ## ***REMAINDER TBA...****
 



## Notes.


refersto::[James Rice](./../../people/Merrill-line/White-line/James_Rice.html)

The unnamed wife is presumably Ruth Wilson, outlives him by 5 years:

refersto::[Ruth Wilson](./../../people/Merrill-line/White-line/Wilson-line/Ruth_Wilson.html)

Eldest son and sole exectuor:

refersto::[Samuel Rice](./../../people/Merrill-line/White-line/Samuel_Rice.html)


A married granddaughter:

refersto::[[Clarissa Miller]]
refersto::[[Schuyler Miller]]

Two other granddaughters probably not married:

refersto::[[Lucretia Partridge]]
refersto::[[Lucy Rice]]


A son of James and Hannah is cut out of the will:

refersto::[Freeman Rice](./../../people/Freeman_Rice.html)

Another beneficiary:

refersto::[[Alfred Cladwell]] 

who is son of 

refersto[[Susan Wilder]]




Sons:

refersto::[[Sparahawk Rice]]
refersto::[[Ralph Rice]]
refersto::[[Nahah Rice]]

