refersto::[[people/Randolph county lines/Marmaduke Vickery]]


## Source
###### Source Citation

Wills, 1663-1978; Estate Papers, 1781-1928 (Randolph County); Author: North Carolina. Division of Archives and History; Probate Place: Randolph, North Carolina

###### Description

Notes: _Original Wills, Stout, Joseph - Yow, Henry_

###### Source Information

Ancestry.com. _North Carolina, U.S., Wills and Probate Records, 1665-1998_. Provo, UT, USA: Ancestry.com Operations, Inc., 2015. 
Original data:North Carolina County, District and Probate Courts.
## Transcription
(by DHS: needs to be verified against photography on Ancestry)


>Randolph County, North Carolina—Will Book 1, p. 6626th day of December in 1787

In the name of God Amen. I, Marmaduke Vickory, Sen., of the County of Randolph and the State of North Carolina, Planter, Being Sick and Weak in body but of perfect mind and memory, Thanks be given to God for the Same, Calling to mind the mortality of my Body and knowing that it is appointed for all men once to die, do make, ordain and appoint this my Last Will and Testament in manner and form as follows. First of all, I Recommend my Soul to God that gave it and my body to the earth to be Buried in Christian Burial at the Directions of my herin after named Executor and as touching my worldly Estate which God hath pleased to bless me with in this Life I give, devise and dispose of the same in the following manner and form. Item. I give unto my well beloved wife Elizabeth Vickory the full possession of my Dwelling house with all of my household goods and furniture during her Natural Life and at her decease to be disposed of in manner and form as follows———Item. I give and bequeath to my Beloved Son Samson Vickory all my lands and Tenements Except that part conveyed to my Grandson Marmaduke Vickory Second by Deed of gifts bearing Date December the Twenty fifth day one thousand Seven hundred and Eighty Seven— 
Item I give and bequeath to my son Samson Vickory all my personal Estate of Every kind quality and Specie to be possessed by him and possession of my Dwelling house with all the household furniture freely to be possessed by him with all the Benefits thereunto belonging and I do appoint the Son Samson Vickory and him alone to be my Executor of this my Last Will and Testament In Witness Whereof I have set my hand and seal this twenty Seventh day of December and in the year of our Lord on thousand seven hundred and Eight seven.

Marmaduke Vickory (his mark) Witnessed 
Christopher VickoryMarmaduke Vickory

Inventory of this estate—Randolph County, December 1788One hundred acreas of land, one horse, & one mare, five head cattle, 2 beds, and furniture—1 Cubbard & Table, 2 pots, 1 oven, a note of hand four pounds, puter tins and chairs, wearing clothes, 1 Saddle, 1 Bridle, 1 pr. plow irons, 1 as, 1 hoe, 2 pr horse chains, 1 log chain, 1 pr stillard, 1 skillet, 2 iron pots, rack, 1 pr. fire tongs, 2 pails, 1 churn, 1 spinning wheel, 1 Drawing knife, knives & forks, 1 Trunk, 1 Reul?, 1 picking fork, 1 pr (illegible)

Returned by executor Sampson Vickory of said estate