refersto::[[Sallie T. Harris]]

## Transcription

### First page 
Will of Sallie T. Williams, deceased.

> I, Sallie T. Williams, being of sound mind and disposing memory, do make and publish this my last will and testament, herby rvoking any other will made by me.
>
>Item First.
>I direct the payment of any just debt that I may be owing at the time of my death, together with my funeral and burial expenses, out of the first money that may come into the hands of my executors herinafter named.
>Item Two.
>If the graves of my husband, David Williams, Sr., and my son, David Williams, Jr., and my daughter Lavenia Williams, have not been propertly marked at the time of my death, my executor is directed to do so, using such amount therefor as he may deem right and proper in the exercise of his discretion.
>Item Three.
>All the balance of my estate of every kind and description I give and bequeath in equal amounts as follows:- one share to my daughter, Elivra Ann Green, wife of J.G. Green; one share to Normer Barber Williams and her sister, Nellie Barber Turrentine, wife of Sam Turrentine; one share to Minnie Williams and Mary WIlliams, my grandchildren, the children of my deceased son David Williams, Jr.
>Item Fourth.
>I nominate and appoint J.G. Green and wilfe Elivira Ann Green executors of this my last will and testament.
>
 Sallie T. Williams
>
> We the undersigned have attached our names hereto as attesting witnesses in the presence and at the request of the testatrix, who sigbned the above in our presence as her last will and testament and we have signed as attesting witnesses in the presence of each other, This the -- day of -- 1902.
>
> Saml. L. Knox
> Joe Landers
> 
> I, J.G. Green, make oath that the above is a true and perfect copy of the last will and testament of Sallie T. Williams, deceased, as nearly aas I can give the same from memory, the original of which was destroyed by L.B. Williams in my presence on Oct. 14, 1910.
> 
> J.G. Green
> 
> sworn to and subscribed before me, this October 26th, 1910.
> E.W. Bearden, [??]



### Second page

Certificate of Clerk and master
State of Tennessee
County of Bedford,

I, E.W. Bearden, clerk and master of the Chancery Court at Shelbyville, do certify that the within and foregoing is a full, true and perfect copy of the last will and testament of Sallie T. Williams, deceased, as set up and established by decree of Chancery Court rendered on Nov. 8th, 1910, and entered in Minute book "Q" (?) pages 481 et seq. in said Court the cause therein of "J.G. Green et als. vs. L.B. Williams". Said will was, by said decree, ordered to be certified to the County Court of Bedford County, Tenn., there to be proceeded on and under as the last will and testament of said Sallie T. Williams, deceased.
Witness my hand and seal of office, in Shelbyville, Tenn., this Nov 10th., 1910,
E.W. Bearden, Clerk & Master
State of Tennessee.
Bedford County.

I, P.C. Steele, County Court Clerk of Bedford County, do herby certify tht the foregoing is a full, true and perfect copy of the last will and testament of Sallie T. Williams, deceased, as certifeid to this court by E.W. Bearden, Clerk & Master of the Chancery Court at Shelbyville, Tenn, and admitted to probate in the County Court of Bedford County on the 14th day of November, 1910. and order to be recroded as the last will and testament of Sallie T. Williams, as shows by certified copy now on file in my office.
Witness my hand at office this the 14th day Nov. 1910,
P.C. Steele, Clear,
By Jo.D.Steele D.C.




## Citation

Wills, 1861-1966; Wills and Inventories, 1863-1889, 1890-1929, 1937-1965; Author: Bedford County (Tennessee) County Court Clerk; Probate Place: Bedford, Tennessee

###### Description

Notes: _Wills, Vol 1-2, 1861-1922_

###### Source Information

Ancestry.com. _Tennessee, U.S., Wills and Probate Records, 1779-2008_ . Lehi, UT, USA: Ancestry.com Operations, Inc., 2015. 
Original data:Tennessee County, District and Probate Courts.



