
refersto::[Zebedee Rush 1790-1872](./../../people/Rush-line/Zebedee_Rush_1790-1872.html)
refersto::[Benjamin C. Rush](./../../people/Rush-line/Benjamin_C._Rush.html)
refersto::[Archibald Franklin Rush](./../../people/Rush-line/Archibald_Franklin_Rush.html)
refersto::[Martha Rush](./../../people/Smith-line/Martha_Rush.html)
refersto::[William Pearce](./../../people/Smith-line/William_Pearce.html)
refersto::[Noah Rush](./../../people/Rush-line/Noah_Rush.html)
refersto::[Henry Rush](./../../people/Rush-line/Henry_Rush.html)
refersto::[Dorcas Rush](./../../people/Rush-line/Dorcas_Rush.html)
refersto::[Arthur Hair Niell](./../../people/Randolph_county_lines/Arthur_Hair_Niell.html)
refersto::[Elizabeth A. Rush](./../../people/Rush-line/Elizabeth_A._Rush.html)
refersto::[Farley Brookshire Lewis](./../../people/Randolph_county_lines/Lewis/Farley_Brookshire_Lewis.html)
refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[Zebedee Franklin Rush](./../../people/Rush-line/Zebedee_Franklin_Rush.html)
refersto::[Frances Rush](./../../people/Rush-line/Frances_Rush.html)
refersto::[Drewry Lewis](./../../people/Rush-line/Drewry_Lewis.html)


## Citation

Detail

Wills, 1663-1978; Estate Papers, 1781-1928 (Randolph County); Author: North Carolina. Division of Archives and History; Probate Place: Randolph, North Carolina

Edit source

### Source information

Title

North Carolina, U.S., Wills and Probate Records, 1665-1998

Author

Ancestry.com

Publisher

Ancestry.com Operations, Inc.

Publisher date

2015

Publisher location

Provo, UT, USA

## Notes

Zebidee F. gets the land

## Partial transcription....

Know all men by these presents, that I, Zebidee Rush, of the county of Randolph & state of North Carolina, being of good health and of sound mind, and disposing memory, do make and publish this my last will and testament, hereby revoking all former wills by me at any time heretofore made.

And as to my worldly estate, and all the property real, personal or mixed, of which I shall die seized and possessed or to which I shall be entitled at the time of my decease I devise, bequeath and dispose thereof in this manner following - to wit -

First - My will is, that all my just debts and funeral expenses, shall, by my Executors hereinafter named be paid out of my estate, as soon after my decease, as shall by them be found convenient

Item - The full owning and raising of my children - to wit - Benjamin C., Archibald F, Martha, who intermarried with Wm. Pearce, Noah, Henry - Dorcas, who intermarried with Arthur H. Neal - Fannie, who intermarried with Drury Lewis -- Zebidee F. -- Eliza, who intermarried with Farlow Lewis, - Calvin - and Duncan K. Rush -- And my will is, that if any of the above married children, ... named, in this my will -- and go to law for and about the 

[....]


Item - I give, dispose and bequeath to my son Zebidee F. Rush, the following ...

