refersto::[Claud Gattis](./../../people/Gattis-line/Claud_Gattis.html)


## Source

## Transcription

**Claude J. Gattis**

Services for Claude J. Gattis, 91, of 1115 Virginia Ave., who died Wednesday at the VA Medical Center, will be held at 3 p.m. Friday at Jennings & Ayers Chapel, with burial in Evergreen Cemetery. The Reverends John Willimas and Phillip Horne will officiate.

His parents were the late I.N. and Cassie Green Gattis.

He is survived by his wife, Louse Gattis of Murfreesboro; two daughters, Judy Smith of Williamsburg, Va., Gloria Andrews of Murfreesboro; five grandchildren and a great-grandchild.

A member of the First United Methodist Church and American Legion, he was a Purple Heart veteran of World War I with the U.S. Army's 114th Artillery Battalion. He was a retired assistant postmaster with 37 hears service and a native of Bedford County.

Grandsons and nephews will be pallbearers with former employees of the Murfreesboro Post Office serving as honorary pallbearers.

Visitation with the family be help from 7 to 9 tonight at Jennings & Ayers Chapel.
