## Citation

_Sentinel and Democrat_; Publication Date: _11 Dec 1806_; Publication Place: _Burlington, Vermont, USA_; URL: _https://www.newspapers.com/image/488872002/?article=6fa3e744-dab4-43ae-a8a5-f16fbbb1c1f7&xid=4717&terms=Ebenezer_White_


## Transcription



Citation

Notice i herby given to all the creditors of Ebenezer White of Essex, County of Chittenden and State of Vermont, that he is now in confinement in the common goal [sic] in Burlington, by virtue of a writ of execution issued from the County Court of Chittenden County, at their Sept. Term, 1806, and duly signed by their Clerk, Solomon Miller, in favor of William and Christopher Slocom, of the city and State of New York, and a complaint has been issued in due form to Noah Chittenden, Esq. Judge and Roger Enos, Esq. Justice of the Peace, and a citation duly issued and served on the said William and Christopher, through the medium of their Attorney of record, directing them to appear at the dwelling house of Maj. Lyman King, in Burlington aforesaid, at eleven o'clock, forenoon, on the 20th day of December inst. to shew cause, why the said Ebenezer should not be personally liberated agreeable to the statute provided for the relief of poor prisoners; and at the same time and place his other creditors are directed to appear and shew cause as aforesaid.

By order of ROGER ENOS, Justice Peace

Burlington, Dec. 2, 1806
