
## Source

*The Buffalo News*, December 30, 1902, Page 5. via Newspapers.com (https://www.newspapers.com/article/the-buffalo-news-obituary-for-henry-geor/167255884/ : accessed March 5, 2025), clip page for Obituary for Henry George White by user neel_smith_home
## Transcription

**H. G. WHITE DEAD.**

---

**Buffalo's Oldest Citizen Died Suddenly at His Home on Irving Place.** 

---

In the death of Henry George White, Buffalo loses its oldest resident as well as an estimable citizen. He was born in Burlington, Vt., June 8, 1814, and died at his home, 32 Irving Place, at 6 o'clock this morning. Death, although resulting from old age, was unexpected. Last night Mr. White retired as well as he has ever been during the past two years, and this morning he was discovered dying by one of the members of the family. A physician was summoned, but the dying man expired as the physician crossed the threshold.

Mr. White, who would soon reach his 90th year, came to this city in 1836, full of the energy and ambition of youth. He had great faith in Buffalo's future. Immediately on his arrival he started to learn the painter's trade in all its branches. So well did he succeed that in 1838 he bought out the business and good-will of his employer, and thus, while just beginning his 25th year, he became his own "boss" and remained one ever since. His place of business was at 53 Main street, where he remained for over half a century. 

Some years ago he formed a partnership with William H. Pinck and the business was then carried on under the name of White & Pinck and still continues under that name. For several years previous to the time of his death Mr. White refrained from participating in the active business of the firm, although still retaining his interest in the establishment.

He was married three times. In 1840 he married Ann Quayle of the Isle of Man, Eng., who died in 1860. Four children were born to them, and the following three are now living: George W. White and Charles H. White of this city and James H. White of Anadarko, Oklahoma. In 1862 he married Susan N. Prince, belonging to the well-known Prince family of this city, who died in 1864. In 1865 he married Susan D. Church of this city, who survives him. One son was born to them, Eugene R. White, editor of the Niagara Falls Gazette, and formerly a member of the editorial staff of the EVENING NEWS.

As to polltical bellef Mr. White was a Republican, although the first President for whom he cast a vote was the fiery Andrew Jackson. He was closely connected with the work of the Church of Our Father, of which he was one of the founders, and although a strict Unitarian by faith, was always willing to allow for the religious belles of others. 

The funeral will take place from the family residence at 3 o'clock tomorrow afternoon.The Rev. Frederick Brown, pastor of the Church of Our Father, will officiate.

## Notes

refersto::[Henry George White](./../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Ann Quayle](./../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[George W. White](./../../people/Merrill-line/White-line/George_W._White.html)
refersto::[Charles H. White](./../../people/Merrill-line/White-line/Charles_H._White.html)
refersto::[James Herbert White](./../../people/Merrill-line/White-line/James_Herbert_White.html)
refersto::[Susan Prince](./../../people/Merrill-line/White-line/Susan_Prince.html)
refersto::[Susan D. Winslow](./../../people/Merrill-line/White-line/Susan_D._Winslow.html)
refersto::[Eugene Richard White](./../../people/Merrill-line/White-line/Eugene_Richard_White.html)
