
## Source

*The Burlington Free Press*, June 30, 1893, Page 5. via Newspapers.com (https://www.newspapers.com/article/the-burlington-free-press-obituary-for-h/167283354/ : accessed March 5, 2025), clip page for Obituary for Hiram S. White by user neel_smith_home


## Transcription

**"HIGH" WHITE DEAD.** 

---

**He Passed Away Yesterday in the 77th Year of His Age.** 


Hiram White died yesterday morning in the 77th year of his age. He was one of the city's oldest residents. In his early life he was very active. When the gold craze spread over the country he was one of the many who went to California. Gold not being as plentiful as he anticipated he came back and settled down contented. He captained a canal boat for years, run a grocery store for a time and in his later years lived upon a farm. He was successful in all these pursuits and accumulated considerable property. 

In his prime Mr. White was an active member of the Boxer Engine company and was always more or less mixed up in politics, being a "dyed-in-the-wood" democrat. He served as constable and collector of taxes. This gave him a wide acquaintance and be was familiarly known by all as "High" White. He was, also, a member of the Howard Guards. Though eccentric in his ways, he bad many admirable traits.

A wife and son survive him.

## Notes

refersto::[Hiram Smith White](./../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Euphemia Armstrong](./../../people/Merrill-line/White-line/Euphemia_Armstrong.html)
