---
engine: julia
---

# Index

- [Anna White Merrill death notice](./Anna_White_Merrill_death_notice.html)
- [Bee Neel obituary LA Times](./Bee_Neel_obituary_LA_Times.html)
- [Calvin Harris Rush obituary in Greensboro News and Record](./Calvin_Harris_Rush_obituary_in_Greensboro_News_and_Record.html)
- [Charles R. Smith obituary Roanoke Times](./Charles_R._Smith_obituary_Roanoke_Times.html)
- [Claud Gattis obituary in News-Journal](./Claud_Gattis_obituary_in_News-Journal.html)
- [Ebenezer White incarcerated Vermont Sentinel and Democrat](./Ebenezer_White_incarcerated_Vermont_Sentinel_and_Democrat.html)
- [H.G. White obituary in Buffalo Enquirer](./H.G._White_obituary_in_Buffalo_Enquirer.html)
- [H.G. White obituary in Buffalo News p. 5](./H.G._White_obituary_in_Buffalo_News_p._5.html)
- [H.G. White obituary in Buffalo News](./H.G._White_obituary_in_Buffalo_News.html)
- [Hiram Smith White obituary in Burlington Free Press](./Hiram_Smith_White_obituary_in_Burlington_Free_Press.html)
- [Isaac N. Gattis obituary Murfreesboro News Journal](./Isaac_N._Gattis_obituary_Murfreesboro_News_Journal.html)
- [Isaac Newton Gattis obituary](./Isaac_Newton_Gattis_obituary.html)
- [James Green obituary](./James_Green_obituary.html)
- [Judy Gattis wedding plans Rutherford Courier](./Judy_Gattis_wedding_plans_Rutherford_Courier.html)
- [Judy Smith birth announcement in Murfreesboro News Journal](./Judy_Smith_birth_announcement_in_Murfreesboro_News_Journal.html)
- [Louise Neel Gattis obituary](./Louise_Neel_Gattis_obituary.html)
- [Moses Smith death in abstract of Columbian Centinel](./Moses_Smith_death_in_abstract_of_Columbian_Centinel.html)
- [Sallie Rush obituary in Asheboro Courier](./Sallie_Rush_obituary_in_Asheboro_Courier.html)
- [Shelley Lindner - John Henderson wedding plans](./Shelley_Lindner_-_John_Henderson_wedding_plans.html)
- [Susan Winslow - Charles Church marriage](./Susan_Winslow_-_Charles_Church_marriage.html)