
## Source

*The Daily News-Journal*, Murfreesboro, Tennessee · Tuesday, February 14, 1928, page 6

## Transcription


**Rutherford Farmer Is Buried Today**

---

**Mr. J.G. Greene Moved Here From Bedford County Fifteen Years Ago**

---

Mr. J.G. Green the venerable father of Mrs. I.N. Gattis, died Monday afternoon at 3 o'clock at his home on the Shelbyville road about 2½ miles south of Murfreesboro, aged 84 year, 9 months and four days.

Mr. Green was a Union soldier and a pensioner. He was a member of the Methodist Church and a man of fine character and was highly esteemed.

Mr. Green came to this county from Bedford about fifteen years ago, and has since resided on his farm purchased at that time. He is survived by his wife and two children, Mrs. Gattis and Joe Green of Nashville. Funeral services were conducted this afternoon at 2:30 o'clock at the home of Mrs. Gattis on South Church street by Dr. John Baggett, Interment at Evergreen Cemetery.



## Notes

refersto::[James Green](./../../people/Gattis-line/Green-line/James_Green.html)
refersto::[Cassie Green](./../../people/Gattis-line/Green-line/Cassie_Green.html)
refersto::[Elvira Ann Williams](./../../people/Gattis-line/Green-line/Williams-line/Elvira_Ann_Williams.html)
refersto::[Joseph Edward Green](./../../Joseph_Edward_Green.html)

