
## Source

Ancestry.com. _U.S., Newspaper Extractions from the Northeast, 1704-1930_[database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2014. This collection was indexed by [Ancestry World Archives Project](https://support.ancestry.com/s/article/Discontinuing-the-Ancestry-World-Archives-Project?language=en_US) contributors.

Original data: Newspapers and Periodicals. American Antiquarian Society, Worcester, Massachusetts.

The Digitized Content is licensed from the American Antiquarian Society ("AAS") and may not be reproduced, transferred, commercially or otherwise exploited, in whole or in part, outside the terms and conditions of this service without the express written consent of AAS. All rights reserved.


## Transcription

Smith, Moses F. Capt. d. in Barre, aged 45 (C.C. Mar. 21, 1835)


## Notes


This refers to a different "Moses Smith" than the father of [Candace Smith](./../../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html) : her fatrher is [[Moses Smith|this Moses Smith]].

