refersto::[Sarah Loflin](./../../people/Randolph_county_lines/Loflin/Sarah_Loflin.html)
refersto::[Zebedee Franklin Rush](./../../people/Rush-line/Zebedee_Franklin_Rush.html)
refersto::[Calvin Harris Rush](./../../people/Rush-line/Calvin_Harris_Rush.html)
refersto::[Mary Jane Rush](./../../people/Rush-line/Mary_Jane_Rush.html)

## Source

*The Courier*, Asheboro, North Carolina · Thursday, September 13, 1906, page 1
## Transcription

**Aged Lady Dead.**

**Funeral of Mrs. Rush at Famer Monday -- Well Attended.**

The funeral of Mrs. Sallie Rush was conducted at Farmer Monday morning at 11 0'clock, and was attended by a large number of relatives and friends from Asheboro. Rev. B.F. Fincher conducted the service.

Mrs. Rush was 86 years old and was a highly respected lady. She had been in declining health for several months and her death Sunday was due to old age.

The deceased was the mother of our townsmen, Z.F. and Harris Rush and Mrs. Nereus Lowe, of Mechanic. Her husband was the late Noah Rush.

The bereaved relatives have the sympathy of a host of friends in the county.

