
 



## Synopsis

>Artemas in Keeseville, NY, writes to Horatio Nelson in Panton, VT. Artemas dates the letter "9 month 31 day" but the post mark is *Oct* 31, 1842.
>
> Artemas writes to arrange delivery of three kegs of nails to Horatio Nelson, and incidentally reports the death of an infant child in his family due to sickness, as well as eight victims in the collapse of a suspension bridge.

# Transcription

Keeseville 9 month 31 Day, 1842

Brother Nelson

i have on hand your nails 3 Kegs and if you will direct me whom to send them i will do so or prehaps it is so late you will conclude to let them be until you come over to Dr Smiths Next winter and then i can send them to you or you can come after them as you think best we have since you our Home ben verry sick which i suppose you have heorn by the way of home but god in his mercy has been merciful to us in that it has sparn the mother and took the babe my wife now enjoys virry good health and is more fleshy than i have ever known hir hir dresses pinch hir in the arms so it is with difficulty she can get them on and off we have hearn the Voice of God speaking to us in a verry mysterious way in the fall of the new suspension bridge which i suppose you have hearn the Particulars as it would fill a Volume to tell it all suffise to say & fellow Beings were consigned to a watery grave the last was found to Day a young french Boy 8 years old he was found in the lake washed on shore but all this Dont say that that wore sinners above others but it says be you also ready for in such an hour as you think not the messenger may come Brother George thinks you treat him with contempt in not writing him my Paper is about out and i must end your 


good by for this time Give my best respecks to those who you have in charge with my families

Artemas


## Illustrations

Front cover: [IMG_3053](./../../../images/White_letters-images/IMG_3053.html) Back cover: [IMG_3054](./../../../images/White_letters-images/IMG_3054.html) Unfolded exterior: [IMG_3055](./../../../images/White_letters-images/IMG_3055.html)

Interior with text of letter: [IMG_3056](./../../../images/White_letters-images/IMG_3056.html)


## Questions and notes

refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)



Who is "Dr. Smith"?
