
 

 


## Synopsis

> Henry George White in Buffalo writes to Horatio Nelson White in Panton.
>
> Henry George exchanges family news, and presses Horatio Nelson to visit during the upcoming state fair to be held in Buffalo. He responds to a request for information about a Dr. Allin who has recently come to Vermont from Buffalo where he was acquitted in a (malpractice?) trial.

## Transcription



Buffalo July 2d 1848

Brother Nelson &c

As it is a rainy afternoon and feeling little or no inclination to go to church I thought to write a few lines to You

As it is usual to begin by writing concerning Health I will say that we are tolerably well that is as well as usual which I suppose is first rate & we hope You and Yours are in a like situation

It has been quite sickly & is now so here diseases of a Bilious nature Billious Fever, Fever ague &c but we have all escaped as Yet, in the country as well as the city it has been the same but it appears to be rather abating now

Our Little ones grow somewhat although I would be glad if Charles grew faster, he does not appear sick Yet he does not grow & thrive as I would like, George is as well as most Boys are of his age & our little one the girl Ann Eliza (she of whom you wrote concening those shoes) grows finely & has every appearance of of being healthy Ann & myself prety tolerable well

Our weather has has been quite dry since April Yet we have fine coll Breezes from the Lake which make it comfortable

My Business has been quite good that is I have done considerable work but I do not know how the crop will gather perhaps it may rot in the Ground & perhaps it may prove a good Yield at any rate it is planted & I think for the most part in good soil I have had work for from 10 to 20 men since February

Having now given You a history of matters & things perhaps it may be well to broach another subject

We would be glad to hear from You & from all of our Nephews & Nieces & hope we may be fortified by the receipt of a Letter from each, I would send them a paper accasionaly but for that odious 3 cent prepayment of postage I wish all papers were free postage My Boy William I hope he will write another Letter & also Friend. Frances & George, Frances wrote a fine Letter which we have Yet & shall keep in hopes of getting another so if You desire to practice write again Frances

I have not heard from Home for some time & I fear we are all getting to be selfish & do not care to hear or write to our Friends now such should not be the case & shall not be on my part I assure You.

We expect you & Syrena out here this season & as the state fair is to be held here this Year in the early part of September we thought that perhaps it might add to the inducement for You to come for I assure You it will be a splendid thing & probably more people will be gathered here than ever before besides the Animals & other things usual on such accasions & You being Farmers ought to be interested I will write You again when it is to be if You desire & if You make up Your mind to come the thing is half done then I know it is hard times but money ought to be looked upon as a means given us to promote our own & others happiness We hope You will make up Your minds to come & also that *will come* for there will never probably be so much to induce You to come as now so prepare to come & start & You will be here before You thought of it

I usualy write over the whole sheet but now I think I shall not do so but You have my meaning without any palaver

I shall write to Artemas for I feel queer that any of my Brothers or any of my Friends should feel towards me anything but goodwill to be sure I told him some plain truths but as they were truths he ought to have received them as for his good, but I am not the only or first person that has made others angry by telling them the truth, however I have said all I shall unless I am invited to say more by himself, he is in a bad state of feeling towards his own friends & I hope it may soon give way to better feelings & I shall try & do what I can to promote the same

I think if You would just write to him a Friendly letter You would help the matter of reconciliation on in a great measure, for he feels as if all were against him & the fact of Your not going to see him or writing to him gives it a semblance of reality, so I hope You will write to him even if You have no especial Business

I believe that Hiram is the only one with whom he at present fellowships & they have been at swords points often

I saw or had read to me a portion of a Letter from Your neighbor Spaulding concerning a Doctor Allin that formerly lived here in Buffalo & my opinion of him was solicited. as it regards his skill as a medicine man I do not know much about it having never had any occasion to employ him or any of the paternity & I hope You will not. I have seen some that he prescribed for & they say that he done them much good but have but little faith in any medicine or Doctor & probably nature done as much for them as physic & therefor any opinion from me might be of little use to any one, as it regards that matter for which he was tried & aquitted here I think it to have originated in malice & falsehood & so did the Jury as they acquitted him of the charge

But one thing You will find him to be as all other John Bulls are a great Brag & as generaly they are great Liars also I presume he will not be an exception to the rule So you can gather from that my ideas 

I am an advocate of cold water Temperance & they will in most cases promote Health & you can snap You snap Your fingers at the faculty & all Quacks & go on You may rejoicing

I have about Send to You the usual quantity of writing so shall as usual bid You good bye & may all the choice Blessings of Heaven ever attend You & Yours is the prayer ever of Your Brother Amen 

H.G. White

## Images

Page 1: [IMG_3049](./../../../images/White_letters-images/IMG_3049.html). Page 2: [IMG_3050](./../../../images/White_letters-images/IMG_3050.html) Page 3: [IMG_3051](./../../../images/White_letters-images/IMG_3051.html) Page 4: [IMG_3052](./../../../images/White_letters-images/IMG_3052.html)






## Notes



refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Charles H. White](./../../../people/Merrill-line/White-line/Charles_H._White.html)
refersto::[George William White](./../../../people/Merrill-line/White-line/George_William_White.html)
refersto::[Ann Quayle](./../../../people/Merrill-line/White-line/Ann_Quayle.html)
refersto::[Ann Eliza White](./../../../people/Merrill-line/White-line/Candace-Smith-line/Ann_Eliza_White.html)
refersto::[William E. White](./../../../people/Merrill-line/White-line/William_E._White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[Henry George White 2](./../../../people/Merrill-line/White-line/Henry_George_White_2.html)
refersto::[Syrena Adams](./../../../people/Merrill-line/White-line/Syrena_Adams.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)