
 

refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Candace Smith](./../../../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)


## Notes

Ebenezer reports that Candace's health is good, but she will be dead in less than two months from the date of this letter.


## Synopsis

Ebenezer in Burlington writes to Horatio Nelson in Panton.

Although the immediate prompt to write is in reply to a "buisness letter" from Horatio Nelson, the family news includes report of Artemas setting out for California as a '49er seeking gold. It is not clear how long he stayed in California. The census of 1850 shows Artemas back at home in Keeseville ten months later (September 19, 1850), but in letters of 1852, Ebenezer refers to him as being in California.
## Transcription

Burlington Nov 18 1849

I read your Buisness Letter and should have answered it before but have buisy in preparing for winter that I had no time I have ordered your paper to Vergennes which I suppose you have got before this you can have them on thursdays Hiram has got the money on your Note he says the Banks will not give a receipt for Monies deposited but he would send you the money when he got time. your Mother is prety well but I am rather off of the hooks at presant Adaline is so that She keeps about house She is not as well as Hirams Wife your Mother and I went to Keeseville a week ago last thursday to take our leave of Artemas who started for California a week ago las Saturday morning I saw him about two minutes on the wharfe at Burlington and gave him a final goodby he said he would write me from N. york but I have rece'd no letter Adaline wants you to bring 20 lb of Butter when you come to see us you undoubtedly will come in the Cars as that is the most genteel way of traveling now a days our love to all

Eben White H.N. White

this is all the pape I have
