
 




## Synopsis


Ebenezer and Adaline White in Burlington write to Horatio Nelson White in Panton.

Family news includes updates from Hiram prospecting for gold in California, Horatio Nelson falling two votes short of election to the Vermont state legislature, and a request from Adaline to send 30 or 40 pounds of butter to Burlington on the train.

## Transcription

Burlington Oct. 30 1851

 

My Son Nelson There was a time when I and you used to corrispond by letter, but that time appears to be past and gone by whose falt whether my own or yours I am not able to tell when I wrote to you or you to me. I should like on my part to renew that corispondenceces tharefore I now begin I have nothing in particular to write but will write to let you know I think of you & care for you we are as well as usual. *hoping these few lines will find you enjoying the same blessings* it seems to me *you* have not paid us a visit for a very long time I don't remember, but one thing I remember that is that little *rogue* of a Candace has not ben to see us for a long, long tim, we all want to see her very much she must not let those fals reports deter her coming for I think we all love her I should love her if it ware only for her name which will ever be Dear to me. I was disappinted to learn that -that- you had given up going to Buffalo I ware sory for it, but undoubtedly you know your own buisness better than I do, but it does appear to me that you never will have a better time if as good. I rec'd a letter from George a few day since they ware still hoping and expecting you wold yet come, but they will hope in vain I do not think now that you ever will see Buffalo, you have talked so much about it without caning the talk into affect. I hope Friend will go and see his uncle George when he arrive at the age of 21 and Frances when she becomes 18 and so on if they all live. George tells of coming out here in the winter he can as well come in the winter as any time we had or Cynthia had a letter from Hiram the maile before the last he does not say how he is doing only he is drawing dirt with his Mule and Cart to the River to wash and that he is as Fat as a Bear & Black as an Indian but does not tell of ever coming hom. I suppose Cynthia has told all to Francies as I understan they are in corispondane with each other and now I have writen to you I shall expect you will return the complement it is only just three cents as Jack Pomroy said when some of you boys found a bundle of his papers and ran all over Toronto to give them to him one cold night he said here is just six cents I do not send my compliments to you and Family but I real love to you all

you Father Ebenr White 

H.N. White Esq.

Henry says you come within two votes of going to the legislator

Brother Nelson

I wish to know if you could put me down 30 or 40 pounds of Butter if so you may get a tub and put it in and if it would come safe in the cars put it aboard if none of you are coming up, I should be glad if I could get a fat *hog* but do not know how it would be about getting it here you will please inform me how it is,

Yours Adaline


N.B. everything you send will be so much my gane.

E.W.


## Notes

The "little rogue of a Candace" is Horatio Nelson's daughter [Candace White](./../../../people/Merrill-line/White-line/Candace_White.html), now about 9

Friend is about 18 now; Frances about 17

Who is Jack Pomroy ?


refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Candace White](./../../../people/Merrill-line/White-line/Candace_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Friend Adams White](./../../../people/Merrill-line/White-line/Friend_Adams_White.html)
refersto::[Frances E. White](./../../../people/Merrill-line/White-line/Frances_E._White.html)
refersto::[Cynthia Sawyer](./../../../people/Merrill-line/White-line/Cynthia_Sawyer.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)
