refersto::[Melvin Elwood Sheirel](./../../Melvin_Elwood_Sheirel.html)

## Source citation

California State Archives; Sacramento, California; _Secretary of State California State Archives Folsom Prison Registers_

Ancestry.com. _California, U.S., Prison and Correctional Records, 1851-1950_. Provo, UT, USA: Ancestry.com Operations, Inc., 2014.

Original data:

Department of Corrections. Folsom State Prison Records, 1879–1949. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. San Quentin State Prison Records, 1850–1950. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. Youth Authority Dept. Records, 1872–1950. ID California State Archives, Office of the Secretary of State,

## Transcription

 

| Register No. 66626-A | Name Sheirel, Melvin E. | | | TRANSFERRED FROM SAN QUENTIN | Received SEP 6 1946 | |
| --------------------------- | ----------------------------- | ------------------------- | ---------------------- | ---------------------------- | ------------------------------------------------------------------------- | --- |
| Crime Burg. 2nd & 2 Prs | Age 32 Date of Birth 10-11-13 | Complexion Med Race White | | Nativity of Mother Illinois | Arrived in US via Native | |
| Sentence 1-15 yrs CC W/Pr T | Height-- Feet 5 Inches 9 3/4 | Occupation Oiler | | Nativity of Father Missouri | Arrived in California 1926 | |
| County LA # 107189 | Weight 163 Build Musc. | Education 12 yrs | Social status Divorced | Counsel | Nearest relative Mother: Mrs. M. Sheirel 869-No. Gower, Hollywood, Calif. | |
| Judge Wm. R. McKay | Color Eyes Hazel | | Children 1 | Plea | | |
| Nativity Missouri | Color of Hair Med-Brn | | Brothers 0 Sisters 2 | Military service None | | |


Cut sc. under rt. eyebrow. Small birthmark rt. shldr.

AUG 16 1946 PAROLE SUSPENDED BA. at S.F.

NOV 21 1946 TRANS. TO SAN QUENTIN 5-24-41 SP. SQ. # 66625. Burg. 1st. & A.D.W. 5-Life & 0 - 10 yrs. CC.

Paroled 4-21-44 from Chino.
