refersto::[Melvin Elwood Sheirel](../../../Melvin_Elwood_Sheirel.html)

## Source

> This is a printed card completed with a typed information.


California State Archives; Sacramento, California; _Secretary of State California State Archives San Quentin Prison Registers_

Ancestry.com. _California, U.S., Prison and Correctional Records, 1851-1950_. Provo, UT, USA: Ancestry.com Operations, Inc., 2014.

Original data:

Department of Corrections. Folsom State Prison Records, 1879–1949. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. San Quentin State Prison Records, 1850–1950. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. Youth Authority Dept. Records, 1872–1950. ID California State Archives, Office of the Secretary of State, Sacramento, California .

## Transcription

### California State Prison at San Quentin

Reg. No. 66625

Name Melvin E. Sheirel 

Color White

County LOS ANGELES

Received MAY 24 1941

Crime Burg 1st (459-PC) & ADW (245-PC)

Sentence 5-L & 0-10-CC

Occupation Oiler

Tattoos, marks and scars

Cut sc. under rt. eyebrow; Sm birthmark R. shoulder.
