refersto::[Melvin Elwood Sheirel](../../../Melvin_Elwood_Sheirel.html)

## Source

> This is a handwritten register


California State Archives; Sacramento, California; _Secretary of State California State Archives San Quentin Prison Registers_

Ancestry.com. _California, U.S., Prison and Correctional Records, 1851-1950_. Provo, UT, USA: Ancestry.com Operations, Inc., 2014.

Original data:

Department of Corrections. Folsom State Prison Records, 1879–1949. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. San Quentin State Prison Records, 1850–1950. ID California State Archives, Office of the Secretary of State, Sacramento, California. 

Department of Corrections. Youth Authority Dept. Records, 1872–1950. ID California State Archives, Office of the Secretary of State, Sacramento, California .
## Transcription

Page 176:


25- Melvin E. Sheirel 32 II M 262 III
32 MMM XMM 1

Recd. 5-24-41 : Ret as Chino Viol to SQ with new term 7-27-46

Trans to Chino 10-14-41 Par. 5/23/50(0) Disch from Parole 3/15/54.
