
## Transcription

James A. Merrill

1868-1924

His wife

Anna S. White

1870-1913


## Illustrations

- Site in Lakeview Cemetery: [IMG_0632](./../../images/Vermont_locations-images/Burlington-images/IMG_0632.html)
- Family headstone and individual footstones: [IMG_0629](./../../images/Vermont_locations-images/Burlington-images/IMG_0629.html)
- Inscription for James and Anna: [IMG_0634](./../../images/Vermont_locations-images/Burlington-images/IMG_0634.html)
- Footstone for James Merrill: [IMG_0630](./../../images/Vermont_locations-images/Burlington-images/IMG_0630.html), [IMG_0633](./../../images/Vermont_locations-images/Burlington-images/IMG_0633.html)
- Footstone for Anna Serena White: [IMG_0631](./../../images/Vermont_locations-images/Burlington-images/IMG_0631.html)


## Citation

Transcription from public domain photography listed here.

## Notes

refersto::[James Albee Merrill](./../../people/Merrill-line/James_Albee_Merrill.html)
refersto::[Anna Serena White](./../../people/Merrill-line/White-line/Anna_Serena_White.html)

The grave is monument [46553685 in findagrave](https://www.findagrave.com/memorial/46553685/james-albee-merrill?_gl=1*1k9x58k*_gcl_dc*R0NMLjE2NzU4MTEzMTEuQ05yRGc4N0RoUDBDRlVuZndBb2RnSmtKUEE.*_ga*ODQzNzA3Mjk1LjE2NzY5NzI1MDM.*_ga_4QT8FMEX30*MTY3Nzc5NjIzNS4xNS4xLjE2Nzc3OTYzOTIuNjAuMC4w*_ga_B2YGR3SSMB*OGVlMzkwODMtZDc5OS00NzQxLTk3YjMtNmVmMGEyMThhY2U4LjU4LjEuMTY3Nzc5NjM5My41OS4wLjA.)

