 

refersto::[Wesley Hammond](./../../../people/Hammond-line/Wesley_Hammond.html)
refersto::[William Goheen Hammond](./../../../people/Hammond-line/William_Goheen_Hammond.html)
refersto::[Eliza A. Hammond](./../../../people/Hammond-line/Eliza_A._Hammond.html)
refersto::[Samuel Clayton Hammond](./../../../people/Hammond-line/Samuel_Clayton_Hammond.html)


## Notes


Who is "P.J. Hammond"?

Eliza presumably [Eliza A. Hammond](./../../../people/Hammond-line/Eliza_A._Hammond.html)
"Sam" could be [Samuel Clayton Hammond](./../../../people/Hammond-line/Samuel_Clayton_Hammond.html)




**Hammond Letter 4**

**Date**: Sept 8, 1861

**FROM**: Wesley Hammond [213]

**To**: "Reverend Bill" (W. G. Hammond) [41]

**____________________**

 

Valley Mountain Camp, Virginia

 September the 8th 1861

 

Reverend Bill:

I have written a great many letters home and still more to friends but I seldom if ever get anything in return, being so often disappointed I have almost concluded to quit writing altogether. It looks a little like we will have to quit soon whether we want to or not for it is hard scraping to get paper to write a letter now. I have been looking for a line or two from you eccasionally but not one have I received. I wrote to P. J. Hammond [33] and Mildred [1808]and sent them by a wagoner yesterday. And to Eliza [39] a few days before to have me some clothes made and send to me. Probably she will not get it so I will state again what I wanted. One pr. grey Janes pants with a red stripe 3/4 of an inch wide up each seam, a fatigue shirt cut of the same kind ef goods. This is to be made so that it can be worn in or outside of my pants. You saw cur uniform and can tell how it ought to be made. 2 or 3 pairs ef socks, a pr. drawers, a flannel under shirt and a checked shirt with a collar made to it. Our clothes are furnished us but if we furnish them we get paid for them in a short time. Tell them if they have none of that kind of Janes try and swap for some other of the same color for the fatigue. I don’t care much about the color of the pants. I reckon I will have to ask you to get me the shirting cloth as I am about out of money and a strong pr. of peg shoes. No. 9. It is impossible to get any here or any where close. I wrote in my other letters that John Ribble was coming over here with a wagon and would bring them over. He is here now and as soon as he gets home he is coming back with a wagon and will bring them with the things he will bring for Smith’s boys [11], [28]. You seem to have it attended to. Sam [37] wrote to John [34] to have him a pr. of good boots he also wants 2 or 3 pr socks. *********are about all that I am obliged to have. But there are some other things that would be of some service to me if we takee up winter quarters over here. A pair mittens the red comfort I left at home. and a pr of shoes. Ribble is also going to bring Smith's [11], [28] something in the way of eatables if they at home want to send a little something they can do so. If they do don’t send any cooked victuals unless they are sure they will keep. Smiths [11], [28] Sam [37] and I tent together as we did at Lynchburg. We live quite rough by here more so than if we were on the railroad. Others are getting boxes from home which made us wish for a little something too. A good cheese would be so good.. I wrote to Peter [33] that we were looking for a fight almost every hour. It has rather died away and there is not so much prospect for it now. I received the news a short time I wrote him that the enemy had fallen back. Our forces moved up in a mile and a half of them The Tenn. forces were about pitching into them but Lee would not let them. I have no time to write any news. Infact I deem it useless as I have Just written several letters hone. Sam [37] and I are well and standing up to camp life better than the most of the Reg. I would like to write you a long letter but I have not time. We are fixing to move ever the mountains tomorrow. I will leave this letter unsealed until morning and if I have time to write more will do. Give my love to Mother [16] and tell her I am getting along well. To Kittie [ ] and Bonnie [ ] and all the other girls. Tell Kittie I have written to almost all my friends but her. Will write to her if I have time and paper to write it on. Tell Ann [ ] if I have a good white shirt at home send it to me with the other things. Write me soon.

Yours sincerely,

 

Wesley Hammond

