---
engine: julia
---

# Family history

## Source material

I'm starting by sharing transcriptions of  the [primary source material](./sources/index.qmd) I'm collecting for family historical research. I'm transcribing and annotating these documents in an [Obsidian vault](https://obsidian.md). The transcriptions are directly exported to the [transcriptions section](./sources/transcriptions/) of this web site. The annotations are used to build pages for individuals identified in the sources. You can browse the transcriptions

You can use the sitewide search (the magnifying glass icon in the upper right corner of each page) to find material anywhere on the site. You can explore the individuals from this [index by last name](./sources/last-names/).

::: {.callout-tip title="Finding individuals"}
 People who used more than one last name appear under each, so you should be able to find them using any of their last names.
:::



## Commentary and interpretation

I'm separately posting notes in the [blog section](../posts.qmd) of this site. It's not my intention to develop any kind of overarching historical narrative. Instead, I'm choosing to write about isolated episodes and people I find interesting, and can document adequately to support my text. My intention is to post only about when I can link directly to the relevant source material.



### An initial project

I'm beginning (slowly) in 2025 by focusing on a collection of letters to and from members of the family of [Ebenezer White](./sources/people/Merrill-line/White-line/Ebenezer_White.html) (1779-1853).

- see an introduction to the [White family letters](./whiteletters/)


### Limitations


In writing about particular topics, I am setting two limits: I won't write about people with living children (as far as I know), or who have died recently, whether or not they have children. I'm struggling to define "recently", but in any case, members of the nineteenth-century White family I am starting will fall within any boundaries I might choose.

