
## Source

## Transcription

*page 23 in box*

Ebenezer White

Estate

Warrant of Division

---

Recorded

*page 24 in box*

State of Vermont

District of Chittenden S.S.

The Hon. the Probate Court for the District of Chittenden.

To Noble Lovely Henry H. Mitchell and Mides A. Evarts, of Burlington,

Greeting.

Whereas application in writing hath been made to the Probate Court for the District of Chittenden by A. White one of the heirs to the estate of Ebenezer White late of Burlington in said District deceased, intestate for a division of said estate and the several persons interested in said estate have been notified thereof agreeably to law.

Therefore in pursuance of the statute in such case provided the said Court doth hereby appoint you a Committee and invest you with full power and authority for that purpose.

In discharging the duties of said appointment you will appraise all the estate of the said deceased now in the hands of the said Administrator you will then faithfully and impartially divide and make partition of said estate (after firstly paying the said Administrators the sum of nine dollars and eighty two cents ($9.82) ) being the balance due them on the settlement of their account)


*page 25 in box*

to and among Horatio N. White, Adaline White, Artemas White, George White and Hiram S. White, the heirs of the said Ebenezer White in the proportions following that is to say

- To the said Horatio H. White an equal fifth portion thereof
- To the said Adaline White an equal fifth portion thereof reckoning however as part and parcel of her said share the sum of sixty five dollars which hath heretofore been assigned to the said Adaline White in Pew No. 77 in the Congregational Church in Burlington by a decree of this Court she having accepted said assignment agreeable to law.
- To the said Artemas White one equal fifth part thereof.
- To the said George White one equal fifth part thereof.
- To the said Hiram S.White one equal fifth part thereof.

When you proceed to the work you will give due notice to all parties concerned.

*page 26 in box*





## Notes

refersto::[Ebenezer White](./../../../people/Merrill-line/White-line/Ebenezer_White.html)
refersto::[[Lovely Henry]]
refersto::[[Henry H. Mitchell]]
refersto::[[Midas A. Evarts]]

refersto::[Adaline White](./../../../people/Merrill-line/White-line/Adaline_White.html)

refersto::[Horatio Nelson White](./../../../people/Merrill-line/White-line/Horatio_Nelson_White.html)
refersto::[Artemas White](./../../../people/Merrill-line/White-line/Artemas_White.html)
refersto::[Henry George White](./../../../people/Merrill-line/White-line/Henry_George_White.html)
refersto::[Hiram Smith White](./../../../people/Merrill-line/White-line/Hiram_Smith_White.html)
