---
engine: julia
---

# Neel

- [Abner Duncan Neel](./../people/Neel-line/Abner_Duncan_Neel.html)
- [Bee Neel](./../people/Neel-line/Bee_Neel.html)
- [Bell Starr](./../people/Neel-line/Bell_Starr.html)
- [Betty Neel](./../people/Neel-line/Betty_Neel.html)
- [Duncan Neel](./../people/Neel-line/Duncan_Neel.html)
- [Eda J. Neel](./../people/Neel-line/Eda_J._Neel.html)
- [Edith Jane Davidson](./../people/Neel-line/Edith_Jane_Davidson.html)
- [Eleanor McFarland](./../people/Neel-line/Eleanor_McFarland.html)
- [Elizabeth Blakely](./../people/Neel-line/Elizabeth_Blakely.html)
- [Elizabeth Busby](./../people/Neel-line/Elizabeth_Busby.html)
- [Florence Lelia Burkett](./../people/Neel-line/Florence_Lelia_Burkett.html)
- [James Davidson Neel](./../people/Neel-line/James_Davidson_Neel.html)
- [James Marion Neel](./../people/Neel-line/James_Marion_Neel.html)
- [James Marion Neel, Jr.](./../people/Neel-line/James_Marion_Neel,_Jr..html)
- [Jessie Elaine Manuel](./../people/root/Jessie_Elaine_Manuel.html)
- [Jessie Elaine Manuel](./../people/root/Jessie_Elaine_Manuel.html)
- [Josephine Neel](./../people/Neel-line/Josephine_Neel.html)
- [Mary Louise Neel](./../people/Neel-line/Mary_Louise_Neel.html)
- [Maude Graham](./../people/Neel-line/Maude_Graham.html)
- [Maxine Woods](./../people/Neel-line/Maxine_Woods.html)
- [Northern cemetery](./../ne-towns/notes/Northern_cemetery.html)
- [Robert W. Neel Jr.](./../people/Neel-line/Robert_W._Neel_Jr..html)
- [Robert Wilburn Neel](./../people/Neel-line/Robert_Wilburn_Neel.html)
- [Sarah Elizabeth Neel](./../people/Neel-line/Sarah_Elizabeth_Neel.html)
- [Sarah Jane Barton](./../people/Neel-line/Sarah_Jane_Barton.html)
- [Thomas Neel](./../people/Neel-line/Thomas_Neel.html)
- [Willie Saudek Blanton](./../people/Neel-line/Blanton-line/Willie_Saudek_Blanton.html)
- [Willie Saudek Blanton](./../people/Neel-line/Blanton-line/Willie_Saudek_Blanton.html)