---
engine: julia
---

# White

- [Adaline White](./../people/Merrill-line/White-line/Adaline_White.html)
- [Alice Elizabeth White](./../people/Merrill-line/White-line/Alice_Elizabeth_White.html)
- [Ann Eliza White](./../people/Merrill-line/White-line/Candace-Smith-line/Ann_Eliza_White.html)
- [Ann Quayle](./../people/Merrill-line/White-line/Ann_Quayle.html)
- [Anna Serena White](./../people/Merrill-line/White-line/Anna_Serena_White.html)
- [Artemas White](./../people/Merrill-line/White-line/Artemas_White.html)
- [Benjamin White](./../people/Merrill-line/White-line/Benjamin_White.html)
- [Candace Myra White](./../people/Merrill-line/White-line/Candace_Myra_White.html)
- [Candace Smith](./../people/Merrill-line/White-line/Candace-Smith-line/Candace_Smith.html)
- [Candace White](./../people/Merrill-line/White-line/Candace_White.html)
- [Conras M. White](./../people/Merrill-line/White-line/Conras_M._White.html)
- [Cynthia Sawyer](./../people/Merrill-line/White-line/Cynthia_Sawyer.html)
- [Ebenezer White](./../people/Merrill-line/White-line/Ebenezer_White.html)
- [Edith Bailey](./../people/Merrill-line/White-line/Edith_Bailey.html)
- [Eliza Ann White](./../people/Merrill-line/White-line/Eliza_Ann_White.html)
- [Ellen Grandey](./../people/Merrill-line/Grandey-line/Ellen_Grandey.html)
- [Elsie White](./../people/Merrill-line/White-line/Elsie_White.html)
- [Eugene Richard White](./../people/Merrill-line/White-line/Eugene_Richard_White.html)
- [Euphemia Armstrong](./../people/Merrill-line/White-line/Euphemia_Armstrong.html)
- [Florence White](./../people/Merrill-line/White-line/Florence_White.html)
- [Frances E. White](./../people/Merrill-line/White-line/Frances_E._White.html)
- [Frederick D. White](./../people/Merrill-line/White-line/Frederick_D._White.html)
- [Friend Adams White](./../people/Merrill-line/White-line/Friend_Adams_White.html)
- [George Nelson White](./../people/Merrill-line/White-line/George_Nelson_White.html)
- [George William White](./../people/Merrill-line/White-line/George_William_White.html)
- [H.C. White](./../H.C._White.html)
- [Henry George White](./../people/Merrill-line/White-line/Henry_George_White.html)
- [Henry George White 2](./../people/Merrill-line/White-line/Henry_George_White_2.html)
- [Henry Sawyer White](./../people/Merrill-line/White-line/Henry_Sawyer_White.html)
- [Hiram Smith White](./../people/Merrill-line/White-line/Hiram_Smith_White.html)
- [Hiram White](./../people/Merrill-line/White-line/Hiram_White.html)
- [Horatio Nelson White](./../people/Merrill-line/White-line/Horatio_Nelson_White.html)
- [James Herbert White](./../people/Merrill-line/White-line/James_Herbert_White.html)
- [Jennie Marks Warner](./../people/Merrill-line/White-line/Jennie_Marks_Warner.html)
- [Lydia R. Brumley](./../people/Merrill-line/White-line/Lydia_R._Brumley.html)
- [Lydia White](./../people/Merrill-line/White-line/Lydia_White.html)
- [Mary Ella White](./../people/Merrill-line/White-line/Mary_Ella_White.html)
- [Mollie Grandey White](./../people/Merrill-line/White-line/Mollie_Grandey_White.html)
- [Ruth Wilson](./../people/Merrill-line/White-line/Wilson-line/Ruth_Wilson.html)
- [Sarah Maria White](./../people/Merrill-line/White-line/Sarah_Maria_White.html)
- [Susan D. Winslow](./../people/Merrill-line/White-line/Susan_D._Winslow.html)
- [Susan Prince](./../people/Merrill-line/White-line/Susan_Prince.html)
- [Susan Spaulding](./../people/Merrill-line/White-line/Susan_Spaulding.html)
- [Syrena Adams](./../people/Merrill-line/White-line/Syrena_Adams.html)
- [Thankful Holland](./../people/Moses_Smith_connections/Thankful_Holland.html)
- [William E. White](./../people/Merrill-line/White-line/William_E._White.html)